Update to fix view on image validation failure
internetarchive/openlibrary pull request #10009
Opened 2024-11-08 01:18 UTC by jimchamp

Closes: #10086
Follow-up to #9966

Fixes "Unable to render this page" message being rendered in cover modal when image validation fails.

### Technical

Adds `validate` method to image validator.  Replaces existing image validation calls with a single `validate` call in the `upload` method.

Validation errors are now propagated from `upload` to the image upload handler.  When a validation error occurs, the `covers/add` template is rendered with an error message.

### Testing

Attempt to upload an invalid image to the covers service.  Expect to see a generic error message.

An invalid image has at least one of the following properties:
- Is greater than 10MB size
- Ends with an invalid file extension
- Is not actually an image

### Screenshot

![Screenshot 2024-11-07 171051](https://github.com/user-attachments/assets/394e311f-c924-4798-900d-159d81ae9552)

### Stakeholders

2024-11-12 01:49 UTC, cdrini requested changes

2025-03-03 21:00 UTC, mekarpeles commented
We need to make sure `webp` is allowed (via html validation); some js changes may still need to happen for webp support and image uploads. @RayBB may have merged the js side of things?

2025-03-03 21:11 UTC, RayBB commented
Yes WebP is now supported on upload.
Avif isn't possible because our underlying library doesn't support it yet.

2025-03-17 11:34 UTC, RayBB commented
@jimchamp this is assigned to me but I'm a little unclear on if you actually need something from me for this?

2025-12-15 17:42 UTC, closed without merging