Centered the Google Login button
internetarchive/openlibrary pull request #10079
Opened 2024-11-23 10:43 UTC by shikharchaurasia

Closes #10071 

This PR aims to center the third party Google login button across different views.

### Technical

Previously, the width attribute of the ia-third-party-logins ID was set to auto. This was causing it to occupy a width of 300px by default, and leaving a gap of 50px after the right end of the Google button, whose width was measured to be 250px. This was confirmed by using the box model upon inspecting elements. As a result, even though the 300px 'outer container' seemed to be centered, because the Google button's iFrame only occupied 250px, it did not appear to be centered.

I modified the width attribute to 250px, which does not leave any gap, and properly centers the Google login button across all viewing configurations, desktop and mobile included.

### Testing

Tester/reviewer can launch the login page, and compare the third party Google login button's location in comparison to when this issue was reported. It can be observed the button is now centered. Tester can also test different devices by toggling device toolbar, and selecting different devices to confirm this PR fixes the issue.

### Screenshot

![image](https://github.com/user-attachments/assets/6dda0847-22c9-4dd1-9a8a-9f4cbba69008)
Previously, with width being set to auto for the iframe, there was a gap of 50px leftover after the end of the iframe, resulting in the Google login button not being centered.
![image](https://github.com/user-attachments/assets/3dc43628-70b4-43fb-9921-85d52b7157fd)
After setting the width correctly to 250px, the Google login button is now centered. (iPhone view)
![image](https://github.com/user-attachments/assets/ea01d85a-2131-47e2-beb9-7a1dd6862fc1)
After setting the width correctly to 250px, the Google login button is now centered. (Desktop view)

### Stakeholders

@RayBB - tagging you for now as you assigned me this issue. Please let me know if someone else needs to be tagged, and i will do so.

2024-11-23 16:33 UTC, RayBB commented
I will review monday. It looks like your fix works but I think it's preferably to use something like css flex to center align it this way if the width changes in the future elsewhere this will still be aligned.
@shikharchaurasia

2024-11-29 20:42 UTC, RayBB requested changes
@shikharchaurasia lets use css flex to fix this instead of a manual width

2024-12-06 06:03 UTC, RayBB commented
@shikharchaurasia are you still working on this? If I don't hear back by Monday I'll assume not and close this so someone else can work on it.

2024-12-08 05:36 UTC, shikharchaurasia commented
Hi @RayBB, yes I am working on this. Will push a fix for this using flex styles shortly. Apologies for the delay in response.

2024-12-09 07:41 UTC, shikharchaurasia commented
Hi @RayBB,

The third-party iframe has a fixed width of 250px, and attempts to set the width to auto or 100% result in the browser defaulting to a width of 300px. This causes misalignment and unnecessary gaps in the layout.

To address this, I propose setting a max-width of 250px while keeping the width set to 100%. This approach ensures the iframe respects its designed dimensions but remains responsive to potential changes in the parent layout. By constraining the maximum width, the solution prevents the iframe from exceeding its intended size while still adapting to the layout dynamically.

This balances responsiveness with the fixed design requirements of the third-party iframe, ensuring alignment and flexibility in case of future layout changes.

Please let me know if this approach is acceptable.

2024-12-10 04:34 UTC, shikharchaurasia commented
Hi @RayBB 

I was initially trying what you suggested on the iframe with ID ia-third-party-logins - these changes did not seem to work.

However on analyzing the code further, I observed that the flexbox changes could be applied onto the iframe nested within the document that is rendered by Google, with ID g_id_signin. Applying these flexbox styles there seems to work, aligning the button on the center.

![image](https://github.com/user-attachments/assets/395fd7a4-0b5f-4caf-bf59-7089df367c2e)

As a result, I have reverted all my previous changes, and only made changes to the page-signup.less file, by adding the flexbox style for g_id_signin.

2024-12-10 04:59 UTC, RayBB commented
@shikharchaurasia I tested your change and it doesn't work because you can't apply styles to the contents of an iframe.

Lets revert to https://github.com/internetarchive/openlibrary/pull/10079/commits/85a033b70c579d524a311cb85484684412ed3507 and I think we can get this merged in this week.

2024-12-10 05:03 UTC, shikharchaurasia commented
I have reverted back to the max-width approach in the latest commit.

2024-12-10 05:04 UTC, RayBB approved these changes
This is working (when I test with changing in the devtools on prod).

Need @cdrini to give a final check and merge

2024-12-11 16:42 UTC, closed without merging