changed the innerHTML with textContent for security reasons
internetarchive/openlibrary pull request #10105
Opened 2024-12-02 18:10 UTC by ronibhakta1

Closes #10097 
Hey @jimchamp i have made the changes in innerHTML with textContent for security reasons as you mentioned. 

### Technical

changes in the `team.js` file to increase the security.

### Testing

no build errors and no other syntactical errors. all changes are preferable as per the documentations 

### Screenshot

### Stakeholders

2024-12-03 00:06 UTC, jimchamp requested changes
Thanks @ronibhakta1!  I've confirmed that everything is working.

Happy to merge this once the commented code on lines 134-137 are removed.

2024-12-03 12:09 UTC, ronibhakta1 commented on openlibrary/plugins/openlibrary/js/team.js
> +            // memberDepartment.textContent = `${member.departments}`;
Yeah sure i will update you with the changes

2024-12-03 13:27 UTC, ronibhakta1 commented on openlibrary/plugins/openlibrary/js/team.js
> +            // memberDepartment.textContent = `${member.departments}`;
> Can you remove these comments altogether?

hey @jimchamp  i made the required changes you can check that out !

2024-12-04 19:36 UTC, jimchamp approved these changes
Thanks @ronibhakta1!

2024-12-04 19:37 UTC, merged