[WIP] feat: use author known identifiers in import API
internetarchive/openlibrary pull request #10110
Opened 2024-12-03 02:10 UTC by pidgezero-one

# ===This is a WIP and is not ready for review===

this should be squash merged to avoid conflicts with https://github.com/internetarchive/openlibrary/pull/10092, which this is split off of (I am not a git commit history expert). this depends on #10092 being merged because it depends on a new author method in that PR

Closes #9448
Closes #9411

### Technical
- import pipeline matches by OL ID first, then remote_ids (which should have been filled out with wikidata identifiers via backfill) (and as long as there aren't too many conflicts), then fall back to existing logic of matching by name
- import records can use an "identifiers" field in the author dict, which is a dict in the form of { "viaf": "blahblahblah" ...etc }. related schema update PR: https://github.com/internetarchive/openlibrary-client/pull/419

TODO: unit tests
TODO: how do we flag conflicts to librarians?

The import model is expanded by adding some additional logic to write to the author's `remote_ids` when detected in the incoming json object, and search Infogami against those remote ids to detect if the author already exists. The incoming `author` dict can store an optional `remote_ids` field to contain these (i.e. viaf stored in `author["remote_ids"]["viaf"]`), except for OL ID, which is not a remote identifier, so it is expected at `author["key"]`.

Issues:
- Importing books returns a 200 success, but the author's page still says 0 works

### Testing

tested using the output from https://github.com/internetarchive/openlibrary/pull/9674

To test the import, I wasn't sure how to hit /api/import with user credentials, so I disabled the `if not can_write():` condition in openlibrary/plugins/importapi/code.py as well as the `if not account_key:` condition in openlibrary/catalog/add_book/__init__.py, and copy-pasted the printed JSON records into a Postman request body.

 Example:

```json
{
    "title": "Equitation",
    "source_records": [
        "wikisource:en:Equitation"
    ],
    "identifiers": {
        "wikisource": [
            "en:Equitation"
        ]
    },
    "languages": [
        "eng"
    ],
    "ia_id": "wikisource:en:Equitation",
    "publish_date": "1922",
    "authors": [
        {
            "name": "Henry L. de Bussigny",
            "remote_ids": {
                "wikidata": "Q16862522",
                "viaf": "305913238",
                "isni": "0000000424758764",
                "project_gutenberg": "40106"
            }
        }
    ],
    "publishers": [
        "Wikisource"
    ]
}
```

This responds successfully with:

```json
{
    "authors": [
        {
            "key": "/authors/OL15A",
            "name": "Henry L. de Bussigny",
            "status": "created"
        }
    ],
    "success": true,
    "edition": {
        "key": "/books/OL18M",
        "status": "created"
    },
    "work": {
        "key": "/works/OL9W",
        "status": "created"
    }
}
```

Viewing this author key at `http://localhost:8080/authors/OL15A` shows that the strong identifiers were imported correctly:

<img width="177" alt="image" src="https://github.com/user-attachments/assets/a21c610d-762d-49a7-926b-e8b317ceb9af">

Editing the author verifies this as well:
<img width="518" alt="image" src="https://github.com/user-attachments/assets/a397ecb4-2273-46b4-85a0-7ce34f89710c">

I then created a test book record whose author uses the same VIAF but has a missing name:

```json
{
    "title": "Equitation test",
    "source_records": [
        "wikisource:en:Equitation_test"
    ],
    "identifiers": {
        "wikisource": [
            "en:Equitation_test"
        ]
    },
    "languages": [
        "eng"
    ],
    "ia_id": "wikisource:en:Equitation_test",
    "publish_date": "1922",
    "authors": [
        {
            "name": "viaf test",
            "remote_ids": {
                "viaf": "305913238"
            }
        }
    ],
    "publishers": [
        "Wikisource"
    ]
}
```

The response shows that the author was successfully matched to an existing one by VIAF:

```json
{
    "authors": [
        {
            "key": "/authors/OL15A",
            "name": "Henry L. de Bussigny",
            "status": "matched"
        }
    ],
    "success": true,
    "edition": {
        "key": "/books/OL19M",
        "status": "created"
    },
    "work": {
        "key": "/works/OL10W",
        "status": "created"
    }
}
```

This also works for OL IDs, which uses a slightly different fetch query than the other strong identifiers do:

```json
{
    "title": "Equitation test 2",
    "source_records": [
        "wikisource:en:Equitation_test_2"
    ],
    "identifiers": {
        "wikisource": [
            "en:Equitation_test_2"
        ]
    },
    "languages": [
        "eng"
    ],
    "ia_id": "wikisource:en:Equitation_test_2",
    "publish_date": "1922",
    "authors": [
        {
            "name": "author ol_id test",
            "key": "/authors/OL15A"
        }
    ],
    "publishers": [
        "Wikisource"
    ]
}
```

```json
{
    "authors": [
        {
            "key": "/authors/OL15A",
            "name": "Henry L. de Bussigny",
            "status": "matched"
        }
    ],
    "success": true,
    "edition": {
        "key": "/books/OL23M",
        "status": "created"
    },
    "work": {
        "key": "/works/OL14W",
        "status": "created"
    }
}
```

Importing optional cover images also works:
<img width="801" alt="image" src="https://github.com/user-attachments/assets/2cbd536f-f693-4329-8dd3-ac92fe0f01ec">

I added support for all identifiers found in identifiers.yml, except for Inventaire, which I couldn't find in Wikidata:
<img width="235" alt="image" src="https://github.com/user-attachments/assets/c33723f1-693d-4ba3-bed8-91036069aa91">

### Screenshot

### Stakeholders

2025-02-09 17:43 UTC, pidgezero-one commented on scripts/providers/import_wikisource.py
todo: can this script's python library dependencies be used without having to add them to the requirements.txt for the whole of OL?

2025-02-20 18:14 UTC, cdrini requested changes
Open questions:

- `key` vs `ol_id` in author import record
- `remote_ids` vs `identifiers` in author import record
    - ^ For both of these, since there are subtle differences between eg `remote_ids` (authors, Dict[str, str]) and `identifiers` (works/editions, Dict[str, list[str]]), I think it might be easiest if we re-use the shape of our existing open library records. So `remote_ids: dict[str,str]` for authors, and `key` to hold the open library key.
- Should any identifier conflicts cause import error?
     - As a first stab, let's error on precaution, and error on any identifier conflicts.

2025-02-20 18:14 UTC, cdrini commented on openlibrary/core/models.py
> +        if conflicts > matches:
Discussion: Should this bail if there are any conflicts?

2025-02-20 18:14 UTC, cdrini commented on scripts/providers/import_wikisource.py
> +                        if author.birth_date is not None
```suggestion
                        if author.birth_date
```

2025-02-20 18:14 UTC, cdrini commented on scripts/providers/import_wikisource.py
> +                        if author.death_date is not None
```suggestion
                        if author.death_date
```

2025-02-20 18:14 UTC, cdrini commented on scripts/providers/import_wikisource.py
> +                        if len(author.identifiers.keys()) > 0
```suggestion
                        if author.identifiers
```

2025-02-20 18:14 UTC, cdrini commented on scripts/providers/import_wikisource.py
> +                    **({"ol_id": author.ol_id} if author.ol_id is not None else {}),
```suggestion
                    **({"ol_id": author.ol_id} if author.ol_id else {}),
```

2025-02-20 18:14 UTC, cdrini commented on scripts/providers/import_wikisource.py
> +                    contributor.identifiers[id] = obj[id]["value"]
```suggestion
                    contributor.identifiers[id] = val
```

2025-03-20 04:48 UTC, pidgezero-one commented on openlibrary/core/models.py
> +        output = {**self.remote_ids}
Ended up having to revert to this deconstruction - self.remote_ids is being treated as a Thing and not a dict, for some reason (despite every other operation on it in this codebase suggesting it should be a dict) so deepcopy fails.  I'm stumped on why that's happening.

2025-03-27 17:08 UTC, cdrini approved these changes
Lgtm! We tested on a call and importing is working like a charm! We've got some tweaks to the wikisource import script which we'll push up in a separate PR. Great work + perseverance on this one @pidgezero-one

2025-03-27 17:08 UTC, merged