Using book cover sizes to prevent layout shifting
internetarchive/openlibrary pull request #10145
Opened 2024-12-13 03:19 UTC by anna-ayn

Closes #9739 

feature

### Technical

* Added `width` and `height` methods to the `Image` class in `openlibrary/core/models.py` to retrieve image dimensions.
* Modified the `OLCarousel.vue` component to include a `cover-container` div and set default cover image dimensions. Also added responsive styles for different screen sizes. 
* Updated the `createActiveShowcaseItem` function in `ShowcaseItem.js` to accept a `desiredHeight` parameter and set image dimensions dynamically based on the aspect ratio. 
* Adjusted the `book.less` and `listLists.less` styles to set fixed dimensions for cover images, ensuring consistent layout across different components. [[1]](diffhunk://#diff-f8c91bc33e93b164d4442976576b0679323989637ec608962259b856a78a1bc1L32-R33) [[2]](diffhunk://#diff-9330540670a576916c8aca593f67f793a5c8706bafe2db882f8d46a4d48c8d1fL31-R32)
* Modified the `search-result-item.less` to remove the `.bookcover` class and ensure consistent image sizing.
* Updated `index.less` to remove the `max-width` constraint on images within the content body.
* Updated the `book_cover.html` template to calculate and set the height of the cover image dynamically based on its aspect ratio.
* Adjusted the `lists/home.html` template to calculate and set the height of the cover image dynamically based on its aspect ratio.

### Testing

1. Navigate to pages where book covers are displayed.
2. Verified that the book covers load with the correct dimensions.
3. Ensured that the layout remains stable and does not shift when the images are loaded.
4. Tested the changes on various devices and screen sizes to confirm responsiveness.

### Screenshot

We have make videos demonstrating the changes and comparing with the real website of OpenLibrary;
https://drive.google.com/file/d/1RrzodyWAFDAS--mk5Y222Hjk95FYgMla/view?usp=sharing
https://drive.google.com/file/d/1BF7YWPcys6Ny2EuJ9ahkiIexsC1JjmCH/view?usp=sharing

### Stakeholders

@cdrini

2024-12-14 00:49 UTC, anna-ayn commented
Hi @RayBB and @cdrini,

We have completed the modifications to standardize the sizes of book covers and prevent layout shifting in various sections of the site.

We would greatly appreciate your review and feedback on these changes. Thank you!

2024-12-16 23:52 UTC, mekarpeles commented
Can you provide some screenshots so we can visually inspect the before/after? Thank you!

Also, it seems like the commit history may need a bit of a rebase / cleanup.

@RayBB do you mind taking a first look?

2024-12-17 01:50 UTC, anna-ayn commented
Hello @mekarpeles 
No problem! We're glad you found the videos.

Regarding the commit history, we just done a rebase and cleanup. Now, we're waiting for the approval of two workflows by a maintainer. 

Feel free to reach out if you have any other questions or need additional information!

2024-12-17 19:23 UTC, RayBB requested changes
Hey folks this is a great start!
I left a few small notes on the PR itself.

However, you also seem to have created a regression on the search results page.
Please fix that and the other comments and then I'll try to take a closer look.
Good luck!

http://localhost:8080/search?q=lewis&mode=everything
![CleanShot 2024-12-17 at 14 21 02@2x](https://github.com/user-attachments/assets/688576a0-6172-4c4a-9457-bdd9c31794f6)

2024-12-17 19:23 UTC, RayBB commented on static/css/layout/index.less
> +    // max-width: 100%;
If you want this to be removed please delete it completely instead of commenting it out.

2024-12-17 19:23 UTC, RayBB commented on static/css/components/search-result-item.less
> +  .git {
Is this an intentional change? Probably a typo

2024-12-17 19:23 UTC, RayBB commented on static/css/components/listLists.less
> +        // max-width: 100%;
Again, if you want this to be deleted please fully delete it.

2024-12-17 19:23 UTC, RayBB commented on openlibrary/components/LibraryExplorer/components/OLCarousel.vue
>  <style scoped>
Please try to keep the changeset small by avoiding whitespace changes like this one.

2024-12-18 00:45 UTC, anna-ayn commented
Hi @RayBB 

Thank you for your feedback! I've addressed the comments and made the necessary changes:

* Removed Commented-Out Code: Fully deleted the commented-out max-width property in [static/css/layout/index.less](https://github.com/internetarchive/openlibrary/pull/10145/files/b9956a4b2f658721a6b6377f8a6d16bd649fb0fc#diff-0fb6bd653f719f92dcbf9aadcf7fee714bd522dc039ec4ec802578caa6f58877) and in [static/css/components/listLists.less](https://github.com/internetarchive/openlibrary/pull/10145/files/b9956a4b2f658721a6b6377f8a6d16bd649fb0fc#diff-9330540670a576916c8aca593f67f793a5c8706bafe2db882f8d46a4d48c8d1f)

* Fixed Typo in .bookcover Class: Removed changes made to [static/css/components/search-result-item.less](https://github.com/internetarchive/openlibrary/pull/10145/files/b9956a4b2f658721a6b6377f8a6d16bd649fb0fc#diff-db0effbcf2ef74b59f5f2054ab12a2bed7d9aa6f2fd21566767ea719a23ded1a)

* Avoided Unnecessary Whitespace Changes: Removed unnecessary whitespace changes in [openlibrary/components/LibraryExplorer/components/OLCarousel.vue](https://github.com/internetarchive/openlibrary/pull/10145/files/b9956a4b2f658721a6b6377f8a6d16bd649fb0fc#diff-67252238cf1f4e1386c9d41f7416ed52fd6d72e5effb8d2273b539942a65f4c3). 

* Addressed Regression on Search Results Page: Fixed the regression issue on the search results page by modifying openlibrary/macros/SearchResultsWork.html.

2024-12-20 04:30 UTC, RayBB requested changes
I've taken one more brief look and found two issues:
1. The cover in the search results has the wrong aspect ratio and as such is distorted.
![CleanShot 2024-12-19 at 23 26 17@2x](https://github.com/user-attachments/assets/afcd8cfc-da62-4b41-83f3-1218a0155667)

2. The aspect ratio is also causing distortion in the "more by this author" section
![CleanShot 2024-12-19 at 23 27 02@2x](https://github.com/user-attachments/assets/735ede3b-a373-4054-bccd-9b5eca021c55)


Please fix the two above issues.

Also, please edit your original PR testing instructions to include a complete list of (localhost) URLs where we should see the changes.

As for the code itself, I didn't look closely as @cdrini is the lead and will likely have detailed feedback on that when he reviews it.

Overall, good work on this. It's certainly not an easy task to get this working in so many places.

2024-12-20 17:44 UTC, anna-ayn commented
Hi @RayBB,

I've resolved the distortion issue with the covers. It was related to the object-fit property setted as "cover", and I've made the necessary adjustments.

![Search Results](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZGwwbnMyOG1vdW02djAza3JhMWxjaHduMWtjNHZ3aDc1MXNlZmVzMiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ZNUZb7noGq0sy9GqRJ/giphy.gif)

![image](https://github.com/user-attachments/assets/c1213c6b-8f23-4968-9ba1-ebe236fc85c6)

![You might also like](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMnE1cm82cjBiZHpmajVxdWRreDZuaXUwZzVyZzJ6YmN4bW1udGtmMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Q9nQMHcr7xiyo7wZnd/giphy.gif)

2025-02-05 17:44 UTC, cdrini requested changes
Hi @anna-ayn , awesome work on this one! Unfortunately looking into it some more, we only really want to affect the book page, eg `book_cover.html`. Fetching the info for the cover width/height has a cost associated with it, so we don't want to be doing too frequently. On the book page, we only have the one main cover which causes the biggest layout shift, that's the one we want to address. The other pages, eg. search, carousels, won't be able to use the currently flow to get the width/height, because it would be too expensive to fetch that info for all those covers. There is a separate project for including this info in our solr search index which will make that possible, but for I'm afraid it's not.

Apologies for the run around here! We didn't realize the cost of this when creating the issue.

2025-02-05 17:44 UTC, cdrini commented on openlibrary/plugins/openlibrary/js/lists/ShowcaseItem.js
This cover is very rarely displayed, and fetching the cover size before rendering it is not worth the complexity and performance costs, I believe, so we can roll back the changes to this piece (and where `ShowcaseItem` is called).

2025-02-05 17:44 UTC, cdrini commented on openlibrary/templates/books/custom_carousel.html
This won't quite work, since it's hard-coding the aspect ratio to 180 / 360, but getting the image sizes for all the covers that will appear in a carousel is likely going to be expensive. I don't think that will be worth the trouble, so let's roll back this page here.

2025-02-05 17:44 UTC, cdrini commented on openlibrary/templates/books/edition-sort.html
Ditto with this one, the editions table displays quite a few edition covers, and would be expensive to fetch the sizing info for all of them, so leaving this as it was is best. There is a separate project to include width/height in our search index solr; once that is complete, then we can use the information there to do this kind of work!

2025-02-05 17:44 UTC, cdrini commented on openlibrary/macros/SearchResultsWork.html
Ditto here unfortunately, this will not be able to use/display the cover width/height until it is in solr.

2025-02-05 17:44 UTC, cdrini commented on openlibrary/templates/covers/book_cover.html
> +<div class="coverMagic cover-animation" style="min-height: ${calculated_height}px;">
It seems like we'll only need to specify the aspect ratio; e.g. `style="aspect-ratio: $cover_width / $cover_height;"` on the `<img>` element. @RayBB and I tested this, and it removed the layout shift! That should simplify this up quite a bit!

2025-02-05 17:44 UTC, cdrini commented on openlibrary/templates/lists/home.html
Ditto here unfortunately, this will have to be rolled back to avoid a performance hit.

2025-02-05 17:44 UTC, cdrini commented on openlibrary/book_providers.py
> +def get_dimensions_cover(url: str) -> tuple[int, int] | None:
Since we have access to the database that contains all the cover info, instead of making a network request, it would be faster to instead make a database request.

I think calling the `details` method should fix this:

https://github.com/internetarchive/openlibrary/blob/8b2a94044f01b9388b96ff094559c8e4637b6d4f/openlibrary/coverstore/db.py

2025-04-15 16:10 UTC, RayBB commented
@anna-ayn are you planning to continue working on this? If not, we can give someone else a chance to work on it.

2025-04-15 18:13 UTC, anna-ayn commented
> @anna-ayn are you planning to continue working on this? If not, we can give someone else a chance to work on it.

Hi @RayBB, I appreciate your follow-up! Unfortunately, I won't be continuing to work on this. Please feel free to reassign it to someone else who can take it forward. Thanks!

2025-05-14 23:34 UTC, closed without merging