fixed arrow alignment
internetarchive/openlibrary pull request #10169
Opened 2024-12-19 07:16 UTC by Craig-Rosario

Align/Fix the navigation arrows, positioning them on the sides of the covers for better usability.

### Technical

### Testing

1) Go to the add-cover section of a book (eg. https://openlibrary.org/works/OL69166W/Italian_journeys/add-cover)

### Screenshot

**Before:**
![Screenshot 2024-12-19 121132](https://github.com/user-attachments/assets/79d3c9c3-81ff-4049-8943-6931fb92cb37)

**After:**
![Screenshot 2024-12-19 121909](https://github.com/user-attachments/assets/73c1a061-457f-4f27-8847-707c271a2cbc)

### Stakeholders

@mekarpeles

2025-01-05 18:06 UTC, mekarpeles commented on static/css/lib/slick-theme.css
> -    right: -25px;
This may affect the buttons on other pages as well (e.g. the homepage) so we may have to do some testing

2025-01-05 18:36 UTC, Craig-Rosario commented on static/css/lib/slick-theme.css
> -    right: -25px;
Yeah, some testing may be required, because when the value is: 
right: -25px

some part of the arrow actually clips out of the box.

2025-01-07 01:21 UTC, cdrini requested changes
Ah, the issue here is that the CSS meant for the "Use this image" button are also applying to the left/right button. Because of this css rule: `.ol-cover-form .carousel button`. Changing the rule to `.ol-cover-form .carousel .cta-btn` should fix the issue :+1: That's a preferable approach, since it makes fewer changes, and is less likely to affect other parts of the page and cause bugs.

2025-01-08 19:41 UTC, Craig-Rosario commented
Yeah, made the necessary changes, works great now. Also adjusted the z-index to ensure it doesn’t interfere with the book image.
![Screenshot 2025-01-09 010138](https://github.com/user-attachments/assets/47d2ba4e-4003-4abb-8bbf-ddcd9eb135ac)

2025-01-09 03:49 UTC, cdrini approved these changes
Looks great! Thank  you @Craig-Rosario !

![image](https://github.com/user-attachments/assets/e3104d36-41bd-4966-8020-283e3709bc94)
![image](https://github.com/user-attachments/assets/d180dc3d-9e9c-479e-9d5c-3d76a83c11d2)

2025-01-09 03:49 UTC, merged

2025-01-09 05:12 UTC, Craig-Rosario commented
No worries, glad I could help😊