Fix search facet from mirepresenting the amount of ebook results
internetarchive/openlibrary pull request #10160
Opened 2024-12-17 21:31 UTC by sbwhitt

Closes #9575 

Hides printdisabled results for users not explicitly searching for them who do not have printdisabled settings stored in cookies. 

### Technical

### Testing

Ensure that ebook facet counts match the amount of actual ebook results, with or without 'pd' set to true in cookies. 

### Screenshot

### Stakeholders

@cdrini  @RayBB

2025-01-22 18:17 UTC, cdrini requested changes
This won't quite work at this layer, since it'll filter out printdisabled books all the time, even if the mode isn't specified. We want the way the _facets_ are computed to be modified, so that it correctly handles the `has_fulltext` facet.

We currently have a rewrite rule for the `has_fulltext` facet, which is what's causing the discrepancy. The facet is computed using the `has_fulltext` solr field, but once it's selected, it's translated by this code to use the `ebook_access` field:

https://github.com/internetarchive/openlibrary/blob/6a117fab6c963b74dc1ba907d838e74f76d34a4b/openlibrary/plugins/worksearch/schemes/works.py#L203-L210

This is the discrepancy. 

Solr does have options to specify more custom facets, I believe they're called facet queries (the docs here are useful ; sorry couldn't find the specific section! https://solr.apache.org/guide/solr/latest/query-guide/faceting.html ).

If we update the the Work search scheme's facet_fields to instead of having the plain `has_fulltext` field, instead have a `dict` with options to specify a facet query, and then update the code that actually builds the solr query to understand/serialize this dict, that might do the trick?

Work Search Scheme facet fields: https://github.com/internetarchive/openlibrary/blob/6a117fab6c963b74dc1ba907d838e74f76d34a4b/openlibrary/plugins/worksearch/schemes/works.py#L102-L113

Code that does the actual query: https://github.com/internetarchive/openlibrary/blob/9a4e45eabb329db65a80d04b1e2a009518d41915/openlibrary/plugins/worksearch/code.py#L191-L205

And then there might be some awkward stitching logic. Apologies this a bit more of a meatier change than expected! Let us know if you have any questions!

2025-01-25 13:32 UTC, sbwhitt commented
@cdrini Thanks for taking a look. The current change should only exclude printdisabled books when the mode is not specified and the user does not have the pd cookie, but it does remove those books from the results entirely. Is the issue that we want to avoid hiding printdisabled books to users without the pd cookie?

2025-02-13 21:00 UTC, hornc commented
@sbwhitt , @cdrini  #10451 was just merged which removed the `printdisabled` search mode (because it relied on a no-longer used subject facet to filter, and hasn't worked for some time)  That might simplify the logic here?

2025-02-15 17:46 UTC, sbwhitt commented
@hornc Thank you for letting me know!

2025-02-21 01:37 UTC, cdrini commented
@sbwhitt correct printdisabled books should appear in the main search results; we only want to change the number next to the "ebooks? Yes" facet :+1:

2025-03-10 21:47 UTC, cdrini commented
I'm going to close this one @sbwhitt , since it hasn't had updates in a bit. Please feel free to re-open if you find you have the time to tackle!

2025-03-10 21:47 UTC, closed without merging