Use mock data for homepage charts to reduce startup loading time
internetarchive/openlibrary pull request #10179
Opened 2024-12-22 02:33 UTC by schu96

Closes #10118 

Fix

### Technical

Checks if the current running instance is a dev environment using ```web.ctx.features``` and utilizes mock data to display the charts on the front page. Minor CSS styling issue fix for chart labels. 

### Testing

1. Run ```docker compose up -d```
2. Open your browser's developer tools and select the Network tab before navigating to localhost:8080
3. Check how long it takes for the homepage to completely load
    -   My local instance loading time dropped from roughly ~22 seconds to ~2 seconds, timings for other machines and browsers will most likely vary

### Screenshot

Before
--- 
![image](https://github.com/user-attachments/assets/9e120423-31d4-4350-9f5b-79411af2a5c5)
After
---
![image](https://github.com/user-attachments/assets/1162624d-6a5a-4a31-8195-bfc0f5032b3a)

### Stakeholders

@jimchamp @RayBB

2024-12-22 02:40 UTC, RayBB commented
We're you able to time how much faster the home page is ready?

2024-12-22 02:44 UTC, schu96 commented
> We're you able to time how much faster the home page is ready?

Not sure if this was the best method to use but I used the Firefox Networking tab to get the request duration for the homepage which I included in the screenshots (23 seconds to 2 seconds)

2024-12-22 03:22 UTC, RayBB requested changes
This is great work! What a huge improvement for development environments :)

@jimchamp is the lead so he'll provide the final feedback.

However, I'll give one piece of feedback.

I think the convention of the codebase is to set something up in dev_instance.py for the mock data. I'm not exactly sure how it should work in this case with overriding data/function but it would likely simplify the PR a decent amount. It could be as simple as adding `admin._get_count_docs = admin.mock_get_stats`.

Even if you choose not to go this approach the get_stats function could probably be simplified by having one return statement and the if/else just about setting the docs variable.

Anyway, good work and I hope Jim can review soon :)

2025-01-01 00:28 UTC, jimchamp requested changes
Thanks @schu96, this seems to greatly improve homepage load times.

I've requested some changes to improve clarity, DRY the code, and remove unrelated style changes.  I'm happy to merge this once those have been completed.

2025-01-01 00:28 UTC, jimchamp commented on openlibrary/core/admin.py
> +def get_stats(ndays=30, dev_prod=False):
```suggestion
def get_stats(ndays=30, use_mock_data=False):
```
`dev_prod` doesn't really convey what this boolean is used for.

2025-01-01 00:28 UTC, jimchamp commented on openlibrary/core/admin.py
> +        }
```suggestion
    docs = mock_get_stats() if use_mock_data else _get_count_docs(ndays)
    return {
        'human_edits': Stats(docs, "human_edits", "human_edits"),
        'bot_edits': Stats(docs, "bot_edits", "bot_edits"),
        'lists': Stats(docs, "lists", "total_lists"),
        'visitors': Stats(docs, "visitors", "visitors"),
        'loans': Stats(docs, "loans", "loans"),
        'members': Stats(docs, "members", "total_members"),
        'works': Stats(docs, "works", "total_works"),
        'editions': Stats(docs, "editions", "total_editions"),
        'ebooks': Stats(docs, "ebooks", "total_ebooks"),
        'covers': Stats(docs, "covers", "total_covers"),
        'authors': Stats(docs, "authors", "total_authors"),
        'subjects': Stats(docs, "subjects", "total_subjects"),
    }
```
DRY this function up.

2025-01-01 00:28 UTC, jimchamp commented on openlibrary/plugins/openlibrary/home.py
> +            stats = None
```suggestion
    try:
        stats = admin.get_stats(use_mock_data=("dev" in web.ctx.features))
    except Exception:
        logger.error("Error in getting stats", exc_info=True)
        stats = None
```

2025-01-01 00:28 UTC, jimchamp commented on openlibrary/plugins/openlibrary/js/graphs/plot.js
> +            'z-index': 100
```suggestion
            boxShadow: '1px 1px 1px #000'
```
Roll back change unrelated to #10118.

2025-01-01 03:20 UTC, schu96 commented on openlibrary/core/admin.py
> +        }
Should both the VisitorStats and LoanStats classes be deleted from ```openlibrary/core/admin.py``` or is this a temporary change?

2025-01-01 14:10 UTC, jimchamp commented on openlibrary/core/admin.py
> +        }
You're right, thanks for pointing this out.  How about this:

1. Update `mock_get_stats` to return the completed stats `dict`
2. Update `get_stats` to return `mock_get_stats()` if this is a dev instance.  Otherwise, return the actual stats (just as we've been doing).

2025-01-02 18:37 UTC, jimchamp approved these changes
LGTM.  Graphs are rendering as expected in local and testing environments.
Thanks, @schu96!

2025-01-02 18:38 UTC, merged