Convert nested if statements to elif clauses for better readability.
internetarchive/openlibrary pull request #10227
Opened 2024-12-29 22:34 UTC by ananyakaligal

Closes #10196

PLR5501 - Convert nested if statements to elif clauses for better readability.

@RayBB I converted nested if statements to elif clauses for better readability across 14 files.
In some cases, I couldn't apply the change due to specific conditions, so I simplified or improved readability instead.
I’ve reviewed all the changes carefully, but if I’ve missed any files, please let me know. Let me know if further modifications are needed.

2024-12-29 22:38 UTC, RayBB commented
Please tag me once all tests and precommit checks are passing.

2024-12-29 22:51 UTC, ananyakaligal commented
@RayBB All the checks have passed. Let me know if any more modifications are needed.

2024-12-29 22:57 UTC, RayBB requested changes
Please remove any changes that aren't strictly needed to enable the rule. For the most part you should only have to enable the rule and let ruff fix thing. There may be a few other small changes needed. Don't add other changes like spacing unless important.

2024-12-29 23:03 UTC, ananyakaligal commented
@RayBB Thank you for the feedback, I will work on it and make a PR by tomorrow.
In some cases, I may not be able to completely remove the nested conditions, but I can work on reducing their complexity or nesting level. Would that be acceptable?

2024-12-30 00:22 UTC, RayBB commented
We should let ruff fix them automatically. If any are too complicated for ruff to fix let's review together on a case by case basis.

2024-12-30 04:53 UTC, ananyakaligal commented
@RayBB alright, I'll revert the all the unnecessary changes made and review each case properly this time. Thankyou

2024-12-31 14:51 UTC, ananyakaligal commented
Hello @RayBB , Due to unforeseen circumstances, I couldn’t work on this as planned. I’ll ensure it’s completed in the next 2-3 days.

2025-01-03 08:40 UTC, RayBB commented
@ananyakaligal are you still working on this?

2025-01-03 09:49 UTC, ananyakaligal commented
@RayBB I just made a PR on this #10260

2025-01-03 11:43 UTC, closed without merging