Fix Docker build - Create home directories for accounts
internetarchive/openlibrary pull request #2736
Opened 2019-12-14 22:25 UTC by tfmorris

2019-12-16 17:05 UTC, cdrini requested changes
Can you expand on what error you observed? I'm not sure why these users need home directories.

2019-12-16 17:05 UTC, cdrini commented on docker/README.md
> +docker-compose build solr # 1 minute
These timings look really short; docker caches things pretty aggressively, so unless you uninstalled everything and started from scratch, my guess would be your computer had cached some of the images (so these timing aren't taking into account e.g. download time).

In general, I think these timings should be quite liberal; I don't want someone to expect something to take 4 minutes and have it take 30+; that sucks :P However expecting something to take 30+ minutes and having it take 4 is much better. I'd recommend _adding_ your timings, like so:

```
docker build -t olbase:latest -f docker/Dockerfile.olbase . # 30+ min (Win10Home/Dec 2018); 5 min (MacBook Pro/Dec 2019)
```

But _only_ if you've done a _full_ reset; these timings are mainly for first-comers.

2019-12-16 17:08 UTC, cdrini commented on docker/README.md
> +docker-compose build solr # 1 minute
(Also, although a MacBook Pro is a very common device among established developers, my guess would be it's well outside of the price range of students/contributors/etc).

2020-01-17 04:37 UTC, cdrini commented
Hey @tfmorris , any updates on this?

2020-03-23 22:57 UTC, cdrini commented
This pr has gone stale for ~2mo; closing. Feel free to rebase + update :+1:

2020-03-23 22:57 UTC, closed without merging

2020-03-24 05:29 UTC, tfmorris commented
I provided updates on Slack to confirm that the problem actually was real, but I really don't care. I'll chock it up to wasted volunteer work. Someone else will rediscover and refix it later.