WIP - Python3 test fixes
internetarchive/openlibrary pull request #2897
Opened 2020-01-21 03:10 UTC by tfmorris

This uses the Python 3 import cleanup as a base and starts to fix some of the test failures.

Closes #

### Technical

### Testing

### Evidence

### Stakeholders

2020-01-21 03:21 UTC, hornc requested changes
This is great in that it maps out what is needed to get the Python3 tests passing, but simple changes to ensure divisions result in `int`s are going to get held up by changes to requirements.txt.  Moving from web.py 0.39 to 0.40 is going to take quite a bit of planning and discussion to get across the line, this isn't really mergable at its current scale.

2020-01-21 04:05 UTC, tfmorris commented
@hornc As a reminder, PRs labelled WIP or Draft are **not** ready for review. I used both on this one to make it extra clear. 

This uses an integration branch with all the `import` fix PRs included. I expect the sequence to be:
* clean up, review, and merge #2888 
* review and merge the other `import` related PRs
* create PRs for the test fixes which are organized by type of fix (e.g. all `iteritems()` fixes) or functional area e.g. `openlibrary.core`

Perhaps you could update the web.py 0.40 PR with what you see as the issue there. It seems straightforward to me.

2020-01-22 18:54 UTC, cclauss commented on openlibrary/catalog/author/merge.py
> +        author_keys = set(k for k in list(a.keys()) + list(best.keys()) if k not in ('key', 'last_modified', 'type', 'id', 'revision'))
`.keys()` are not required.  The following are all equivalent.
```
for key in a:  # unless a could change during iteration
for key in list(a):
for key in list(a.keys()):
```
In this case, `list(a) + list(best)` would work just fine.

2020-01-22 18:54 UTC, cclauss commented on openlibrary/catalog/author/rename.py
> +    for k in old.keys():
`for k in old:`

2020-02-03 01:34 UTC, cclauss commented on openlibrary/coverstore/code.py
> +        tarindex = coverid // 10000
tarindex, index = divmod (coverid, 10000)

2020-04-30 22:25 UTC, tfmorris commented
I think @cclauss has cherry picked all the useful commits from this branch into individual PRs and successfully shepherded them through the long and painful review process. Thank you!

2020-04-30 22:25 UTC, closed without merging