Refactors IA-Powered Carousels (Supplants #2161: ia.IAEditionSearch)
internetarchive/openlibrary pull request #3180
Opened 2020-03-14 06:38 UTC by mekarpeles

Closes #2161 (incomplete stale refactor of IAEditionSearch)

This PR `refactor`s how Open Library queries Archive.org Elastic Search for books matching certain queries (which are then converted into a fetch of the desired Open Library editions w/ correct Archive.org availability information) 

### Technical

### Testing

- [x] rendering homepage carousels should work (all the carousels should be there, e.g. thrillers -- otherwise, this reflects an error in the Elastic Search queries)
- [x] clicking on the title/link of IA-powered homepage carousels on dev + production should produce an Archive.org search results page with comparable # of results 
- [x] tests for IAEditionSearch should pass
- [x] subject pages should render with correct availability information
- [x] homepage carousel infinite loading should work

### Stakeholders

@cdrini @cclauss

2020-03-14 06:48 UTC, cclauss commented
It would be good if this PR could ensure that [`openlibrary/plugins/upstream/tests/test_related_carousels.py`](https://travis-ci.org/github/internetarchive/openlibrary/jobs/662306587#L893) passes on both Py2 and Py3 as it does in #3177.

2020-03-14 06:58 UTC, mekarpeles commented on openlibrary/tests/core/test_processors.py
> +    def _get_backreferences(self, *args, **kwargs):
this technically fixes a different booklending_utils bug which makes tests fail on dev (because the booklending_utils lib is actually present)

2020-03-14 07:02 UTC, mekarpeles commented
> https://github.com/internetarchive/openlibrary/pull/3180#issuecomment-599019771

@cclauss I can barely tell what's going on in travis for python 3.8 linting on this branch

2020-03-14 07:52 UTC, cclauss commented
On your local machine run `make lint-diff`

2020-03-14 07:56 UTC, cclauss commented
At the very bottom of the Travis output:
openlibrary/core/ia.py:183:9: F401 'openlibrary.core.lending' imported but unused
openlibrary/plugins/worksearch/tests/test_worksearch.py:87:45: W605 invalid escape sequence '\:'
openlibrary/plugins/worksearch/tests/test_worksearch.py:93:46: W605 invalid escape sequence '\:'
openlibrary/tests/core/test_ia.py:2:1: F401 'infogami.config' imported but unused

2020-03-14 12:09 UTC, cclauss commented on openlibrary/core/ia.py
> +            request = urllib2.Request(url)
```suggestion
            request = six.moves.urllib.request.Request(url)
```
And lose the import line above.

2020-03-14 12:13 UTC, cclauss commented on openlibrary/core/ia.py
> +            response = urllib2.urlopen(
```suggestion
            response =  six.moves.urllib.request.urlopen(
```

2020-03-17 07:37 UTC, cclauss commented
Requires the same two imports as https://github.com/internetarchive/openlibrary/pull/3189#discussion_r393464813

2020-03-23 07:04 UTC, cclauss commented
Please rebase.  https://travis-ci.org/github/internetarchive/openlibrary/jobs/665700598#L584 was fixed in #3241

2020-04-11 04:36 UTC, cclauss commented on openlibrary/core/ia.py
> +            # TODO switch to requests
Why postpone the shift to requests?

2020-04-11 04:38 UTC, cclauss commented on openlibrary/core/ia.py
> +        return dict((item['identifier'], item) for item in items)
Why pay the function call overhead?
```suggestion
        return {item['identifier']: item for item in items}
```

2020-04-11 04:40 UTC, cclauss approved these changes

2020-04-11 11:25 UTC, cclauss commented on openlibrary/core/models.py
> +                return ol_covers[0]
The current implementation only processes the loop until the first element is created.  The proposed change creates the entire list and then only uses the first element.  Is this extra processing desired and useful?

2020-04-11 19:27 UTC, tfmorris requested changes
It's pretty hard to review this without a high-level description of what the intended refactoring is meant to do. It looks like there were changes to the caching, but I'm not sure I followed them all.

Given that, my review focuses mostly on micro level syntactical stuff as opposed to whether the refactoring was done correctly at a macro level.

2020-04-11 19:27 UTC, tfmorris commented on openlibrary/core/ia.py
> +    PRESET_QUERIES = {
A core library module seems like a strange place to store presets. I'd have thought they'd be in some calling code.

2020-04-11 19:27 UTC, tfmorris commented on openlibrary/core/ia.py
> +        return {
This seems like it belongs in a Solr helper library.

2020-04-11 19:27 UTC, tfmorris commented on openlibrary/core/lending.py
> +    query = ia.IAEditionSearch.PRESET_QUERIES.get(query, query)
The previous module seems more logical to me.

2026-05-11 14:55 UTC, closed without merging