Added padding in category-count
internetarchive/openlibrary pull request #3925
Opened 2020-10-16 05:56 UTC by Yashs911

Closes #3923 

### Screenshot

![fix](https://user-images.githubusercontent.com/64412143/96218438-5b8cba00-0fa2-11eb-9e78-d488da7a87b7.JPG)

### Stakeholders

@cdrini @mekarpeles

2020-10-17 01:36 UTC, jamesachamp requested changes
It worries me that we are removing the explicit padding of 0 for the top, right, and left.

2020-10-17 01:36 UTC, jamesachamp commented on static/css/components/category-item.less
> +    padding-bottom: 1px;
```Suggestion
padding: 0 0 1px;
```

2020-10-17 06:36 UTC, Yashs911 commented on static/css/components/category-item.less
> +    padding-bottom: 1px;
@jamesachamp  have made the changes

2020-10-17 11:46 UTC, jamesachamp approved these changes
Lgtm, thanks @Yashs911 !

2020-10-19 18:37 UTC, cdrini commented
Thanks @jamesachamp !

2020-10-19 18:37 UTC, merged