fixes failing search case where %3A, i.e. : fails
internetarchive/openlibrary pull request #3943
Opened 2020-10-19 22:15 UTC by mekarpeles

Addresses a case @JeffKaplan reported from project Koha about certain MARC records which contain ":" colons causing issues.

2020-10-20 06:01 UTC, cclauss commented on openlibrary/plugins/worksearch/code.py
> +def depunctuate(s):
[punctuation is `!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~`](https://docs.python.org/3.9/library/string.html#string.punctuation) in Python so perhaps a more self-documenting function name...
```suggestion
def colonoscopy(s):
```

2020-10-20 06:10 UTC, cclauss requested changes

2020-10-20 06:10 UTC, cclauss commented on openlibrary/plugins/worksearch/code.py
> +    just my removing `:`'s and stripping trailing whitespace.
```suggestion
    just by removing `:`'s and stripping leading and trailing whitespace.
```

2020-10-20 06:10 UTC, cclauss commented on openlibrary/plugins/worksearch/code.py
> +    """
```suggestion
    >>> depunctuate('  ! " #$ :A:B:C: %& ` ?  ')
    '! " #$ ABC %& ` ?'
    """
```

2020-10-20 06:15 UTC, cclauss commented on openlibrary/plugins/worksearch/code.py
> +        q_list += ['%s:(%s)' % (k, depunctuate(param[k])) for k in check_params if k in param]
```suggestion
        q_list += [
            '%s:(%s)' % (k, depunctuate(param[k])) for k in check_params if k in param
        ]
```
Use psf/black for format long line to placate Travis CI.

2020-11-04 01:20 UTC, cdrini commented
Closing in favour of #4009

2020-11-04 01:20 UTC, closed without merging