Fix YAML Load warnings
internetarchive/openlibrary pull request #3963
Opened 2020-10-26 18:53 UTC by Purhan

### [WIP/Incomplete]

Closes #3958

Removes YAML load warnings raised by pytest.

### Technical

### Testing

### Screenshot

### Stakeholders

@cclauss

2020-10-26 18:56 UTC, Purhan commented
@cclauss (and others) I have been able to fix part of the issue but I'm unable to identify a proper fix for

```
openlibrary/tests/solr/test_update_work.py::Test_update_items::test_update_author
  /openlibrary/infogami/__init__.py:168: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
    runtime_config = yaml.load(open(config_file))
```

I am unable to locate the correct file. Any clue on how I should proceed now?

2020-10-26 20:20 UTC, cclauss requested changes

2020-10-26 20:20 UTC, cclauss commented on openlibrary/config.py
> +    runtime_config = yaml.safe_load(open(config_file))
```suggestion
    with open(config_file) as in_file:
        runtime_config = yaml.safe_load(in_file)
```
Let's automate the file close() even if an Exception is raised by using the `with open() as` _context manager_.

2020-10-26 20:20 UTC, cclauss commented on openlibrary/config.py
> +        loaded_file.close()
```suggestion
        with open(config_file) as in_file:
            config.infobase = yaml.safe_load(in_file)
```

2020-10-26 20:20 UTC, cclauss commented on openlibrary/plugins/admin/tests/conftest.py
>      return d
```suggestion
    with open(os.path.join(root, "sample_services.yml")) as in_file:
        return yaml.safe_load(in_file)
```

2020-10-27 16:16 UTC, cclauss approved these changes
LGTM

2020-10-28 15:49 UTC, merged

2020-11-16 19:24 UTC, cclauss commented
Could you please create one more of these for:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/coverstore/server.py

2020-11-17 04:39 UTC, Purhan commented
@cclauss sure, I will create a PR soon