fix py3 bytes/str issue when viewing a MARC record
internetarchive/openlibrary pull request #4034
Opened 2020-11-06 05:38 UTC by hornc

Fixes the following errors:
```
<class 'TypeError'> at /show-records/marc_loc_2016/BooksAll.2016.part41.utf8:32007375:748
argument should be integer or bytes-like object, not 'str'
```
URL: 

https://openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part41.utf8:32007375:748
https://openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part41.utf8:32007375:748?debug=true

Closes #

### Technical

### Testing

### Screenshot

### Stakeholders

2020-11-06 13:28 UTC, cclauss approved these changes
LGTM.  Changes made to deprecated functions.

2020-11-06 17:17 UTC, cdrini requested changes
Trusting you know what you're doing by removing the code/error checks that you did; no clue why they're necessary :P 

Tested:
- [x] https://dev.openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part41.utf8:32007375:748
- [ ] This is still erroring: http://staging.openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part41.utf8:32007375:748?debug=true

2020-11-07 05:56 UTC, cclauss commented
Please do integer division on line 175 (like #4037)
```python
iter_dir = (directory[i*12:(i+1)*12] for i in range(len(directory) / 12))
# —>
iter_dir = (directory[i*12:(i+1)*12] for i in range(len(directory) // 12))
```

2020-11-07 22:03 UTC, mekarpeles approved these changes

2020-11-07 22:07 UTC, mekarpeles commented
The changes look fine but as noted, the error still exists

```
<class 'TypeError'> at /show-records/marc_loc_2016/BooksAll.2016.part41.utf8:32007375:748
'float' object cannot be interpreted as an integer

Python | /openlibrary/openlibrary/catalog/marc/fast_parse.py in read_directory, line 175
GET http://staging.openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part41.utf8:32007375:748
```

2020-11-08 06:48 UTC, hornc commented
thanks @cdrini for finding that failing case, good catch! This should fix it.

2020-11-10 17:10 UTC, cdrini commented on openlibrary/catalog/marc/fast_parse.py
> +        length += data[last:].find('b\x1e')
:P
```suggestion
        length += data[last:].find(b'\x1e')
```

2020-11-10 17:12 UTC, cdrini commented
Ahh, still getting another error here :P 

http://staging.openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part41.utf8:32007375:748?debug=true

2020-11-10 20:50 UTC, hornc commented
@cdrini That should be fixed now. I'm unable to test locally because my docker env won't build with the recent python 3.9 changes.
I was getting an error about not being able to find python 3.9 when building the covers image, which seemed strange since it was there for the `olbase` image.

```
Step 9/13 : RUN python3.9 -m pip install -r requirements_test.txt
 ---> Running in 0a034c8d7ae4
/bin/sh: 1: python3.9: not found
ERROR: Service 'covers' failed to build : The command '/bin/sh -c python3.9 -m pip install -r requirements_test.txt' returned a non-zero code: 127
```

2020-11-10 21:10 UTC, cdrini commented
Oh! :( You might want to try doing a "full" re-build: `docker-compose build --pull`; that will also pull the latest `openlibrary/olbase` image from docker hub.

2020-11-10 21:10 UTC, cdrini commented
I'll toss your changes on to staging now as well to see if this fixes the issue!

2020-11-10 21:12 UTC, cdrini commented
Turtles all the way down 😅 http://staging.openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part41.utf8:32007375:748?debug=true

2020-11-10 21:54 UTC, cdrini commented
Refreshed on staging; there's more 😅 http://staging.openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part41.utf8:32007375:748?debug=true

Any luck with the docker commands?

2020-11-11 00:32 UTC, cclauss commented
Use Py 3.8.6, not 3.9.0.

2020-11-11 01:53 UTC, hornc commented
@cdrini `docker-compose build --pull` did the trick, thank you.

I can run everything locally and view that last link:
![image](https://user-images.githubusercontent.com/905545/98755378-471ad080-242d-11eb-9a44-628931d0f9f5.png)

When I tried it on staging earlier today I _did_ see an error:
```
Python | /openlibrary/openlibrary/plugins/upstream/code.py in static_url, line 89
-- | --
GET http://staging.openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part41.utf8:32007375:748
```

But I'm not getting in now, not on staging nor locally. I'm runnin geverything with
`PYENV_VERSION=3.8.6 docker-compose up`

2020-11-11 02:02 UTC, hornc commented
Last commit fixes the `b'001'` display of the MARC fields:

![image](https://user-images.githubusercontent.com/905545/98756146-dd032b00-242e-11eb-82af-d66b62ea4966.png)

2020-11-11 02:40 UTC, cdrini commented
Woohoo! Working on staging: staging.openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part41.utf8:32007375:748 , too :)

2020-11-11 06:58 UTC, hornc commented
@cdrini ok, tests finally match desired behaviour, they went through a stage of passing with the incorrect `b'100'` output... <sigh>
I

2020-11-11 14:22 UTC, cdrini approved these changes
Awesome! Lgtm

2020-11-11 14:22 UTC, merged