Improve error reporting in plugins/upstream/covers.py
internetarchive/openlibrary pull request #4165
Opened 2020-11-25 19:33 UTC by cclauss

Closes #

Sentry shows us many have many JSONDecodeErrors which are often caused because we do not detect errors as they happen but instead wait until the json decoder raises. https://sentry.archive.org/sentry/ol-web/?query=JSONDecodeError

Here we will fast-fail by catching and logging `requests` errors while we still have enough context to debug those errors.

```
2020-11-25 19:20:58 [216] [openlibrary.logger] [INFO] solr request: http://ol-solr1:8983/solr/select?wt=json&q=key%3A%22%2Fworks%2FOL4226152W%22&start=0&fl=cover_edition_key%2Ccover_id%2Cedition_key%2Cfirst_publish_year%2Chas_fulltext%2Clending_edition_s%2Cchecked_out%2Cpublic_scan_b%2Cia
/openlibrary/openlibrary/plugins/upstream/utils.py:744: FutureWarning: This search is broken in 1.3 and earlier, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/item'
  return [parse_item(item) for item in tree.findall("//item")]
Traceback (most recent call last):
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 280, in process
    return self.handle()
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 271, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 517, in _delegate
    return handle_class(cls)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/web/application.py", line 495, in handle_class
    return tocall(*args)
  File "/openlibrary/infogami/utils/app.py", line 187, in <lambda>
    HEAD = GET = POST = PUT = DELETE = lambda self: delegate()
  File "/openlibrary/infogami/utils/app.py", line 206, in delegate
    return getattr(cls(), method)(*args)
  File "/openlibrary/openlibrary/plugins/upstream/covers.py", line 37, in POST
    data = self.upload(key, i)
  File "/openlibrary/openlibrary/plugins/upstream/covers.py", line 81, in upload
    return web.storage(resp.json())
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/openlibrary/.pyenv/versions/3.8.6/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
### Technical

### Testing

### Screenshot

### Stakeholders

2020-11-25 21:21 UTC, cdrini requested changes

2020-11-25 21:21 UTC, cdrini commented on openlibrary/plugins/upstream/covers.py
> +            response.raise_for_status()
Might want to drop this line in case /upload2 returns a useful response with a not ok status code.

2020-11-25 21:21 UTC, cdrini commented on openlibrary/plugins/upstream/covers.py
>              if six.PY3:
As discussed, let's do this on both py2/py3 because erroring on py2-web -> py3-covers

2020-11-25 21:21 UTC, cdrini commented on openlibrary/plugins/upstream/covers.py
> +logger = getLogger("openlibrary." + __file__)
e.g. from other file: `logger = logging.getLogger("openlibrary.account.model")`

2020-11-25 21:22 UTC, cdrini commented on openlibrary/plugins/upstream/covers.py
> +            logger.exception(str(e))
```suggestion
            logger.exception("Failed to upload image")
```

2020-11-25 21:59 UTC, cclauss commented
I think all those suggestions are in place so please re-review.

2020-11-25 22:36 UTC, mekarpeles approved these changes

2020-11-26 03:07 UTC, cdrini approved these changes
Tested uploading a cover on staging with py2-web to py2-covers and it worked; we also tested this fix on dev0 with a py2-web -> py3-covers and it worked :+1:

2020-11-26 03:07 UTC, merged