Change Cover Guidelines to Image Guidelines
internetarchive/openlibrary pull request #4211
Opened 2020-12-03 17:24 UTC by Sabreen-Parveen

Closes #2785

### Technical

### Testing

### Screenshot
![image](https://user-images.githubusercontent.com/53360510/101064262-cbd6b580-35b9-11eb-92d4-6e4f344575de.png)
![cover](https://user-images.githubusercontent.com/53360510/101064349-e872ed80-35b9-11eb-89c8-b5240fc69539.png)

### Stakeholders
@mekarpeles @seabelis

2020-12-04 04:23 UTC, cclauss commented on openlibrary/templates/covers/add.html
>      $ intro = _("There are three ways to get a cover image on Open Library")
Question for reviewers...  Should line 15 say `three ways` or `two ways` like the other instances?

2020-12-04 10:48 UTC, cclauss requested changes
We can simplify...

2020-12-04 10:48 UTC, cclauss commented on openlibrary/templates/covers/add.html
> +    $ guideline = _("Cover Guidelines")
```suggestion
```
The variables are set the same way in all cases except `$if doc.type.key == "/type/author":`.  This means that we can have one simple if statement — if the doc is an author then we can set the variables one way else we can set the variables another way.

2020-12-05 08:06 UTC, Sabreen-Parveen commented
@cclauss I have made the required changes

2020-12-06 18:16 UTC, cclauss approved these changes

2020-12-07 09:49 UTC, merged

2020-12-07 09:50 UTC, cclauss commented
Thanks much!