PR to unrevert "integrating updated bulk services/availability API""
internetarchive/openlibrary pull request #4214
Opened 2020-12-03 23:39 UTC by mekarpeles

Reverts internetarchive/openlibrary#4213

2020-12-04 19:28 UTC, cclauss requested changes
Wrap long lines.

2020-12-04 19:28 UTC, cclauss commented on openlibrary/core/lending.py
> +    lendable = '(lending___available_to_browse:true OR lending___available_to_borrow:true)'
```suggestion
    lendable = (
        '(lending___available_to_browse:true OR lending___available_to_borrow:true)'
    )
```

2020-12-04 19:28 UTC, cclauss commented on openlibrary/plugins/openlibrary/home.py
> +    'preset:authorsalliance_mitpress': '(openlibrary_subject:(authorsalliance) OR collection:(mitpress) OR publisher:(MIT Press) OR openlibrary_subject:(mitpress))'
```suggestion
    'preset:authorsalliance_mitpress': (
        '(openlibrary_subject:(authorsalliance) OR collection:(mitpress) OR '
        'publisher:(MIT Press) OR openlibrary_subject:(mitpress))'
    )
```

2020-12-04 22:39 UTC, cclauss approved these changes
RSLGTM

2020-12-05 02:43 UTC, cdrini approved these changes
Lgtm!

- ✅ Tested: http://staging.openlibrary.org/subjects/literature
    - ✅ Second page loads
    - ❌ Second page availability correct; Looks like the JS might have its own logic for checking this, since it has its own logic for rendering stuff here :( Not a blocker on this PR though.
- http://staging.openlibrary.org/books/OL18336664M/Harry_Potter_and_the_Prisoner_of_Azkaban
    - ✅ Shows available in sidebar
    - ✅ Shows available in first row of table
    - ✅ After checked out, shows "Read" in sidebar
    - ✅ After checked out, incognito shows "Join Waitlist"
- http://staging.openlibrary.org/authors/OL6951711A/Tom_Clancy
- http://staging.openlibrary.org/works/OL449016W/The_hunt_for_Red_October?edition=huntforredoctobe1990clan Not in Library

2020-12-05 02:44 UTC, merged