Fixed focus outlines hidden
internetarchive/openlibrary pull request #4255
Opened 2020-12-12 11:12 UTC by Yashs911

Closes #4012 
2px padding was added so that when one tab through the site the outlines are properly visible **but due to this "1 hour borrow" doesn't fit.** (check 3rd image)
### Screenshot

![1](https://user-images.githubusercontent.com/64412143/101982205-3bbefd00-3c98-11eb-89a6-9a5917dd6624.JPG)
![2](https://user-images.githubusercontent.com/64412143/101982207-3e215700-3c98-11eb-8020-e7b9d4ca4c1d.JPG)
![3](https://user-images.githubusercontent.com/64412143/101982209-4083b100-3c98-11eb-8b68-624495c3f379.JPG)
### Stakeholders

@jamesachamp

2020-12-20 01:57 UTC, jamesachamp commented
Thanks @Yashs911!  I can confirm that the outlines are visible once the padding has been added.  The button overflow is not ideal, and is a known issue (#3916) that may be temporarily solved by implementing #4269.

2021-01-09 17:50 UTC, jdlrobson requested changes
This impacts the book covers leading to the images being scaled incorrectly. The change should probably be restricted to `.category-item`

<img width="91" alt="Screen Shot 2021-01-09 at 9 49 47 AM" src="https://user-images.githubusercontent.com/148752/104104967-0b9b5780-5260-11eb-9530-1844fe7cea43.png">
y.

<img width="83" alt="Screen Shot 2021-01-09 at 9 49 42 AM" src="https://user-images.githubusercontent.com/148752/104104965-0b02c100-5260-11eb-8d02-ff126b2b3f81.png">

2021-01-09 18:05 UTC, Yashs911 commented
@jdlrobson I have made the required changes

2021-01-09 18:11 UTC, jdlrobson approved these changes

2021-01-09 18:11 UTC, merged