Draft: Create importbot docker service
internetarchive/openlibrary pull request #4324
Opened 2020-12-22 18:05 UTC by cclauss

Closes #

### Technical

### Testing

### Screenshot

### Stakeholders

2021-01-11 17:11 UTC, cclauss commented
Mode to PROD

2021-01-21 16:54 UTC, cdrini requested changes

2021-01-21 16:54 UTC, cdrini commented on docker-compose.production.yml
> +      - .:/openlibrary
Will need olsystem mounted, and will need to use its config

2021-01-21 16:54 UTC, cdrini commented on docker/ol-importbot-start.sh
> +scripts/manage-imports.py "$OL_CONFIG" $IMPORTBOT_OPTS 7100
Mimic this: https://github.com/internetarchive/olsystem/blob/master/etc/supervisor/conf.d/import-bot.conf ; looks like we also need `import-all`; there is no port (so can drop it from here and the docker compose file).

2021-01-21 16:56 UTC, cdrini commented on docker-compose.production.yml
> +      - OL_CONFIG=conf/openlibrary.yml
```suggestion
      - OL_CONFIG=/olsystem/etc/openlibrary.yml
      - OPENLIBRARY_RCFILE=/olsystem/etc/olrc-importbot
```

2021-01-21 16:56 UTC, cdrini commented on docker-compose.production.yml
> +      - 7100
```suggestion
```

2021-01-21 16:57 UTC, cdrini commented on docker-compose.production.yml
> +      - db
Not entirely sure if it does; can drop for now (helps avoid errors, otherwise we'll always need `--no-deps`)
```suggestion
```

2021-01-21 16:57 UTC, cdrini commented on docker-compose.production.yml
> +      - .:/openlibrary
```suggestion
      - .:/openlibrary
      - ../olsystem:/olsystem
```

2021-01-21 17:01 UTC, cdrini commented on docker/ol-importbot-start.sh
> +scripts/manage-imports.py --config "$OL_CONFIG" $IMPORTBOT_OPTS import-all
Let's drop this env variable; currently unused.

```suggestion
scripts/manage-imports.py --config "$OL_CONFIG" import-all
```

2021-01-21 17:05 UTC, cdrini approved these changes
Lgtm!

2021-01-21 17:05 UTC, merged