DRAFT: Run cron jobs in Docker
internetarchive/openlibrary pull request #4387
Opened 2021-01-08 12:01 UTC by cclauss

Closes #4383
Subtask of #4060

We are running on an oldev-based node but we want to run the cronjobs that are in [`/olsystem/etc/cron.d`](https://github.com/internetarchive/olsystem/blob/master/etc/cron.d).

https://stackoverflow.com/questions/37458287/how-to-run-a-cron-job-inside-a-docker-container

### Technical

### Testing

### Screenshot

### Stakeholders

2021-01-08 12:06 UTC, cclauss commented on docker-compose.yml
> +    command: docker/ol-cronjobs-start.sh
Do we need `COPY /olsystem/etc/cron.d /etc/cron.d/`

2021-01-08 12:07 UTC, cclauss commented on docker-compose.yml
> +    hostname: "$HOSTNAME"
Remove hostname?

2021-01-08 12:07 UTC, cclauss commented on docker-compose.yml
> +    environment:
Remove environment?

2021-01-08 12:08 UTC, cclauss commented on docker-compose.yml
> +    expose:
Remove expose?

2021-01-08 12:08 UTC, cclauss commented on docker-compose.yml
> +    depends_on:
Remove depends_on?

2021-01-08 12:08 UTC, cclauss commented on docker-compose.yml
> +      - dbnet
Remove dbnet?

2021-01-11 17:15 UTC, cclauss commented on docker-compose.yml
> +    command: docker/ol-cronjobs-start.sh
This file: openlibrary -> /olsystem/etc/cron.d/openlibrary.allnodes

2021-01-28 19:19 UTC, cclauss commented
Add  ia_db_pw_file for 5 * * * * python $SCRIPTS/openlibrary-server /olsystem/etc/openlibrary.yml runmain openlibrary.solr.process_stats --load-from-db > /var/log/openlibrary/loanstats.log 2>&1

2021-02-02 20:36 UTC, cdrini commented on docker-compose.production.yml
> +    command: cron -f
looks like this will need the `HOSTNAME` environment variable.

2021-02-05 12:39 UTC, cclauss commented
Added the solrwriter change where both `strip_bad_char()` and [`unicodedata.normalize()`](https://docs.python.org/3/library/unicodedata.html#unicodedata.normalize) expect `value` to be a `str`.

2021-02-05 18:15 UTC, cclauss commented
```html
<html>

<head>
    <title>Apache Tomcat/6.0.39 - Error report</title>
    <style>
        <!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}
        -->
    </style>
</head>

<body>
    <h1>HTTP Status 400 - ERROR: [doc=loans/loan-1944635007] Error adding field
        \'duration_hours_i\'=\'0.0008333333333333334\'</h1>
    <HR size="1" noshade="noshade">
    <p><b>type</b> Status report</p>
    <p><b>message</b> <u>ERROR: [doc=loans/loan-1944635007] Error adding field
            \'duration_hours_i\'=\'0.0008333333333333334\'</u></p>
    <p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p>
    <HR size="1" noshade="noshade">
    <h3>Apache Tomcat/6.0.39</h3>
</body>

</html>
```

2021-02-11 19:00 UTC, cdrini requested changes
Lgtm! One last change: Can you update our deploy script to make sure it starts this service?

2021-02-11 20:52 UTC, cclauss commented
I made that change on #4457 but that is still not landed.

2021-02-12 10:31 UTC, mekarpeles approved these changes
lgtm

2021-02-12 10:42 UTC, mekarpeles commented
I see restart always on the cron and #4457 has landed, going to merge this as well.

2021-02-12 10:42 UTC, merged