Allow cross origin access for cover images
internetarchive/openlibrary pull request #4452
Opened 2021-01-20 21:54 UTC by jamesachamp

Addresses #3399

Adds `Access-Control-Allow-Origin: *` to Open Library image API responses.  This only solves the issue for images coming from the coverstore.  Requests redirected to IA will not include this header in their response.

### Technical

### Testing

### Screenshot

### Stakeholders

2021-01-20 23:14 UTC, cdrini requested changes
Nice! I think we'll want to make use of https://github.com/internetarchive/openlibrary/blob/661c33744e92cd60502b53c2b66528249d349ce5/openlibrary/plugins/openlibrary/processors.py#L31-L53 to keep things DRY.

Maybe add a constructor so we can configure the paths, and then where the `covers` app is created in `coverstore/code.py`, we should be able to do something like `app.add_processor(CORSProcessor(...options...))`

2021-01-26 22:00 UTC, cdrini requested changes
Nice! Looking super close. We'll need this to be enabled for all covers.openlibrary.org paths, I believe. Otherwise small readability things.

2021-01-26 22:36 UTC, jamesachamp commented on openlibrary/coverstore/code.py
> +cors_paths = {
Is there a list of all the paths somewhere?

2021-01-26 22:55 UTC, jamesachamp commented on openlibrary/coverstore/code.py
> +cors_paths = {
Disregard, I think that I get it now. `b` stands for "books" and `w` works.  

Should I also include the paths that always redirect to IA?

2021-01-27 21:27 UTC, cdrini commented on openlibrary/coverstore/code.py
> +cors_paths = {
We should change this so that if we specify `None`, it will apply to all paths. That fits the use case a little better :+1:

2021-01-27 21:57 UTC, jamesachamp commented on openlibrary/coverstore/code.py
> +cors_paths = {
Let me make sure that I understand correctly:  
1. If nothing is passed to the `CORSProcessor` constructor, access control  headers will be added all responses.
2. If a set  of prefixes is passed in the constructor, headers will only be added for paths that begin with the prefix or paths that end with `.json`.

Is this correct?  If so, I would just have to update the processor code and pass `{"/api/"}` [here](https://github.com/internetarchive/openlibrary/blob/492f40215c5ff06df03ca82a9c25739d747d2c5b/openlibrary/plugins/openlibrary/code.py#L42).

2021-01-27 22:05 UTC, cdrini commented on openlibrary/coverstore/code.py
> +cors_paths = {
I think so! You'd also need to change the other call to the constructor to specify the 2 paths it needs :+1:

2021-02-02 20:46 UTC, cdrini approved these changes
Lgtm! Some small final fixes, and then I'll put on staging for testing. Note I won't really be able to test covers.openlibrary.org until we deploy, since that doesn't have a staging equivalent.

2021-02-02 20:46 UTC, cdrini commented on openlibrary/coverstore/code.py
> +app.add_processor(CORSProcessor(cors_paths))
Misunderstood; your original idea was correct :+1:

```suggestion
app.add_processor(CORSProcessor())
```

2021-02-02 20:46 UTC, cdrini commented on openlibrary/plugins/openlibrary/processors.py
> +        for path_segment in self.cors_prefixes:
```suggestion
        if self.cors_prefixes is None or web.ctx.path.endswith(".json"):
            return True
        for path_segment in self.cors_prefixes:
```

2021-02-02 20:46 UTC, cdrini commented on openlibrary/plugins/openlibrary/processors.py
> +        if can_share or web.ctx.path.endswith(".json"):
```suggestion
        if self.is_cors_path():
```

2021-02-02 21:03 UTC, cdrini commented
Tested:

- ✅ `await fetch('http://staging.openlibrary.org/authors/OL8624452A.json').then(r => r.json())` works from a different domain
- ✅ `await fetch('http://staging.openlibrary.org/api/get_many?keys=[%22/authors/OL8624452A%22]').then(r => r.json())` works from a different domain
- ✅ `await fetch('http://staging.openlibrary.org/authors/OL8624452A').then(r => r.text())` throws cors error
- [ ] (TODO) `await fetch('https://covers.openlibrary.org/b/id/727213-L.jpg').then(r => r.text())` works from a different server

2021-02-02 21:03 UTC, merged

2021-02-04 22:25 UTC, cdrini commented
Hmm, tested on prod now that we've deployed, and its still missing the headers... :/ Investigating.

2021-02-04 22:55 UTC, jamesachamp commented
That's weird.  Looks like `/api/` and `.json` paths are working, fortunately.  Is there a special procedure for deploying to the coverstore?

2021-02-24 15:38 UTC, cdrini commented
Actually this is now working, inexplicably! Maybe something glitched in the previous deploy. 🎉