Removed hover effects and fixed mobile nav menus' toggle buttons
internetarchive/openlibrary pull request #4501
Opened 2021-01-30 04:59 UTC by shrey27tri01

### Issue Number
Closes #4444 

### What does this PR achieve? 
Fix

### Technical

I have used the [checkbox hack](https://css-tricks.com/the-checkbox-hack/) to fix the toggle buttons of the mobile navbar menus. Also, removed the hover effect from the buttons, since they led to a not-so-friendly user interface.

### Testing

1. Open OpenLibrary in development mode
2. Open the developer console and toggle to mobile view
3. Open the Browse menu/More options menu/Account dropdown
4. Click on it again to close it.

2021-02-03 05:12 UTC, jdlrobson commented
Sorry for the delay - will get to this one by the end of the week!

2021-02-03 13:42 UTC, shrey27tri01 commented
No problem! :)

2021-02-04 06:24 UTC, jdlrobson requested changes
<img width="450" alt="Screen Shot 2021-02-03 at 10 19 06 PM" src="https://user-images.githubusercontent.com/148752/106853183-277ef700-666e-11eb-8a7c-58f1fe375381.png">
It's possible to open all the menus at the same time which doesn't seem right to me. Perhaps its possible to use a radio input so that only one can be open at a time?

2021-02-04 06:24 UTC, jdlrobson commented on openlibrary/templates/lib/nav_head.html
> +      <label role="button" for="toggle-more-menu" class="more-menu-button">$_('More')
Suggested follow up: Given the repetition could we use a macro in the templates for each of these?

2021-02-04 06:24 UTC, jdlrobson commented on openlibrary/templates/lib/nav_head.html
> +      <label role="button" for="toggle-browse-menu" class="browse-menu-button">$_('Browse')
Recently we discovered the w3c validator [1] doesn't like the role here, it needs to be on the checkbox itself.

[1] https://validator.w3.org/nu/#textarea

2021-02-18 02:42 UTC, jdlrobson commented
@shrey27tri01 do my requests make sense here or can I help clarify them some  how?

2021-02-18 02:48 UTC, shrey27tri01 commented
Really sorry, couldn't work on it. I will try and let you know if I need more clarification!

2021-02-27 23:44 UTC, merged