Removed inline js from excerpts.html
internetarchive/openlibrary pull request #4589
Opened 2021-02-12 18:56 UTC by nynaalekhya

Closes #4474

Removed inline js from excerpts.html  and moved to edit.js
### Technical

### Testing

### Screenshot

### Stakeholders

@jdlrobson

2021-02-18 02:37 UTC, jdlrobson requested changes
I'm struggling to review this one as there are lots of cases where you have changed lines, but not actually tried functionality.

Please aim to get the diff of your changes as small as possible for reviews as it makes the life of the reviewer a lot easier, by allowing them to focus on the parts that have changed. I'll take another look at this when that's done.

2021-02-18 02:37 UTC, jdlrobson commented on openlibrary/plugins/openlibrary/js/index.js
> +        import ('./edit.js')
You'll need to define a webchunk here `/* webpackChunkName: "patron_metadata" */`

2021-02-18 02:37 UTC, jdlrobson commented on openlibrary/plugins/openlibrary/js/index.js
> +        import (/* webpackChunkName: "readinglog_stats" */ './readinglog_stats')
please make sure to keep unrelated changes like this out of the final diff.

2021-02-18 02:37 UTC, jdlrobson commented on openlibrary/plugins/openlibrary/js/index.js
> +        import (/* webpackChunkName: "page-barcodescanner" */ './page-barcodescanner')
please make sure to keep unrelated changes like this out of the final diff.

2021-02-18 02:37 UTC, jdlrobson commented on openlibrary/plugins/openlibrary/js/index.js
> +        import (/* webpackChunkName: "patron_metadata" */ './patron-metadata')
please make sure to keep unrelated changes like this out of the final diff.

2021-02-18 02:37 UTC, jdlrobson commented on openlibrary/plugins/openlibrary/js/index.js
> +        $('#cboxPrevious').attr({ 'aria-label': 'Previous button', 'aria-hidden': 'true' });
please make sure to keep unrelated changes like this out of the final diff.

2021-02-18 02:37 UTC, jdlrobson commented on openlibrary/plugins/openlibrary/js/index.js
> +        $('#cboxPrevious').attr({ 'aria-label': 'Previous button', 'aria-hidden': 'true' });
also applies to the next few lines in this file

2021-02-27 18:29 UTC, jdlrobson commented
Hello @nynaalekhya do you have any questions? This patch has the right idea, and I'd love to see it merged but the unrelated changes make it hard to review.

2021-02-28 16:52 UTC, nynaalekhya commented
Thank you for asking! I will make the suggested changes.

2021-03-03 17:45 UTC, nynaalekhya commented
@jdlrobson, I have made the specified changes

2021-03-04 02:14 UTC, jdlrobson approved these changes
LGTM!

Tested on 
http://localhost:8080/books/OL24152177M/Robinson_Crusoe/edit

<img width="985" alt="Screen Shot 2021-03-03 at 6 14 09 PM" src="https://user-images.githubusercontent.com/148752/109900452-4318f580-7c4c-11eb-836d-808a84815ec3.png">

Also confirmed feature code only loads on editor - not homepage. Great job with the feature detected import!

2021-03-04 02:15 UTC, merged