Display lists patron's list in which the book is already added.
internetarchive/openlibrary pull request #4597
Opened 2021-02-13 19:35 UTC by prakashaditya369

Closes #3630 

Display the patron's list contatining a particular work underneath `Want to Read Button`.  
This will help patron easily remove books from list already added.
### Technical

Added `id = "list-lists"` alongwith `class = "listsLists"` in Line 296. This is because `class = "listLists"` is also used in Line 233. And we need to insert different lists in both `ul`. Hence separate query was needed.  
Added a new parameter `user_key`  to `render_widget_add`.  
Apart from that, can modify the name of `id` and renderer in Line 233 from `alreay-lists` [It sounds ambiguous].
### Testing

Open [http://localhost:8080/books/OL7037695M/The_complete_works_of_Mark_Twain](http://localhost:8080/books/OL7037695M/The_complete_works_of_Mark_Twain)  
The changes can be seen beneath `Want to Read Button`.

### Screenshot

![Screenshot from 2021-02-14 01-03-25](https://user-images.githubusercontent.com/62632865/107859585-7a239480-6e60-1900e-783f0baed527.png)

### Stakeholders

@mekarpeles @jdlrobson

2021-02-13 19:41 UTC, prakashaditya369 commented
Since the patron's list is already displayed beneath `Want to Read` button. Should we remove it from `Lists contaiing Lists`?

2021-02-24 23:02 UTC, mekarpeles commented
1. When I add a book to my Reading Log (e.g. "Want to Read") The down arrow seems to have disappeared on staging: http://staging.openlibrary.org/books/OL7829676M/The_Giver
2. when I test this feature, I don't see the widget -- only directly after I add a book on a list,. When I load the page or I refresh, it disappears

2021-02-24 23:03 UTC, mekarpeles requested changes
see feedback in conversation

2021-02-24 23:04 UTC, mekarpeles commented
https://github.com/internetarchive/openlibrary/pull/4597#issuecomment-778667967 
"All Lists containing this book" is **different** from "**my** lists containing this book" and shouldn't be removed

2021-03-04 21:56 UTC, prakashaditya369 commented
While inspecting the element in [http://staging.openlibrary.org/books/OL7829676M/The_Giver](http://staging.openlibrary.org/books/OL7829676M/The_Giver), I found out that the inspector was not able to load the image. So I clicked in the link for the image. Now, the link for the image opens in `https://staging....` which doesn't exist. But when I change `https` to `http` in image link, it opens. So, can the dropdown icon be missing because, the base-url for image url has "https://staging.." whereas it should be "http://staging.."? The same can be the case for database, so the files are not actually updated into database, and hence after refreshing they disappears?

The url opened when I click for image url in inspector:
![URL for image](https://user-images.githubusercontent.com/62632865/110036042-6df56d80-7d62-11eb-8d0a-388f31d7b774.png)

2021-04-27 20:50 UTC, mekarpeles commented
re-adding to staging -- @prakashaditya369 do you recall where we left off on this one? 

Is this issue still relevant?
https://github.com/internetarchive/openlibrary/pull/4597#issuecomment-790973177

2021-04-27 21:30 UTC, mekarpeles commented
I think this one should be ok to go!
![staging openlibrary org_works_OL15861476W_Glut](https://user-images.githubusercontent.com/978325/116315141-f4c43680-a764-11eb-9a46-8b4d0653fec2.png)

2021-04-27 21:30 UTC, merged

2021-04-28 13:32 UTC, prakashaditya369 commented
> I think this one should be ok to go!
> ![staging openlibrary org_works_OL15861476W_Glut](https://user-images.githubusercontent.com/978325/116315141-f4c43680-a764-11eb-9a46-8b4d0653fec2.png)

The problem was with the dropdown-arrow. And I think it is still not appearing in the image given.