Bug 4815
internetarchive/openlibrary pull request #4873
Opened 2021-03-23 00:00 UTC by jonbos

My first ever PR to an open source project! 😀 thanks all.

Closes #4815 

**Fix** - bump CSS loader to latest and repair css-loader resolution via options in webpack.config

### Technical

Changes `--parent` flag to OSX friendly `-p` flag in both `make css` and `make js` rules

### Testing

Run
`$ make css`
`$ make js`

### Stakeholders

@jdlrobson

2021-03-23 22:57 UTC, jdlrobson commented
Congrats on the milestone!!!! I will make sure I review by end of week but this looks very promising! :)

2021-03-23 23:36 UTC, jonbos commented
Thank you for the kind words! I love the Internet Archive and I'm eager to get further involved with this project.

2021-03-25 22:54 UTC, jdlrobson commented
It looks like this leads to an increase in the bundlesize that's being flagged when `npm test` is run. Can you investigate whether that's expected?

If it is, we'll need to update the `bundlesize.config.json` definition with the new sizes. If not (for example, the stylesheet might now base64 encode assets where we don't want to it), we may want to consider tweaking the solution.

2021-03-26 01:05 UTC, jonbos commented
@jdlrobson I noticed that too - I wasn't sure whether or not the size increase was expected. I will look into it!

2021-03-27 16:28 UTC, jdlrobson commented
i ran `make js` on current master branch and then again on your branch with `webpackconfig.optimization.minimize = false;`. When I review the diff of the two files I am seeing changes to CSS in the webpack bundle but nothing that concerns data URIs or background images. I've also tested it and the patch works for me.

So I think it's acceptable to rebase this patch on master and update the bundlesize like so https://github.com/internetarchive/openlibrary/pull/4813/files#diff-b300d4a00ffb54905382b1328c39daa504b2f3be828103b372f8b5f6b8f796a2

I don't think I can push to your pull request, otherwise I'd do this myself and merge.

Thanks for the contribution!

2021-03-27 16:29 UTC, jdlrobson commented on package.json
> +    "css-loader": "^5.1.3",
When rebasing please fix the version here and drop the ^. Using ^ means its harder for developers to reproduce the local environment, it also opens you up to security vulnerabilities by pulling down code from external places that has not been audited by us.

2021-03-27 17:30 UTC, jdlrobson commented on Readme.md
>  ### Developer's Guide
There's some unrelated changes in this rebase.

2021-03-27 17:31 UTC, jdlrobson requested changes
I think something went wrong with the rebase here.  You may need to do a force push. It may be easier to create a new branch/pull request.

2021-03-27 18:08 UTC, closed without merging

2021-03-27 18:09 UTC, jonbos commented
New PR at [4921](https://github.com/internetarchive/openlibrary/pull/4921)