With reference to issue #4492
internetarchive/openlibrary pull request #4919
Opened 2021-03-27 09:06 UTC by mitchell-frost

Closes #4492 

### Testing
All the tests work. The only problem is that the local version I have built with docker does not seem to have "Winnie_the_Pooh". Hence, I added the object-fit wherever I saw an image.

### Stakeholders
@jdlrobson

2021-03-27 12:15 UTC, Yashs911 requested changes
@mitchell-frost Thanks for the PR. But I don't think this is the right solution.
![image](https://user-images.githubusercontent.com/64412143/112720347-b8ae7380-8f23-11eb-8717-53c65f09f9e5.png)
You need to apply object-fit to all the book covers
and you also need to add background color according to https://github.com/internetarchive/openlibrary/issues/4492#issuecomment-771872381

For importing a book:
1) `docker-compose exec web bash`
2) `./scripts/copydocs.py /books/OL22906339M`

you can replace` /books/OL22906339M` with other terms such as` /works/OLxxxxxxx`

2021-03-27 12:47 UTC, Yashs911 commented on static/css/components/carousel.less
> +  object-fit: contain;
Not required here

2021-03-27 12:47 UTC, Yashs911 commented on static/css/components/carousel.less
> +  object-fit: contain;
Not required here

2021-03-27 12:47 UTC, Yashs911 commented on static/css/components/listLists.less
>        img {
Should be applied here. + Background color

2021-03-27 12:47 UTC, Yashs911 commented on static/css/components/lists-page-cta.less
> +    object-fit: contain;
Not required here.

2021-03-27 12:47 UTC, Yashs911 commented on static/css/components/mybooks.less
> +  object-fit: contain;
Not required here.

2021-03-27 12:52 UTC, Yashs911 commented
@mitchell-frost You need to apply the object-fit property on:

1. homepage/subject carousel book covers.
2. lists covers https://openlibrary.org/lists
3. subject list cover https://openlibrary.org/subjects/architecture 
![image](https://user-images.githubusercontent.com/64412143/112721332-49d41900-8f29-11eb-891a-1dbbab987b64.png)

2021-03-27 14:46 UTC, mitchell-frost commented
@Yashs911 thanks a lot! The code base is a bit overwhelming for me. Any help on where I can find the CSS for these specific pages?

2021-03-27 15:36 UTC, Yashs911 commented
> @Yashs911 thanks a lot! The code base is a bit overwhelming for me. Any help on where I can find the CSS for these specific pages?

@mitchell-frost what I generally do is:
Inspect the element and then search that CSS selector using a code editor (VSCode).
For e.g. homepage carousel book cover css selctor is `.book img.bookcover`
On searching for .bookcover you will  find the CSS in `static\css\components\book.less` (https://github.com/internetarchive/openlibrary/blob/master/static/css/components/book.less)

2021-03-27 15:53 UTC, jdlrobson requested changes
Per @Yashs911

2021-04-04 14:38 UTC, Yashs911 commented
@mitchell-frost Any update on this.

2021-04-23 19:35 UTC, jdlrobson commented
Closing this due to inactivity to free up the task for another contributor. Feel free to reopen at any time. Thank you for your contribution!

2021-04-23 19:35 UTC, closed without merging