adding title to the iframe for accesibilty
internetarchive/openlibrary pull request #5002
Opened 2021-04-07 18:08 UTC by ArunTeltia

What I understand after searching the whole open library, that there are many places where i frame are present 

Here are the files 
openlibrary\macros\BookPreview.html 
openlibrary\macros\iframe.html
(I have a suspicion that these two files are dead code, not 100% sure tho)
openlibrary\plugins\openlibrary\js\covers.js (Line 45 function add_iframe())

About this PR, I got to know that the i frame is being created by this script 
https://archive.org/includes/donate.js

and as this is the script in internet archive not open library we need to manually add the title which i did in this PR

Please Review @bpmcneilly

2021-04-07 18:52 UTC, bpmcneilly requested changes
@ArunTeltia - Thanks for investigating this! I'll defer to other folks, but I think we may need to just adjust the original Archive.org js file, rather than forcing through additional JS on openlibrary. I was thinking (more hoping I guess) that we'd just need to edit a template here.

I will say, that add_iframe function is definitely a good find though. We should definitely be supplying a title for any iFrames we add, and we will need to be able to pass a title attribute to that function to do so. Could you look into how often (if at all) this function is used & updating it to ensure we have titles on all of our iFrames?

2021-04-07 18:59 UTC, ArunTeltia commented
For Sure @bpmcneilly

2021-04-07 19:40 UTC, ArunTeltia commented
@bpmcneilly So after further checks, i found one more file that have <iframe> 

openlibrary\macros\SocialShare.html

and about the add_iframe() function I found out its been used in 
openlibrary\plugins\openlibrary\js\covers.js(Line 25 and being used by initCoversChange function);
initCoversChange is being used in 
openlibrary\plugins\openlibrary\js\index.js(Line 176) 

and eventually this is bieng used in 
openlibrary\templates\covers\change.html(Line 32) 

I am not sure where this change.html is being used, I am finding this out

2021-04-12 20:12 UTC, mekarpeles commented
@bpmcneilly let's discuss during our 1:1 tomorrow

2021-04-19 16:42 UTC, mekarpeles commented
@bpmcneilly + @ArunTeltia, we ended up submitting a PR on the archive.org internal repo to resolve this and so we're closing this issue. Thank you for proposing a solution and helping us address this problem!

2021-04-19 16:42 UTC, closed without merging