Refactor/Move inline js from work_search template
internetarchive/openlibrary pull request #5068
Opened 2021-04-19 22:51 UTC by lephemere

Closes `openlibrary/templates/work_search.html` point from #4474

Move inline JavaScript from work_search.html template to index.js and search.js.

### Technical

### Testing

Search Facets:
- expand available filter item list in the `Zoom in` area with the `more` button
- reduce available filter item list in the `Zoom in` area with the `less` button
- verify bullet between `more` and `less` button is hidden when `less` button is hidden

Admin Timing:
- Connect as admin
- Verify that `Read API call took XX seconds` message appears at the bottom of the search results

### Screenshot

### Stakeholders

@jdlrobson

2021-04-23 20:01 UTC, jdlrobson requested changes
This looks great. A few nitpicks to fix up.

Sorry for the delay here. I will endeavour to be more speedy with my follow up review/merge.

2021-04-24 12:59 UTC, lephemere commented on openlibrary/plugins/openlibrary/js/index.js
> +    if (document.getElementById('adminTiming')) {
Isn't it dangerous, as if we make modifications to the `searchFacets` section (let's say we remove it for whatever reason), we automatically "break" the `adminTiming` section?

2021-04-24 13:35 UTC, lephemere commented on openlibrary/plugins/openlibrary/js/search.js
> +        const ol = 'openlibrary.org';
@jdlrobson Do you know what the use of the `readapi_percent` variable is or was?
`const readapi_percent = 100;if (Math.random() * 100 < readapi_percent) {}` is always true and could be removed.

2021-04-24 16:53 UTC, jdlrobson commented on openlibrary/plugins/openlibrary/js/index.js
> +    if (document.getElementById('adminTiming')) {
I think this is true of most our code. I would rather rely on code review, monitoring and integration tests for protecting against that happening.

For me readability is more important here. The adminTiming code only applies to the search code. It's important to make this clear in the code by having a central point of entry for the code.

Imagine if we added a bunch of code on L180 and these two bits of code got separated. That's more likely to lead to error IMO

2021-04-24 16:53 UTC, jdlrobson commented on openlibrary/plugins/openlibrary/js/search.js
> +        const ol = 'openlibrary.org';
Good catch. This code predates me and yes it doesn't make sense.

I imagine before that this was sampled and the sampling was bumped up to 100%. Let's take this opportunity to cleanup and document that 100% of the views of admins will be sampled.

2021-04-24 16:53 UTC, jdlrobson commented on openlibrary/plugins/openlibrary/js/search.js
> +function more(header, start_facet_count, facet_inc) {
thank you!

2021-04-24 16:53 UTC, jdlrobson commented on openlibrary/plugins/openlibrary/js/search.js
> +export function initSearchFacets() {
Thank you! super helpful going forward!

2021-04-24 19:15 UTC, lephemere commented on openlibrary/plugins/openlibrary/js/index.js
> +    if (document.getElementById('adminTiming')) {
OK, makes sense. I'll update that ASAP!

2021-04-25 16:54 UTC, jdlrobson approved these changes
I just need to pull this down one last time for testing but code looks good.

2021-04-26 04:25 UTC, merged