Fix show less facet function on search page
internetarchive/openlibrary pull request #5109
Opened 2021-04-29 21:25 UTC by lephemere

Closes #5064

Fix show less facet function used on [Search page](https://openlibrary.org/search).
The `less()` function was able to hide all facets of a facet list in the `Zoom in` area when all available facets where displayed via the `more()` function.

### Technical

`less()` function now reverts the `more()` function action when reaching the end of the facet list (Especially, when remaining hidden facet number < `facet_inc`).

### Testing

Test for facet list with `5 + N * 10 + X` nb of items where:

 - `N = 0` or `N > 0`
 - `X = 0` or `0 < X < 10`

(Default nb of displayed facet is currently `5` and increment `10`)

### Screenshot

### Stakeholders

@cdrini

2021-05-09 05:19 UTC, jdlrobson requested changes
We should add a test so that we protect against this breaking again. @lephemere have you got any experience writing tests in jest?

2021-05-09 10:10 UTC, lephemere commented
@jdlrobson no yet, but that's a good opportunity to learn something new and gather some experience.

2021-05-09 16:08 UTC, jdlrobson commented
> @jdlrobson no yet, but that's a good opportunity to learn something new and gather some experience.

Cool! Would you prefer to do it as part of this pull request or as a separate one? 

As a starting point you'll want to make sure you can run the tests (`npm run test:js`) and  export this new method so it's accessible from the tests and create a file called `tests/unit/js/test.search.js`. that imports and runs it.

Happy to guide you through this on Slack if you hit any problems!

2021-05-23 17:39 UTC, jdlrobson commented
Merging given https://github.com/internetarchive/openlibrary/pull/5195 is underway!

2021-05-23 17:40 UTC, merged