Delete site/stats.html (debug-stats)
internetarchive/openlibrary pull request #5200
Opened 2021-05-24 05:30 UTC by Yashs911

Related to #4474 

Deleted site/stats.htlm (because its not used anymore)

### Stakeholders

@jdlrobson

2021-05-24 14:44 UTC, jdlrobson requested changes
I see a render_template call in openlibrary/templates/site/footer.html to this template that is invoked when the debug parameter is in the URL.

that's referenced in openlibrary/templates/site.html

I can see this Html in the page on the followng URL
https://openlibrary.org/?debug=1

it doesn't look dead to me!

2021-05-24 14:54 UTC, Yashs911 commented
But I am unable to use `Ctrl+Alt+.` so what should I do?

2021-05-24 14:56 UTC, jdlrobson commented
the script might be dead code/useless code, so we could remove that? But deleting the file will make debug=1 URLs stop working entirely which would be bad :)

2021-05-24 16:35 UTC, Yashs911 commented
PR updated

2021-05-29 22:33 UTC, jdlrobson approved these changes
I can still see this by going to http://localhost:8080/?debug=true

and adding this to the JavaScript console:
```
$("#debug-stats").removeClass('hidden')
```
This probably should be documented on the wiki somewhere...

2021-05-29 22:34 UTC, merged