Refactor/Move inline js from books/edit template
internetarchive/openlibrary pull request #5211
Opened 2021-05-26 21:14 UTC by lephemere

Closes openlibrary/templates/books/edit.html point from #4474

Move inline JavaScript from books/edit.html template to index.js and edit.js.

### Technical

Dead code removed (`$(#excerpt).keyup()` and associated `limitChars()`)

### Testing

### Screenshot

### Stakeholders

@jdlrobson

2021-05-29 22:52 UTC, jdlrobson commented on openlibrary/plugins/openlibrary/js/edit.js
> +        if ($(fieldname).length != 0) {
Use !==

2021-05-29 23:02 UTC, jdlrobson commented
> Dead code removed ($(#excerpt).keyup() and associated limitChars())

<img width="791" alt="Screen Shot 2021-05-29 at 4 00 47 PM" src="https://user-images.githubusercontent.com/148752/120086816-0a47bb80-c097-11eb-9826-30bd00d6b479.png">

Looks like the code should be applying to this element. Looks like it got broken at some point, so let's fix that! 

Call  `limitChars('excerpts-excerpt'` instead of `limitChars('excerpt'` and I think this should magically work again.

2021-05-29 23:02 UTC, jdlrobson requested changes

2021-05-29 23:02 UTC, jdlrobson commented on openlibrary/templates/books/edit.html
> -function limitChars(textid, limit, infodiv) {
Per my comment, this code should be fixed not remove.d

2021-06-01 17:55 UTC, lephemere commented
> 
> 
> > Dead code removed ($(#excerpt).keyup() and associated limitChars())
> 
> <img alt="Screen Shot 2021-05-29 at 4 00 47 PM" width="791" src="https://user-images.githubusercontent.com/148752/120086816-0a47bb80-c097-11eb-9826-30bd00d6b479.png">
> 
> Looks like the code should be applying to this element. Looks like it got broken at some point, so let's fix that!
> 
> Call `limitChars('excerpts-excerpt'` instead of `limitChars('excerpt'` and I think this should magically work again.

I have reinstated the `limitchars()` functionnality and moved it to `initEditExcerpts()` for consistency.
We may need to change the visual of this section in another PR:
- The text is now strictly limited to 2000 characters and automatically cut.
- The red warning character count in `excerpts-excerpt-len` section is never reached and the "limit reached" information is less visible.

Before:
![image](https://user-images.githubusercontent.com/73437497/120368748-bcd78280-c312-11eb-88e0-d1bf4da0c5d1.png)

After:
![image](https://user-images.githubusercontent.com/73437497/120368853-db3d7e00-c312-11eb-85ea-c65db8b0c7c3.png)
![image](https://user-images.githubusercontent.com/73437497/120368928-ee504e00-c312-11eb-97ff-3088a93e43dc.png)

2021-06-01 18:36 UTC, tfmorris commented
If those images are accurate, it looks like internationalization is broken (and the HTML prohibition is missing from English).

2021-06-01 19:23 UTC, lephemere commented
@tfmorris internationalization is broken as message is overwritten via javascript. I have seen this topic is already discussed in issue #2607.
For this particular case, as the number of remaining character information is already given by the number on the right, I will disable the modification done to the `Maximum length...` message, hence keeping the same level of information and preserving internationalization.

2021-06-02 05:15 UTC, jdlrobson commented
Thanks for going the extra mile and preserving i18n here @lephemere ! Thanks @tfmorris for flagging!

2021-06-02 05:15 UTC, merged