Donate button fixed (firefox issue)
internetarchive/openlibrary pull request #5246
Opened 2021-05-31 09:30 UTC by soham4abc

Closes #5153

2021-05-31 16:39 UTC, jdlrobson commented on static/css/components/iaBar.less
> +  -ms-flex-align: center;
When using vendor prefixed properties, the standard one should always be applied.

2021-05-31 16:40 UTC, jdlrobson requested changes
See comment.

2021-06-02 17:26 UTC, jamesachamp commented on openlibrary/templates/site/alert.html
> +      <div class="iaBarDonate">
This change is a bit confusing.  To my mind, the class name implies that this element is the donate button (instead of the logo).

2021-06-02 17:28 UTC, jamesachamp commented on static/css/components/iaBar.less
> +    align-items: baseline;
This is not affecting the layout, as the `iaBarDonate` element is not a flex or grid container.

2021-06-03 04:35 UTC, soham4abc commented
My bad I am closing this PR.

2021-06-03 04:35 UTC, closed without merging