primes Carousel.js to work w/ Lists + fixes existing bugs
internetarchive/openlibrary pull request #5293
Opened 2021-06-10 18:04 UTC by mekarpeles

Upgrades our Carousel.js loadmore functionality to be more robust to values returned by API.

### Technical

This fixes cases where:

1. our availability API returns `status: private` e.g. https://archive.org/services/availability?identifier=Hello.
2. prevents breakage when `book` doesn't have an `identifier` / `ocaid`
3. improves availability accuracy by looking for additional fields for availability options

### Testing

Existing carousels should work without much change. @seabelis may have noticed some carousels which **don't** have `ocaid`s (e.g. Not In Library) likely break existing carousels when we try to Load More pages via ajax. This should be solved.

This PR is also a pre-requisite for passing list keys to `QueryCarousels`

### Stakeholders

@cdrini @jamesachamp

2021-06-10 22:03 UTC, mekarpeles reviewed
old feedback, disregard

2021-06-10 22:43 UTC, jamesachamp commented on openlibrary/plugins/openlibrary/js/carousel/Carousel.js
> +                            var works = results.works || results.docs;
```suggestion
                            const works = results.works || results.docs;
```
We should move away from using `var` to declare variables.  `const` is good in this case as `works` will not be reassigned.

2021-06-10 23:06 UTC, jamesachamp commented on openlibrary/plugins/openlibrary/js/carousel/Carousel.js
> +                    (`/books/${openlibrary_edition}`) : work.key;
Are the URLs for preview buttons handled here?  It looks like they'll redirect to `/borrow/ia/${ocaid}`.

2021-06-10 23:12 UTC, jamesachamp requested changes
Aside from the `var` and the question about preview button URLs, this looks good to me.

2021-06-11 00:03 UTC, jamesachamp commented on openlibrary/plugins/openlibrary/js/carousel/Carousel.js
> +                    (`/books/${openlibrary_edition}`) : work.key;
Disregard this.  I didn't realize that "Preview" was merely the call to action for private books, and not an actual preview button.

2021-06-11 06:22 UTC, merged