List + Solr work_key powered QueryCarousel
internetarchive/openlibrary pull request #5299
Opened 2021-06-11 06:59 UTC by mekarpeles

Allows List keys to be passed to `QueryCarousel` macro to power carousels

### Technical

This PR extends `QueryCarousel` so a list key may be provided, such as `/people/mekBot/lists/OL104041L/` and the when https://github.com/internetarchive/openlibrary/compare/master...list-querycarousel#diff-a6072af04af429689c35331c2a4a35fa2c23317099533cc2161ef6d8ba79df90R1034 is called, the list will be expanded into a set of work_keys which are *then* passed through to solr.

Note: The limit and offset are necessarily for paging through the List, but we **don't** want the limit and offset to be applied to solr because solr is going to receive a discrete list of work_ids (from the already paginated/offset List) and we want to return all of these works from solr. 

Will likely be unnecessary once/if Lists are in solr

### Testing

Adding a `{{ QueryParam("/people/mekBot/lists/OL104041L/") }}` (please check syntax) macro somewhere not too public (e.g. user profile page) should do the trick once this code is on testing. 
 
### Screenshot

Will add once it's on testing

### Stakeholders

@cdrini @seabelis

2021-06-11 10:02 UTC, cclauss commented
Please run psf/black on this code to autofix the failing tests...
```
git diff "${BASE_BRANCH:-master}" -U0 | ./scripts/flake8-diff.sh
openlibrary/plugins/openlibrary/lists.py:210:1: E302 expected 2 blank lines, found 1
openlibrary/plugins/openlibrary/lists.py:225:17: W503 line break before binary operator
openlibrary/plugins/openlibrary/lists.py:237:1: E302 expected 2 blank lines, found 1
openlibrary/plugins/openlibrary/lists.py:251:1: E302 expected 2 blank lines, found 1
openlibrary/plugins/openlibrary/lists.py:255:1: E302 expected 2 blank lines, found 1
openlibrary/plugins/openlibrary/lists.py:269:1: E302 expected 2 blank lines, found 1
openlibrary/plugins/openlibrary/lists.py:327:1: E302 expected 2 blank lines, found 1
openlibrary/plugins/openlibrary/lists.py:367:1: E302 expected 2 blank lines, found 1
openlibrary/plugins/worksearch/code.py:1011:1: E302 expected 2 blank lines, found 1
openlibrary/plugins/worksearch/code.py:1048:89: E501 line too long (98 > 88 characters)
openlibrary/plugins/worksearch/code.py:1109:89: E501 line too long (93 > 88 characters)
8     E302 expected 2 blank lines, found 1
2     E501 line too long (98 > 88 characters)
1     W503 line break before binary operator
```

2021-07-22 13:27 UTC, mekarpeles commented on openlibrary/plugins/openlibrary/lists.py
> -class list_editions(delegate.page):
`list_editions` (not the json endpoint) appears to be dead code as there is no such template `type/list/editions.html`

`r"(/people/\w+/lists/OL\d+L)/editions"` i.e.
https://openlibrary.org/people/mekBot/lists/OL104041L/Popular_Books/editions?debug=true

2021-07-22 20:17 UTC, mekarpeles commented on openlibrary/macros/QueryCarousel.html
> +  params = { 'q': query, 'fields': '*,availability' }
Ensures the "load more" solr query behind the scene also fetches / shuffles in book availability for carousels

2021-07-23 20:55 UTC, jamesachamp commented on openlibrary/plugins/openlibrary/lists.py
> +        if not lst or lst.type.key == '/type/delete':
```suggestion
        if not lst or lst['type']['key'] == '/type/delete':
```
This is throwing an attribute error on testing.  Even with the above change, a KeyError is thrown when `raw` is false.  There should either be another check for `lst['links']['self'] here when `raw is false, or `type.key` should be added to the dictionary returned by `get_list()`.

2021-07-23 21:01 UTC, jamesachamp requested changes
The new ListCarousel macro seems to be working properly locally and on testing.  The list JSON endpoint is returning errors, though.

2021-07-30 13:44 UTC, mekarpeles commented on openlibrary/plugins/openlibrary/lists.py
> +            "description": (
```suggestion
            "type": { "key": lst.key },
            "description": (
```

2021-07-30 13:46 UTC, mekarpeles commented on openlibrary/plugins/openlibrary/lists.py
> +            "type": { "key": lst.key },
```suggestion
            "type": {"key": lst.key},
```

2021-07-30 18:05 UTC, merged