Show outage banner on Open Library for mobile
internetarchive/openlibrary pull request #5315
Opened 2021-06-14 15:50 UTC by mekarpeles

Followup to #5313 

### Stakeholders

@cdrini

2021-06-14 16:13 UTC, jamesachamp commented
This seems to look alright when tested locally:

![local-responsive-banner](https://user-images.githubusercontent.com/28732543/121924411-deb90800-cd09-11eb-9595-2a69c200a1a7.png)

2021-06-14 17:58 UTC, cdrini requested changes

2021-06-14 17:58 UTC, cdrini commented on static/css/components/page-banner.less
> +    display: block;
^^ Further up in this file, there's `display:none` on the main `.page-banner` element; let's knock that off, and the corresponding media query that displays the banner on small screens.

2021-06-15 06:49 UTC, mekarpeles commented
Was this one ever patch deployed?

2021-06-15 06:49 UTC, mekarpeles commented
I see that it was here:
https://github.com/internetarchive/openlibrary/pull/5313/files#r651496174
Thank you!

2021-06-18 14:47 UTC, cdrini commented
All done and a bottle of rum!

2021-06-18 14:49 UTC, cdrini commented
Ooops, closed the wrong one :P

2021-06-21 19:23 UTC, jamesachamp commented
Resolved with inline CSS in #5313

2021-06-21 19:23 UTC, closed without merging