fixing availability of search.json
internetarchive/openlibrary pull request #5354
Opened 2021-06-26 07:22 UTC by mekarpeles

Fixed `work_search` so that search.json adds `availability` from bulk availability API when `*` or `availability in `fields`

http://testing.openlibrary.org:1337/search.json?q=OL21814522M&fields=*
http://testing.openlibrary.org:1337/search.json?q=OL21814522M&fields=availability

### Stakeholders

@cdrini

2021-06-26 07:23 UTC, mekarpeles commented on openlibrary/plugins/worksearch/code.py
> +    if 'availability' in fields and 'ia' not in fields:
availability API requires that the `ia` field is present

2021-07-07 21:07 UTC, cdrini requested changes

2021-07-07 21:07 UTC, cdrini commented on openlibrary/plugins/worksearch/code.py
> +    if '*' in fields or 'availability' in fields:
This is the one piece I'm wary about for performance reasons; in order to get this out today, let's drop this piece. You can tell the person who emailed you that they need to change their query URLs to `fields=*,availability`, or, if they want smaller/faster/tidier, `fields=key,ia,availability`.

```suggestion
    if 'availability' in fields:
```

2021-07-07 21:07 UTC, cdrini commented on openlibrary/plugins/worksearch/code.py
> +        fields.append('ia')
Fields is a CSV; this causes an error
```suggestion
    if 'availability' in fields and 'ia' not in fields:
        fields += ",ia"
```

2021-07-07 21:11 UTC, cdrini commented on openlibrary/plugins/worksearch/code.py
> +        fields.append('ia')
Nope, nevermind; looks like it's sometimes a string -_-

2021-07-07 21:17 UTC, cdrini commented on openlibrary/plugins/worksearch/code.py
> +        fields.append('ia')
Not sure; this isn't working correctly on testing as is.

2021-07-22 13:12 UTC, closed without merging