Ratings and reading logs dumps
internetarchive/openlibrary pull request #5426
Opened 2021-07-14 06:27 UTC by BharatKalluri

Closes #3989 

A script which will generate data dumps for ratings and reading logs. In the format suggested at #3989 

### Testing

#3989 has some tests and perf stats. After the test, I've added OL and M/W concat on edition ID and work ID. Also added headers to the export.

### Stakeholders

@cdrini

2021-07-17 16:53 UTC, cdrini requested changes
Woohoo, great!

Eventually, this will be run as part of the cron file. We generally do the gzipping there (so that we can append a date to the filename), so these don't have to do that. I think we just want the sql, so let's create `dump-ratings.sql` and `dump-reading-log.sql`. If you add a shebang line with `psql -U openlibrary -d openlibrary -f `, that should make it work in the local dev environment when run as `./scripts/dump-ratings.sql` :)

Also, I spoke with @prezvi, and it looks like we do want to reduce the precision of the date fields, so let's drop it to the day. Maybe we can use a truncation function?

Note to self: We'll need to add this to olsystem's cron oldump.sh file ( https://github.com/internetarchive/olsystem/blob/master/bin/cron/oldump.sh ):

- Add the new files, `ol_dump_ratings_{date}.txt.gz` and `ol_dump_reading-log_{date}.txt.gz` to archive section
- Add `time psql -h $host $db -f /openlibrary/scripts/oldump-ratings.sql | gzip -c > ol_dump_ratings_$date.txt.gz` + for reading-log

2021-07-17 16:53 UTC, cdrini commented on scripts/dump-ratings-reading-log.sh
> +  select
Let's make all keywords uppercase; makes the sql a little easier to read.

2021-07-17 16:53 UTC, cdrini commented on scripts/dump-ratings-reading-log.sh
> +  concat('OL', bookshelves_books.work_id, 'W') as work_id,
I believe this is the format of the `Key` column in the OL data dumps; let's keep it the same.

```suggestion
  concat('/works/OL', bookshelves_books.work_id, 'W') as work_id,
```

2021-07-17 16:53 UTC, cdrini commented on scripts/dump-ratings-reading-log.sh
> +    else concat('OL', bookshelves_books.edition_id, 'M')
```suggestion
    else concat('/books/OL', bookshelves_books.edition_id, 'M')
```

2021-07-17 16:53 UTC, cdrini commented on scripts/dump-ratings-reading-log.sh
> +  concat('OL', ratings.work_id, 'W') as work_id,
Don't need the table name here, since we're only using one table in this query.
```suggestion
  concat('OL', work_id, 'W') as work_id,
```

2021-07-17 17:01 UTC, cdrini commented
Oh, and another thing: The current dumps uses the date as a limit; so the dump for 2021-07-10 will only include edits made before that date. So we'll need to add a `WHERE create <= $DATE` to both of these, I think :/

2021-07-17 17:50 UTC, BharatKalluri commented
added a date filter and reduced timestamp precision as suggested 👍🏽 

I think we need to use a bash script to pass in variables to the query. There will be two scripts now instead of one, `dump-ratings.sh` and `dump-reading-log.sh`. They can be used by passing the date env. For example `till_date='2021-07-17' sh ./scripts/dump-ratings.sh`.

Let me know if there are any more changes required :)

2021-07-22 20:34 UTC, merged

2026-04-30 19:43 UTC, tfmorris commented
This introduced a weird "CSV with TAB delimiter" format unlike the standard TSV format which has been used for dumps since the beginning of OpenLibrary. It would be much better to use the same format (ie TSV) for all dumps.