Add string format validation to `i18n-messages validate`
internetarchive/openlibrary pull request #5570
Opened 2021-08-20 05:15 UTC by jimchamp

Adds built-in string format validation to `i18n-messages validate`

### Technical

### Testing

1. Execute `i18n-messages validate` using a locale with known format string errors.
2. Ensure that error messages displayed identify all messages with errors.

### Screenshot

### Stakeholders

@cdrini

2021-08-23 13:48 UTC, cdrini requested changes
Nice! I can't believe this function already existed :D Haven't tested yet, but left some code quality feedback.

2021-08-23 13:48 UTC, cdrini commented on openlibrary/i18n/validators/format_validator.py
> +from babel.messages.catalog import TranslationError
This class hierarchy feels like too much here. The fact that both subclasses (1) don't override the constructor, and (2) have only one method, makes it look like these are just functions in disguise as classes. Let's dissolve the base class, and have two functions in a single `validators.py` file: `validate_python_format(message, catalog)` and `validate_not_fuzzy(message, catalog)`.

2021-08-23 13:48 UTC, cdrini commented on openlibrary/i18n/validators/format_validator.py
> +                    errors = [f'    {e}']
```suggestion
                errors.append(f'    {e}')
```

2021-09-01 20:03 UTC, cdrini requested changes
- [ ] Run both `fmt` algorithms, since they seem to be catching different issues
- [ ] Pull in the format algorithm from test_po_file ; remove the `test_python_format` test in there.
- [ ] Make sure that format checker does not error for msgstr == "", and that it does not error for plurals (skip those)

2021-09-01 20:03 UTC, cdrini commented on openlibrary/i18n/validators.py
> +def _validate_format(message, catalog):
If you can find the type of these inputs, adding would be nice. Nice-to-have, not a blocker.

```suggestion
def _validate_format(message: Message, catalog: Catalog) -> List[str]:
```

2021-09-03 15:09 UTC, cdrini requested changes

2021-09-03 15:09 UTC, cdrini commented on openlibrary/i18n/validators.py
> +    if len(msgstr) and isinstance(msgstr, str):
Ah, for plurals. Looks like this isn't working...

2021-09-03 15:09 UTC, cdrini commented on openlibrary/i18n/validators.py
> +    errors.extend(_validate_cfmt(message.id, message.string))
Thanks to the type hints, I can now quickly/easily investigate what other options these have!

```suggestion
    if message.string and message.pluralizeable:
        errors.extend(_validate_cfmt(message.id, message.string))
```

2021-09-03 16:58 UTC, jimchamp commented on openlibrary/i18n/validators.py
> +    if len(msgstr) and isinstance(msgstr, str):
Replaced this with a test for `message.pluralizeable` in the `validate` function.

2021-09-03 18:52 UTC, cdrini approved these changes
Woohoo! This looks great :) Ran it over each language, and the output is _super_ handy!

2021-09-03 18:52 UTC, merged