Link to author identifier docs from author edit page #5436
internetarchive/openlibrary pull request #5591
Opened 2021-08-29 19:12 UTC by goyaldhara

Closes #5436 

Link to the author identifier docs here from the author edit page.

### Technical
On the author edit page: openlibrary\templates\type\author\edit.html
Added Link and Question mark icon to author identifier link :  https://openlibrary.org/help/faq/editing.en#author-identifiers-purpose

### Testing

### Stakeholders
@RayBB

2021-08-30 02:16 UTC, RayBB commented
Hey @goyaldhara thanks for opening this PR!

I know in the original issue I said that we should try to use a better icon and you did that. To use something like FA the community would need to agree on it and have it setup somewhere more central to the project - instead of just adding it to each page. Perhaps it's best tackled as a separate issue.

The rest of the code is in the right spot and looks about right.
Lets try to use the `?` icon used for the markdown editor instead to keep a consistent appearance cross the site.

If you can do that I think this would be about ready to merge!

Btw I'd encourage you to come to the weekly community call on Tuesday if you can and share what you've done and say hi to folks. https://github.com/internetarchive/openlibrary/wiki/Open-Library-Community-Call-Minutes

2021-09-27 19:45 UTC, mekarpeles commented on openlibrary/templates/type/author/edit.html
> +<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
I think we may want to do this without importing font-awesome, but otherwise the link looks fine.

2021-09-28 20:13 UTC, jimchamp commented on openlibrary/templates/type/author/edit.html
>                          <div class="label">Identifiers</div>
Question mark icon should appear to the right of the "Identifiers" label.  It appears beneath the form inputs now:
![question_icon_before](https://user-images.githubusercontent.com/28732543/135158899-46958dd3-77a8-47d7-9aa3-d63e4c7c1ad0.png)

2021-09-28 20:19 UTC, jimchamp requested changes
Requesting that you replace the new question mark icon with `/static/images/icons/icon_help.png`, and that the icon is moved to the right of the "Identifiers" label.

Please let me know if you have any questions.

2021-09-28 20:19 UTC, jimchamp commented on openlibrary/templates/type/author/edit.html
> +                            $:render_component('AuthorIdentifiers', attrs=dict(assigned_ids_string=dict(page.remote_ids),output_selector='#hiddenIdentifierInputs',author_config_string=dict(get_author
The Font Awesome icon can be replaced with an icon that we are already using (like [this](https://github.com/internetarchive/openlibrary/blob/master/static/images/icons/icon_help.png)).

2021-11-09 22:19 UTC, RayBB commented
@goyaldhara are you still interested in working on this? Is there anything you need help with?

2021-11-29 17:47 UTC, jimchamp commented
Closing this for now.  @goyaldhara, feel free to re-open this issue if you are still working on the suggested changes.

2021-11-29 17:47 UTC, closed without merging