Refactor button story to use string literals
internetarchive/openlibrary pull request #5639
Opened 2021-09-09 11:25 UTC by jimman2003

refactor
### Technical

uses string literals , as a crude way to follow https://storybook.js.org/docs/vue/get-started/setup
### Testing

### Screenshot

### Stakeholders

@mekarpeles @jdlrobson

2021-09-09 14:20 UTC, jdlrobson approved these changes

2021-09-13 23:35 UTC, jimchamp commented on stories/Button.stories.js
> +const ButtonTemplate = (classes,innerHtml) => `<div class="${classes}">${innerHtml}</div>`;
Would it be easier to add controls later if we pass arguments that could be used as controls?  Maybe something like this:
```suggestion
const ButtonTemplate = (buttonType, text, badgeCount=null) => `<div class="cta-btn ${ButtonTypes[buttonType]}">${text} ${badgeCount ? BadgeTemplate(badgeCount) : ''}</div>`;

const BadgeTemplate = (badgeCount) => `<span class="cta-btn__badge">${badgeCount}</span>`

const ButtonTypes = {
    default: '',
    unavailable: ' cta-btn--unavailable',
    available: ' cta-btn--available',
    preview: ' cta-btn--shell cta-btn--preview'
}
```

2021-09-14 15:12 UTC, jimchamp requested changes
We'll also have to change the way that the buttons are instantiated.  For example:
`export const CtaBtn = () => ButtonTemplate('default', 'Leave waitlist');`
`// Other changes omitted for brevity...`
`export const CtaBtnWithBadge = () => ButtonTemplate('unavailable', 'Join waiting list', 4);`

2021-09-14 19:28 UTC, jimchamp approved these changes
Lgtm!  This should make it easier to add controls later.  Thanks for working on this!

2021-09-14 19:28 UTC, merged