fix(SearchResultsWork): Limit displayed authors to 9
internetarchive/openlibrary pull request #5714
Opened 2021-10-02 19:30 UTC by shaneriley

Closes #5630 

Fixes long lists of authors for SearchResultsWork by slicing first 9 authors off authors array and rendering a small "view all authors" message when the authors array exceeds 9.

### Technical

The `max_rendered_authors` is defined at the beginning of the template partial, in the event we feel the max should be changed.

### Testing

1. Search for a work title whose author list exceeds 9 (you may need to edit a work locally and add authors in order to achieve this)
2. The search result for the work should show the first 9 authors and a "view all authors" link to the work's show page
3. Click the "view all authors" link
4. From the work show page, click the first author in the list
5. The author show page should display the work with the author list truncated to 9 and the same "view all authors" link should be rendered.

### Screenshot

![localhost_8080_search_q=blackout mode=everything](https://user-images.githubusercontent.com/39553/135729628-a0834d55-9be0-4139-bab0-d0778a7c3426.png)

![localhost_8080_authors_OL7531052A_Dhonielle_Clayton](https://user-images.githubusercontent.com/39553/135729632-fdc28761-3c5f-4365-a789-4d38a33281ad.png)

### Stakeholders

@jimchamp

2021-10-05 21:52 UTC, cdrini requested changes
Nice, thanks @shaneriley ! I tossed this on testing.openlibrary.org for testing: https://testing.openlibrary.org/authors/OL60550A/Olaudah_Equiano?q=Prentice+Hall+Literature

Could we make this say "and 6 others" instead? I think that provides a bit more info :) You'll need to use this translation syntax:

```
$ungettext("and 1 other", "and %d others", num, num)
```

Also, there should be a comma after the last author name, here: 
![image](https://user-images.githubusercontent.com/6251786/136107568-e6eb7f1f-156b-4a42-ba40-0833c6a84c71.png)

2021-10-05 21:52 UTC, cdrini commented
Oh my goodness, I just noticed your test authors 😂

2021-10-05 21:53 UTC, cdrini commented
(oh, also cc @RayBB , if you want to try it out to see if this looks good to you :) )

2021-10-15 09:54 UTC, shaneriley commented
@cdrini Adding an `ungettext` call in the format you specified throws an error when the value passed in for parameters 3 and 4 are both 1. If I drop parameter 4, it returns the correct value when parameter 3 is `1`. For all other values, I need to pass the same number into parameter 4 to use the second, pluralized string. The error rendered is
```
/openlibrary/openlibrary/templates/work_search.html: error in processing template: TypeError: not all arguments converted during string formatting (falling back to default template)
```

2021-10-20 21:44 UTC, cdrini commented
Need to take this off testing.openlibrary.org since its conflicting with another PR; please feel free to add it back once its ready for the last pass!

2021-10-30 15:59 UTC, cdrini commented
Hey! Sorry for the delay on this one 😬 Hopefully it's not too late for you to register for Hacktoberfest! This will be merged in <1h.

2021-10-30 16:16 UTC, cdrini approved these changes
Lgtm! Checked:

- https://testing.openlibrary.org/authors/OL396367A/Joni_Mitchell
- https://testing.openlibrary.org/authors/OL60550A/Olaudah_Equiano?q=Prentice+Hall+Literature

2021-10-30 16:16 UTC, merged