pyupgrade + black code
internetarchive/openlibrary pull request #5855
Opened 2021-11-10 22:54 UTC by jimman2003

Progress towards #4776 

### Technical

### Testing

### Screenshot

### Stakeholders

@cclauss

2021-11-10 23:12 UTC, cclauss commented
Failing tests are like #5853

2021-11-11 00:26 UTC, cdrini commented
Can we not merge until #5777 lands ? The rebase will be a nightmare :P Should be merged tomorrow :+1:

2021-11-11 00:29 UTC, cdrini commented
After that's merged, you'll have to regenerate the `SolrDocument` : `./openlibrary/solr/types_generator.py > ./openlibrary/solr/solr_types.py` .

2021-11-11 11:21 UTC, cclauss commented
Converted to DRAFT until #5777 lands.

2021-11-12 00:18 UTC, cdrini commented
#5777 has landed :+1:

2021-11-12 08:50 UTC, jimman2003 commented
rebase,add solr-types done

2021-11-13 16:24 UTC, cclauss commented
Converted to DRAFT again because tests are still failing.  I cannot understand the failure.

2021-11-13 18:31 UTC, RayBB commented
This is a weird one for sure. Is anyone able to reproduce it locally? I tried without luck. 

May be worth separating pyupgrade, black,  and codespell into different PRs to isolate the issue.

2021-11-13 18:33 UTC, jimman2003 commented
Actually I included cclauss's pr about solr types , as I had the error it was trying to solve..

2021-11-13 22:15 UTC, cclauss requested changes
requests params are a dict of key / value pairs.

2021-11-13 22:15 UTC, cclauss commented on openlibrary/solr/update_work.py
>  import datetime
```suggestion
from __future__ import annotations

import datetime
```

2021-11-13 22:15 UTC, cclauss commented on openlibrary/solr/update_work.py
> +        ]
```suggestion
        params={
            'wt': 'json',
            'json.nl': 'arrarr',
            'q': 'author_key:%s' % author_id,
            'sort': 'edition_count desc',
            'row': 1,
            'fl': 'title,subtitle',
            'facet': 'true',
            'facet.mincount': 1,
        }
```

2021-11-14 17:44 UTC, cclauss approved these changes
LGTM.  Thanks much!!

2021-11-14 17:45 UTC, merged