fix(#5982) - Fixes pointer and width for the logout button
internetarchive/openlibrary pull request #5983
Opened 2021-12-16 22:32 UTC by Azazel5

- Will be able to logout properly after clicking

Closes #5982 

Fixes the logout button on the dropdown menu: makes the pointer cursor on hover and increases the width of the button
to actually logout on click.

### Technical
Gave the form and button cursor: pointer; attributes and increased the width of the button to 100% of its parent (form).

### Testing
Test by logging into openlibrary and hovering on the logout button/clicking it to make sure it logs out.

### Screenshot
<img width="1205" alt="proof" src="https://user-images.githubusercontent.com/36729591/146458827-f3fc1cd0-d882-4dd0-a9a7-d022e15de26a.png">

### Stakeholders

2021-12-20 18:57 UTC, jimchamp requested changes

2021-12-20 18:57 UTC, jimchamp commented on static/css/components/header-bar.less
> +
```suggestion
```
It looks like this is handled by the `cursor` rule that you've added to the button.

2021-12-30 08:13 UTC, omduragkar commented
Can I work on it please would love to work on it.
Thanks

2022-01-05 17:24 UTC, jimchamp approved these changes
Lgtm!

2022-01-05 17:24 UTC, merged