Tuminzee patch
internetarchive/openlibrary pull request #5988
Opened 2021-12-17 22:49 UTC by tuminzee

Closes #5979

#### Enhance user experience/engagement  on `/account/loans` page, 
If a patron has currently has no loans, display the following on the loans page:

- "Books We Love" carousel  [because of failure of creating the book we love carousel, instead I have replace it with 'Classic Books Carousel]
- "Browse by Subject" carousel
- link to our collections page (https://openlibrary.org/collections)

### Technical

1. Add boolean paramater <compact_mode> to custom_ia_carousel, custom_carousel template which will determine the breaking behaviour
1.2 Set breaking [a:f] pareters [4, 4, 4, 3, 2, 1]for the compact design
2. Make css changes in mybooks-details.less to make my loan page's carousel's responsive
3. Add action button to my loan's page which redirects to collections page

### Testing

1. Go to /accounts/loan 
2. DevTools Responsive Breakpoints

### Screenshot

![01](https://user-images.githubusercontent.com/58180803/146615913-69f70e14-822b-42f9-a336-b3be3fc7fb68.png)
![02](https://user-images.githubusercontent.com/58180803/146615917-2e7b4ee3-3b3e-4cc6-b5e7-1b426dc64fd6.png)
![03](https://user-images.githubusercontent.com/58180803/146615918-6f7806b4-dbcf-422e-9d20-7ec0c537d630.png)
![04](https://user-images.githubusercontent.com/58180803/146615923-1dcb73f3-55de-4c46-b1e2-4ef3ff287993.png)
![05](https://user-images.githubusercontent.com/58180803/146615925-7edb6c80-a44e-443d-806e-fd8a24dd6d4d.png)
![06](https://user-images.githubusercontent.com/58180803/146615929-9fede384-8bf9-4e97-9a0a-35b3735e82a9.png)

### Stakeholders

@jimchamp

2021-12-17 22:54 UTC, tuminzee commented
@cclauss I am super happy. I was able to pass the GitHub actions tests.
Although I tested the code locally, I was still unsure.

Thank you for the lesson.
I hope you have a good day 😄

2021-12-17 22:57 UTC, tuminzee commented
@jimchamp This issue helped a lot to learn about the codebase. Thank you for assigning this 🕺🏼 
Thank you for being patient with me. Learnt a lot.
Looking forward to contributing more 

Please let me know if you are not satisfied with the PR. I I will make the necessary changes.

2021-12-21 22:34 UTC, jimchamp requested changes
Thanks for your patience as well, @tuminzee!  Just a few small changes are needed.  Afterwards, I'll put this on testing in order to ensure that the staff favorites carousel is rendering as expected.

2021-12-21 22:34 UTC, jimchamp commented on openlibrary/templates/account/loans.html
> +    $:render_template("books/custom_carousel", books=readonline_carousel(), title=_('Classic Books'), url="/read", key="public_domain", test=test, compact_mode=True)
```suggestion
    <div>Looking for a book to borrow?  Check out our staff picks, or search for a book on a specific category:</div>
     $:render_template("home/custom_ia_carousel", title=_('Books We Love'), key="staff_picks", query='languageSorter:("English")', subject="openlibrary_staff_picks", sorts=["lending___last_browse desc"], limit=18, test=test, compact_mode=True)
```
I think that this is missing a call to action.  Let's add that before any of the carousels.  You may want to add a bit of space between the "You've not checked out any books at this moment." message and the call to action (unless you think that it looks good).

Although we can't easily test the "Books We Love" carousel locally, we can test this by deploying to https://testing.openlibrary.org.  Let's try replacing the "Classic Books" carousel with the "Books We Love" carousel.  Once that change has been made, I'll deploy this branch to testing.

2021-12-21 22:34 UTC, jimchamp commented on openlibrary/templates/account/loans.html
> +    Check out our <a href="/collections">special collections</a>
```suggestion
    Or, check out our <a href="/collections">special collections</a>.
```
Adding "Or" to the beginning of this sentence makes more sense with the call to action.

2021-12-22 15:16 UTC, tuminzee commented
I have made the changes, please have a look.
Thank you for your time 😄

2021-12-23 19:46 UTC, jimchamp commented
This is up on testing now, and it's looking pretty good:

![Screenshot from 2021-12-23 14-45-17](https://user-images.githubusercontent.com/28732543/147285641-0d55ea8f-495b-4d69-ae4f-023561647bed.png)

2021-12-23 20:00 UTC, tuminzee commented
This looks great. Thank you for all the help.
I wish this makes it to the main branch 🤞🏼

2021-12-23 20:11 UTC, jimchamp commented
I'm going to make a small change to the copy, and merge everything now.

2021-12-23 20:12 UTC, jimchamp commented on openlibrary/templates/account/loans.html
> +    <div>Looking for a book to borrow?  Check out our staff picks, or search for a book on a specific category:</div>
```suggestion
    <br>
    <div>Looking for a book to borrow?  Check out our staff picks, or search for a book on a specific subject:</div>
```

2021-12-23 20:13 UTC, jimchamp approved these changes
Lgtm!  Thanks @tuminzee!

2021-12-23 20:15 UTC, merged

2021-12-23 20:38 UTC, tuminzee commented
PR merged 🎉 🕺🏼 
Thank you @jimchamp