replacing civicrm call with elastic
internetarchive/openlibrary pull request #6013
Opened 2021-12-25 23:49 UTC by mekarpeles

Closes #5801

Replaces CiviCRM call w/ Archive.org ElasticSearch queries (less reliance on additional services)

### Technical

### Testing

http://ol-dev1.us.archive.org:1337/people/mekBot/books/sponsorships

### Screenshot

When
![ol-dev1 us archive org_1337_people_mekBot_books_sponsorships](https://user-images.githubusercontent.com/978325/147395635-7bde3591-d4ce-4b5a-8499-6bcb98b04799.png)
 on `sponsorships` tab

When not on `sponsorships` tab
![ol-dev1 us archive org_1337_people_mekBot_books_currently-reading](https://user-images.githubusercontent.com/978325/147395634-9ac17ed2-5e1c-407a-a0a8-c1cff78b49bb.png)

### Stakeholders

2021-12-27 23:03 UTC, jimchamp commented on openlibrary/core/sponsorships.py
> +    return {}
```suggestion
    return []
```

2021-12-27 23:18 UTC, jimchamp commented on openlibrary/plugins/upstream/mybooks.py
> +                )
```suggestion
                ) if sponsorships else None
```
We redirect to `/people/{username}` when `data == None` at the end of this method.

If we send an empty list when a patron has no sponsorships, they can still navigate to the sponsorship page using their browser's address bar.

2021-12-27 23:18 UTC, jimchamp commented on openlibrary/plugins/upstream/mybooks.py
> -        if sponsorships:
Named argument `sponsorships` can also be removed from this method.

2021-12-27 23:20 UTC, jimchamp commented on openlibrary/core/sponsorships.py
> +    return {}
If I'm wrong about this one, please add a test case for missing `archive_id`'s.

2021-12-27 23:23 UTC, jimchamp requested changes
This should be good after the review notes are implemented.  Will attempt to put this on testing when the new commit has been pushed.

2021-12-28 04:57 UTC, mekarpeles commented
All feedback should be addressed and the feature can be tested on http://ol-dev1.us.archive.org:1337

2021-12-28 17:46 UTC, jimchamp commented on openlibrary/core/sponsorships.py
> +    return {}
```suggestion
    return []
```
Not sure how I missed this one...

2021-12-28 22:08 UTC, merged