Fixed editions table on books pages contains link to current page
internetarchive/openlibrary pull request #6045
Opened 2022-01-10 08:26 UTC by Hitansh-Shah

Signed-off-by: Hitansh Shah <shah.hitanshsanjay.mat20@itbhu.ac.in>

Closes #6040 

On books page it removes the link of the current page from editions table

### Technical

The changes were made solely in [editions_database.html](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/type/work/editions_datatable.html). I changed the conditional statements inside the for loop for rendering template. I also declared a new variable `render_first_flag` with default value of `1` which decides when to render with `render_first=True` argument in `render_template` function. The variable helps to differentiate between the case where the already displayed edition appears in first iteration of for loop and the case where it does not.

### Testing

1. Go to https://openlibrary.org/books/OL7824010M/Where_the_Red_Fern_Grows or any other book (with multiple editions) page.
2. Check that the editions table does not contain the editions which is already displayed

### Screenshot

**Before:** 
![image](https://user-images.githubusercontent.com/76250591/148735711-51898cac-16c6-40e4-a11e-f13602ad64b3.png)

**After:**
![image](https://user-images.githubusercontent.com/76250591/148735825-63a70ea9-7b35-4162-9591-571e6506f399.png)

### Stakeholders

2022-01-10 08:29 UTC, Hitansh-Shah commented
@jimchamp Please review the PR

2022-01-12 01:31 UTC, jimchamp requested changes
Thanks @Hitansh-Shah!

I may have documented the issue incorrectly.  We don't want to display the selected item in the table at all, as it references the page that the user is currently viewing (i.e. clicking on the link in this row will reload the page).

2022-01-12 01:31 UTC, jimchamp commented on openlibrary/templates/type/work/editions_datatable.html
> +                </tr>
```suggestion
            $if book.key != edition.key:
              <tr>
                $:render_template("books/edition-sort", book, edition_sort_key)
              </tr>
```
No need to render the row corresponding to the page that is being viewed.

2022-01-12 01:31 UTC, jimchamp commented on openlibrary/templates/type/work/editions_datatable.html
> +        $ render_first_flag = 1
```suggestion
```

2022-01-12 04:56 UTC, Hitansh-Shah commented
@jimchamp Thanks for reviewing. So I was a little confused about `render_first=True` argument but I guess that is not needed at all now. I will update the changes. Thanks😄

2022-01-14 16:26 UTC, Hitansh-Shah commented
@jimchamp  I have made the changes you suggested. Please review it :)

2022-02-01 17:49 UTC, jimchamp commented
Thanks @Hitansh-Shah!  Unfortunately, I've led you astray.  It looks like we don't have consensus on removing the first editions table entry --- I thought that we did...

Closing this for now, but we may decide to merge it after some more internal discussion about the editions table.

2022-02-01 17:49 UTC, closed without merging