Fix sign up page email and screen name input size
internetarchive/openlibrary pull request #6086
Opened 2022-01-29 18:58 UTC by jollypolly123

Closes #6011

hotfix

### Technical

Original implementation selected the incorrect input type (email) instead of text for email address and screen name fields on the signup page.

### Testing

Navigate to /account/create

### Screenshot

![image](https://user-images.githubusercontent.com/46527761/151673955-0e6214ce-b472-44c9-b2e7-e039c5db24e8.png)

### Stakeholders

2022-02-02 00:24 UTC, mekarpeles commented
Hi @jollypolly123! Thank you for submitting this fix!

@jimchamp I also wanted to note the solution here as it may be equally simple and be an approach we may wish to evaluate.
https://github.com/internetarchive/openlibrary/issues/6011#issuecomment-1013672237

Thank you both!

2022-02-14 15:08 UTC, jimchamp requested changes
Happy to merge this when the requested changes have been made.

2022-02-14 15:08 UTC, jimchamp commented on static/css/components/form.olform.less
>    .required {
```suggestion
  .required {
```
Removing the input selectors solves this issue, and doesn't resize other fields in other views.

2022-02-14 18:03 UTC, jimchamp approved these changes
Lgtm!  Thanks, @jollypolly123!  Will merge when the checks pass.

2022-02-14 18:14 UTC, merged