Make table of contents collapsible
internetarchive/openlibrary pull request #6321
Opened 2022-03-21 20:51 UTC by jimchamp

Closes #6171

Add "Read more" link below tables of content found on books pages.

### Technical

Added some `div`s to the table of contents template in order to satisfy class naming conventions used by the read more JS.

### Testing

### Screenshot

![toc_collapse](https://user-images.githubusercontent.com/28732543/159361710-d98023fe-6a75-4bbc-b911-38573992282c.gif)

### Stakeholders

2022-03-28 19:35 UTC, mekarpeles commented
cc @seabelis who I believe may have a preference for showing whole TOC (I understand we may go in the direction of hide by default or at least have a hide option).

2022-05-27 22:01 UTC, cdrini requested changes
This should show _way_ more of the table of contents ; can we configure it to show like ~300px ? Or maybe only apply the collapsibility to the actual table, not the header/etc?

2022-05-27 22:01 UTC, cdrini commented on openlibrary/macros/TableOfContents.html
> +      <div class="toc-content restricted-view">
Can we combine any of these elements? This is getting quite nested!

2023-10-19 16:15 UTC, cdrini commented
Closing in favour of #8438

2023-10-19 16:15 UTC, closed without merging