Render edition lists only on edition pages
internetarchive/openlibrary pull request #6341
Opened 2022-03-29 16:59 UTC by jimchamp

The books page "Lists containing this Book" section typically has two rows: The first displays lists that contain the work; the second, lists containing the editions.  On work pages, both of the rows are the same.

This PR removes the edition lists from work pages.

### Technical

### Testing

### Screenshot

### Stakeholders

2022-03-29 21:42 UTC, mekarpeles commented
We may have to be careful with this one because even on the work page we can still have an edition selected.

I think we specifically care about the case where we're on a work page and there's no edition (i.e. when we set `edition = edition or page` the case where `edition == page`).

So maybe the logic can be if the `edition.type` is type work, then we know not only are we on the work page, but there's also no edition.

2022-03-29 21:43 UTC, mekarpeles requested changes
We may have to be careful with this one because even on the work page we can still have an edition selected.

I think we specifically care about the case where we're on a work page and there's no edition (i.e. when we set `edition = edition or page` the case where `edition == page`).

So maybe the logic can be if the `edition.type` is type work, then we know not only are we on the work page, but there's also no edition.

2022-03-29 22:48 UTC, jimchamp commented
That seems to have worked.  Here are screenshots with their source URLs:

__Current Production:__

![prod_two_cities](https://user-images.githubusercontent.com/28732543/160719012-ee46a99a-e0e2-4766-98ca-ffbf59489120.png)

https://openlibrary.org/works/OL8721465W/A_Tale_of_Two_Cities?mode=all

---

__This Branch:__

![testing_two_cities](https://user-images.githubusercontent.com/28732543/160719145-c5fa4175-9bde-4b10-943e-546950c2b65f.png)

https://testing.openlibrary.org/works/OL8721465W/A_Tale_of_Two_Cities?mode=all

2022-03-30 16:34 UTC, mekarpeles approved these changes

2022-03-31 15:48 UTC, merged