combine waitlist and checked out pages
internetarchive/openlibrary pull request #6487
Opened 2022-04-26 04:48 UTC by tangym27

Closes #6438 

From the issue:
- [x]  /account/loans should render the waitlist items
- [x]  /account/waitlist should redirect to /account/loans
- [x]  Remove the "Waitlist" link from the sidebar
- [x]  Rename "Checked out" to "Loans"

### Technical

- contents of `waitlist.html` is now in the `details-content` subsection of `loans.html`
### Testing

### Screenshot

<img width="958" alt="image" src="https://user-images.githubusercontent.com/34128141/165221245-e94fdb8f-b117-451b-992c-f986599e2be5.png">

### Stakeholders

@jimchamp

2022-04-26 04:49 UTC, tangym27 commented on openlibrary/templates/account/loans.html
> +}
Used to match the header of `Books You've Checked Out`

2022-04-26 18:31 UTC, mekarpeles commented
@jimchamp  + @tangym27 + @cdrini do you think we might want the sidebar label to be "Loans & Waitlists"? Or do we predict people will know that Waitlists have moved to Loans?

2022-04-26 20:20 UTC, cdrini requested changes
Nice! Looks good, @tangym27 :) A few small cleanups!

I was able to test the loans page functions correctly; couldn't find a waitlist item to test on :P Will test later.

2022-04-26 20:26 UTC, cdrini commented
@mekarpeles I think it'll be sufficiently discoverable; Having a single page dashboard will be a +1 (Note waitlist is 30th on our most visited GA pages).

2022-04-26 20:34 UTC, cdrini commented
@tangym27 And some UX tweaks:

- Can you move the "Looking for a book to borrow" section to the bottom, after the waitlist? So something like this.
![image](https://user-images.githubusercontent.com/6251786/165386964-88269478-82e9-4a64-9406-d79a959d7b03.png)

- The "Loans" section looks kind of funny; can you combine the two sections? Ie something like:
![image](https://user-images.githubusercontent.com/6251786/165387379-77ff954b-8147-4236-ac2d-a4e43e3e7d12.png)

2022-04-29 19:34 UTC, tangym27 commented on openlibrary/templates/account/books.html
> +      $:render_template('account/loans', logged_in_user, items)
oh, this is actually really nice to learn about. I saw that there was a `waitlist` key in `mybooks.py` that seemed separate from the `waitlist` key in `books.html` so I didn't want to accidentally remove the one used within `mybooks.py`. thanks!

2022-05-05 01:17 UTC, cdrini approved these changes
Oh sorry for the delay! Missed the update on this one :) This looks great! I can't find a way to test waitlisted books right now, so I'll keep an eye out for any user reports if something's not working :+1: Thank you @tangym27 !

2022-05-05 01:17 UTC, merged