search navigation
internetarchive/openlibrary pull request #6688
Opened 2022-06-26 02:48 UTC by mekarpeles

This meant to be an absolute minimal PR of adding Book Page style navigation tabs to Search Results

Closes #6542 

## Details

* Lists & Subjects are intentionally omitted from this 1st step because their experience doesn't feel ready -- patrons can still get to this in the same way (through the Browse menu and the main search).
* Google analytics has been added to see if anyone clicks "Quotes" (i.e. fulltext search, named according to Goodreads); see:
* `hits` has been moved consistently below the search box (and the green has been removed)
* Author results have been standardized using the Books format and author covers/imgs have been added. Bullet styles and anchor tags have been standardized across Author and Books results.

![www goodreads com_search_q=to+be+or+not+to+be qid=](https://user-images.githubusercontent.com/978325/175796328-df1f2cbc-635a-4600-b960-c03a74ff4f9a.png)

## Screenshots

**Books**

![ol-dev1 us archive org_1337_search_q=jk%20rowling (1)](https://user-images.githubusercontent.com/978325/175797155-a2149ef1-adce-4d6d-911a-7ecfb4504536.png)

**Authors**

![ol-dev1 us archive org_1337_search_authors_q=jk%20rowling](https://user-images.githubusercontent.com/978325/175797073-669877e0-406b-4ee0-adc1-5d25c0f8d66a.png)

**Quotes**

![ol-dev1 us archive org_1337_search_inside_q=jk%20rowling](https://user-images.githubusercontent.com/978325/175797180-bf338f0c-a18b-4f40-8809-f3dbb4aba082.png)

**Advanced Search**

![ol-dev1 us archive org_1337_advancedsearch](https://user-images.githubusercontent.com/978325/175797204-ae405582-c417-4a91-99cf-5bf6f3f21b88.png)

2022-07-05 15:29 UTC, mekarpeles commented on openlibrary/macros/SearchNavigation.html
> +       href="/search/inside?q=$(q)">$_("Quotes")</a>
```suggestion
       href="/search/inside?q=$(q)">$_("Search Inside")</a>
```

2022-07-05 15:29 UTC, mekarpeles commented on openlibrary/templates/search/inside.html
> +  <h1>$_("Search Quotes")</h1>
```suggestion
  <h1>$_("Search Inside")</h1>
```

2022-07-06 16:09 UTC, cdrini requested changes
Nice! This looks great, and will make it much easier to search! A few changes for you. Happy to discuss on any of the design issues or get further feedback.

Other:
- ❗ Also note that on testing the sorting options are no longer visible.
- Make the tab bar full width and horizontally scrollable; not sure what css is missing there.

2022-07-06 19:40 UTC, mekarpeles commented on openlibrary/templates/search/authors.html
> +	      <img src="https://covers.openlibrary.org/a/olid/$(doc['key'])-M.jpg" itemprop="image" class="cover" alt="Photo of J. K. Rowling">
ty

2022-07-06 19:41 UTC, mekarpeles commented on openlibrary/templates/search/subjects.html
> +        <p class="sansserif collapse"><strong>$ungettext('1 hit', '%(count)s hits', response['numFound'], count=commify(response['numFound']))</strong></p>
I agree they look a little broken but I don't think the green communicates anything meaningful and I think having additional colors without intent (just for aesthetic reasons) is worse than just going through later and fixing them to be more consistent.

2022-07-06 19:44 UTC, mekarpeles commented on openlibrary/templates/search/advancedsearch.html
> +
In this case it is duplicated but 
1. goodreads includes the title
2. https://openlibrary.org/search is currently confusing without a label
3. https://openlibrary.org/search/authors already includes a label

so I think it's not unreasonable to consistently use the labels in addition to the menu. I'm not opposed to us removing them if we do a simple test with a user and confirm they easily know what page they're on. No point taking up more space if it's not necessary.

2022-07-08 00:22 UTC, mekarpeles commented on openlibrary/templates/search/authors.html
> +	      <img src="https://covers.openlibrary.org/a/olid/$(doc['key'])-M.jpg" itemprop="image" class="cover" alt="Photo of J. K. Rowling">
done

2022-07-08 00:51 UTC, mekarpeles commented on openlibrary/templates/search/authors.html
> +	      <img src="https://covers.openlibrary.org/a/olid/$(doc['key'])-M.jpg" itemprop="image" class="cover" alt="Photo of J. K. Rowling">
resolved

2022-07-08 16:56 UTC, jimchamp commented on openlibrary/macros/SearchNavigation.html
> +<ul class="work-menu">
```suggestion
<ul class="nav-bar">
```
We initialize the book page sticky title on pages where `.work-menu` is found.  As such, errors are appearing in the JS console for these search results pages.

The `nav-bar` class was added in #6665 to circumvent this problem.

2022-07-08 17:38 UTC, jimchamp requested changes
This seems pretty good!
One thing that could be improved is the alignment of elements on the author results page:
![authors_navbar_left_align](https://user-images.githubusercontent.com/28732543/178041475-99f6d75b-7469-4e0d-bb35-a118529b4139.png)

A `10px` adjustment should be all that is needed here.

There should probably be a little space between the input and the lists search results, as well:

![Screenshot from 2022-07-08 13-31-18](https://user-images.githubusercontent.com/28732543/178042452-dc0dfbaa-7e5e-47ab-b999-f3a181ebe775.png)

Please double-check the layouts for search inside and subject search pages.  I'm not getting results locally, and it times out when I try to check on your VM.

2022-07-10 19:26 UTC, mekarpeles commented
@jimchamp brought up a few aesthetic changes which I think we should absolutely do as a good-first-issue followup. I'll create an issue for this as a P2. For now, I think all other blocking feedback (including some of these design improvements) have been implemented. Some are scatted across the different experiences and require a bit more attention. Merging for now.

2022-07-10 19:26 UTC, merged