fixing logic for sponsor btn
internetarchive/openlibrary pull request #6691
Opened 2022-06-27 00:40 UTC by mekarpeles

Minimal fix -- sometimes the sponsorship criteria would pass the first `if` statement, enter the `if` body and then fail the second condition, and in this case no btn would render (when really we wanted to show e.g. `Not in Library`). This combines the `if` statements so we check one condition. The sponsorship_url is no longer needed since clicking "donate" not pops up a modal instead of redirecting to archive.org sponsorship.

### Stakeholders

2022-06-28 18:31 UTC, jimchamp commented on openlibrary/macros/LoanStatus.html
> +    <a class="cta-btn cta-btn--sponsor dialog--open"
```suggestion
    <a class="cta-btn cta-btn--shell cta-btn--sponsor dialog--open"
```
Button CTA unreadable without `cta-btn--shell` class:

![Screenshot from 2022-06-28 14-27-57](https://user-images.githubusercontent.com/28732543/176256620-619658c5-4f8a-448e-ae7a-512541a7a90e.png)

2022-06-28 18:35 UTC, jimchamp requested changes
Adding the missing class solves the readability issue.
I'm noticing that the modal content may not be present on the homepage (and maybe other places):

![no_modal_content_on_homepage](https://user-images.githubusercontent.com/28732543/176256980-7d5ed759-6b77-456f-a060-d00bb5fe3c0f.gif)

__Edit:__ This might be a little tricky.  When a donate button is clicked, the content displayed in the modal will have an `id` equal to the value set in the button's `aria-controls` attribute (`seeDonate` for these buttons --- [see this comment](https://github.com/internetarchive/openlibrary/blob/ccf1024667a27cf95193ccd08785dcb8e1676ba9/openlibrary/plugins/openlibrary/js/dialog.js#L67-L72)).

I can think of two fixes:
1. We modify [DonateModal.html](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/DonateModal.html) to except the `id` as a parameter, and add separate uniquely identified `DonateModal`s for each button.
2. We add a single `DonateModal` to each page that needs it, and dynamically update work-specific information in the component before the modal is opened.

2022-06-29 19:13 UTC, mekarpeles commented on openlibrary/macros/LoanStatus.html
> +$elif ('eligibility' in doc) or (check_sponsorship and not ocaid and qualifies_for_sponsorship(doc, donate_only=True).get('is_eligible')):
This likely needs to be updated to `'eligibility' in doc and not ocaid` and we may also want to consider doing this if and only if `not secondary_action`

2022-07-11 21:19 UTC, mekarpeles commented on openlibrary/macros/LoanStatus.html
> +$elif ('eligibility' in doc) or (check_sponsorship and not ocaid and qualifies_for_sponsorship(doc, donate_only=True).get('is_eligible')):
```suggestion
$elif not ocaid and ('eligibility' in doc or (check_sponsorship and qualifies_for_sponsorship(doc, donate_only=True).get('is_eligible'))):
```

2022-09-02 23:14 UTC, jimchamp commented
Removed from testing in order to test #6929

2022-09-02 23:56 UTC, jimchamp commented
This was causing some false positives in the homepage carousels.  Print disabled books were appearing with a "Donate" button on the homepage, but a "Not in Library" button on the book page.  In `debug` mode, the availability for these books is an empty `dict`.

2022-09-06 21:50 UTC, mekarpeles commented
Review #6929, assuming this one can be closed in favor of that one

2022-09-06 21:50 UTC, closed without merging