Work Merge Undo
internetarchive/openlibrary pull request #6948
Opened 2022-09-09 00:56 UTC by mheiman

Closes #6774 

This PR implements a work merge undo interface in parallel with the author merge undo.

### Technical
This is largely a copy of the author merge undo interface, though some changes were required to utils.js in the MergeUI in order to pass the metadata needed by the recentchanges interface.

It also relies on a change to infogami/plugins/api/code.py that allows it to accept and pass the save_many data parameter. That will be a separate Infogami PR.

Finally, this PR tweaks the position and appearance of the Undo All button to make it consistent with the other buttons that appear in the header (e.g. Edit) because it was annoying as it was.

### Testing
Do a work merge, find it in recent changes, and undo it.

### Screenshot
<img width="1126" alt="Screen Shot 2022-09-08 at 7 53 28 PM" src="https://user-images.githubusercontent.com/886889/189250191-9c69199f-192e-491e-8d69-fc1931f8e179.png">

### Stakeholders
@mheiman @cdrini

2022-11-16 17:38 UTC, cdrini requested changes
Did some tests and things are looking good! A few code recs :) Thanks for you patience, Mark!

2022-11-16 17:38 UTC, cdrini commented on openlibrary/templates/recentchanges/merge-works/comment.html
> +$def with (change, page=None)
If we could DRY these templates, I think that would be nice, since they are very similar

2022-11-16 17:46 UTC, cdrini commented on static/css/components/edit-toolbar--tablet.less
> +  button {
Fixed in #7159 ! Can roll back these changes now.

2022-12-06 20:03 UTC, mheiman commented
Notes on the latest set of changes:

1. Having all merge-* changes use one set of templates ended up requiring the same branching code ("If this is a merge-* change...") in at least four different places. Not entirely DRY, but maybe better than the alternative?

2. The templates/recentchanges/merge/comment.html template has a nice feature such that when it's called from an item page it would provide a more descriptive comment (e.g. "Merged 5 duplicate records into this primary") plus a "See details" link to view the entire change. However, once you click through to view that change, you lose the nice descriptive comments, because the page context no longer exists.

    I added some complexity to comment.html to allow the recent changes view to pass a context that allows these descriptive comments to work everywhere. It means you can either pass the template a page object or just a plain key string, and it will do the right thing (including not showing "See details" if you're already there).

Before:
<img width="755" alt="Screenshot 2022-12-06 at 1 54 16 PM" src="https://user-images.githubusercontent.com/886889/206009529-c7ae8def-0541-4974-b05d-201564c9dd46.png">
After:
<img width="754" alt="Screenshot 2022-12-06 at 1 53 14 PM" src="https://user-images.githubusercontent.com/886889/206009557-f21edd4d-7f3a-4535-a2f4-b42ebe7ded51.png">


The template only needs the key (which it reads from the page object), so an alternative implementation would be to make a change further upstream so that the item pages just pass along their key (instead of the page object), and comments.html would then have a cleaner interface. In that case, we'd also need to query the URL context to know whether to display the "See details" link.  Lose some complexity on one place, gain it in another.

2023-01-06 22:49 UTC, cdrini approved these changes
Ok was having trouble testing the work merge page locally but it works like a charm on testing! This is sooooo useful!!! 😊

2023-01-06 22:51 UTC, merged