7007: moves book description above omnibar
internetarchive/openlibrary pull request #7165
Opened 2022-11-17 22:37 UTC by jpdh9881

Closes #7007 

feature

### Technical

- verified on Firefox + Chrome
- edit-toolbar styles: copied tablet breakpoint to a new desktop breakpoint and modified tablet breakpoint (to solve issue where edit-toolbar would share space with book description at tablet sizes)

### Testing

Look at work description on book page at all breakpoints

### Screenshot

Desktop
![image](https://user-images.githubusercontent.com/54423825/202572682-39f89401-f449-462c-938f-cec1a78ab3a4.png)
![image](https://user-images.githubusercontent.com/54423825/202572747-f128ef3e-004c-4417-969d-6fe41f52d26d.png)

Tablet
![image](https://user-images.githubusercontent.com/54423825/202572874-97d0f05a-5002-42d2-b647-5320d99a6ce0.png)

Mobile
![image](https://user-images.githubusercontent.com/54423825/202572981-4fd9087e-150b-4df8-8d26-2d86310cd033.png)

### Stakeholders

@jimchamp

2022-11-17 23:22 UTC, mekarpeles commented
I think this is very close! @jimchamp do we want the description below the navigation bar?

2022-11-18 00:18 UTC, jimchamp commented
Once all of the books page issues have been addressed, the navbar should be at the top of the page.  We may want to merge this and the other book page PRs into an integration branch, then merge that branch into main when enough of the issues have been addressed.

2022-11-19 01:38 UTC, jimchamp commented
It looks like the edit component layout changes have affected many other pages negatively:
![Screenshot from 2022-11-18 17-33-35](https://user-images.githubusercontent.com/28732543/202827877-9686b316-0967-4cc5-8c12-bcf1b299ca3e.png)
_Author edit page_

![Screenshot from 2022-11-18 17-34-20](https://user-images.githubusercontent.com/28732543/202827881-a3a08d75-5262-4a54-b64b-6805c5a3b6d1.png)
_Author page_

![Screenshot from 2022-11-18 17-33-49](https://user-images.githubusercontent.com/28732543/202827885-536dd5d1-e52d-4ecb-910f-f5592cfca130.png)
_Edit history page_

Suggest undoing all changes unrelated to the book description (`.book-description`) and the "Read More" buttons, and clearing the float on the book description for tablet views.

2022-11-19 01:52 UTC, jimchamp requested changes
Implementing the suggested changes should correct the layout issue for tablets without affecting other pages.

2022-11-19 01:52 UTC, jimchamp commented on static/css/components/edit-toolbar--desktop.less
> +}
```suggestion
```
Remove this file, as edit component layout changes are unnecessary.

2022-11-19 01:52 UTC, jimchamp commented on static/css/components/edit-toolbar--tablet.less
> +
```suggestion
```

2022-11-19 01:52 UTC, jimchamp commented on static/css/components/edit-toolbar--tablet.less
> +  display: flex;
```suggestion
```
Remove `display: flex` and add `float: right` beneath the padding (revert to original styling).

2022-11-19 01:52 UTC, jimchamp commented on static/css/components/edit-toolbar--tablet.less
> -  float: right;
This float is needed.

2022-11-19 01:52 UTC, jimchamp commented on static/css/components/work--tablet.less
> -    margin-bottom: 1.5em;
Don't remove this margin.

2022-11-19 01:52 UTC, jimchamp commented on static/css/components/work--tablet.less
>    &About {
```suggestion
  &About {
    .book-description {
      clear: both;
    }
```
Adding the clear here will prevent the layout issue in tablet views.  Please add this below the `margin-top` rule on the next line.

2022-11-19 01:52 UTC, jimchamp commented on static/css/page-book.less
> +@media only screen and (min-width: @width-breakpoint-tablet) and (max-width: @width-breakpoint-desktop) {
```suggestion
@media only screen and (min-width: @width-breakpoint-tablet) {
```

2022-11-19 01:52 UTC, jimchamp commented on static/css/page-book.less
> +}
```suggestion
```

2022-11-22 02:57 UTC, jimchamp commented on static/css/components/work.less
> +  }
```suggestion
  div.editionAbout {
    .book-description.read-more,
    .book-description.read-less {
      text-align: center;
    }
    .book-description {
      padding-top: 1em;
    }
  }
```

2022-11-22 02:57 UTC, jimchamp commented on static/css/components/work.less
> +
```suggestion
```

2022-11-22 03:03 UTC, jimchamp commented
Thanks @jpdh9881!  Made a small change to simplify the mobile CSS for the description and read more links.

Merging this into an integration branch that will contain our book page style changes.  Once enough changes are on that branch, we'll merge it into main.  If you are working on another book page issue, go ahead and pull from the integration branch (instead of `master`).

2022-11-22 03:03 UTC, merged