7006/refactor/design and compartmentalize title and author component
internetarchive/openlibrary pull request #7392
Opened 2023-01-08 22:15 UTC by jpdh9881

Closes # 7006

refactor

### Stakeholders
@jimchamp

2023-01-09 15:54 UTC, mekarpeles commented
Is this still a draft? I see a conflict with work.less which may need to be resolved and also, are there any screen shots of the refactor working? This seems like a change affecting a major page so more additional information to guide the reviewer would be appreciated 😊

2023-01-10 06:05 UTC, jimchamp commented
@jpdh9881 could you pull the latest from `book-page-integration` and rebase your branch onto that branch?  You'll have to resolve a couple of merge conflicts, but they're very straight-forward (just tested this on my machine after updating the `book-page-integration` branch).

2023-01-11 01:13 UTC, jimchamp requested changes
I think that this is mostly good.  It doesn't look like the deleted templates are used anywhere else in the site.  The same is true for the CSS rules that were moved to the new Less file.
There are a couple of small changes that can be made to the `title_and_author.html` template that could simplify things.  Also, let's not render the mobile title and author component in `databarWork.html`, since this component will ultimately be above the cover in mobile views.

2023-01-11 22:21 UTC, jimchamp approved these changes

2023-01-11 22:24 UTC, merged