implement read/return buttons under My Loans
internetarchive/openlibrary pull request #7597
Opened 2023-03-05 13:43 UTC by JaydenTeoh

Closes #7443 

Implemented Read/Return buttons for my loans

### Testing

Will need to test whether buttons are functioning properly on staging environment as borrowing API is not enabled for local environment.
### Screenshot

<img width="634" alt="Return book" src="https://user-images.githubusercontent.com/90945854/222964068-8a3eb86d-4221-468b-9584-ab99f321910c.png">

### Stakeholders

@cdrini created issue
@mekarpeles

2023-03-08 17:24 UTC, cdrini requested changes

2023-03-08 17:24 UTC, cdrini commented on openlibrary/macros/FormatExpiry.html
> +            $datetimestr_utc(expiry_datetime)
NOTE: I'm not sure if the timezones here are/were ever correct 😬 

Is the datetime in eg https://openlibrary.org/account/loans.json UTC? CC @mekarpeles 

The datetime from the loans endpoint (eg something like `"2023-03-10 04:42:11"`) is at some point parsed to be a `datetime` object. Then this object is passed through `datetimestr_utc`. This adds a `Z` at the end of the datetime, but does not change the time in any way; and it adds e.g. `T` between to put it in proper ISO format.

The JS then converts this string using `toLocaleString`. This _changes the time_, but it appears to change the time incorrectly.

1. The initial `expiry` was listed as `2023-03-10 04:42:11`
2. After `datetimestr_utc` it is `2023-03-15T04:42:11Z`
3. After the JS, it is `03/15/2023, 12:42 AM` for me. Note this time conversion is wrong for my timezone. 04:42 UTC is 23:42

2023-03-08 17:24 UTC, cdrini commented on openlibrary/templates/books/custom_carousel.html
> +      $if check_loan_status:
Has different style:
![image](https://user-images.githubusercontent.com/6251786/223784469-3444722f-b7c3-4bf2-9484-efda97ca6ed2.png)

Let's use it anyways, and change the style on the books page to put the date under the return button as well.

2023-03-08 17:24 UTC, cdrini commented on openlibrary/macros/FormatExpiry.html
> +            $datetimestr_utc(expiry_datetime)
Sigh I think the are some questions around how to make the timezone correct; so to keep things simple, let's roll this back and leave it as it was before. I'll create a new issue to investigate making these relative with the timezone correct.

2023-03-08 17:26 UTC, cdrini commented
If it's useful for testing, you can use this to get some stub loan data:

lending.py:497

```py
def get_loans_of_user(user_key):
    """TODO: Remove inclusion of local data; should only come from IA"""
    return list(map(Loan, [{"_key": "loan-styledsecretsfor0000hend", "_rev": 1, "type": "/type/loan", "userid": "@drini776", "user": "/people/ScarTissue", "book": "/books/OL2058361M", "ocaid": "styledsecretsfor0000hend", "expiry": datetime.datetime.fromisoformat("2023-03-10 04:42:11"), "fulfilled": True, "uuid": "loan-2731207935", "loaned_at": 1677645731.0, "resource_type": "bookreader", "resource_id": "bookreader:styledsecretsfor0000hend", "loan_link": None, "stored_at": "ia"}]))
```

2023-03-11 07:57 UTC, JaydenTeoh commented
@cdrini I have made the changes requested.
1. I have used `LoanStatus.html` component for rendering the read/return buttons
2. I have reversed the order of the return button and expiry date in `LoanStatus.html`
3. I rollbacked the changes to `FormatExpiry.html`

Here is how a loan in the loans carousel of mybooks page look like:
<img width="664" alt="My Loans (1)" src="https://user-images.githubusercontent.com/90945854/224472292-c49b280d-ec63-4d13-b4e3-6656a83332dc.png">

I am struggling to stub a loan book on the books page to see how the new `databarWork.html` component will look like, could you guide me through it?

2023-03-13 18:51 UTC, cdrini approved these changes
Lgtm! Tested buttons are now there and work. As followups we should

1) Investigate making the date relative. Note the commend
2) Fix spacing on work page; looks funky.
3) After returning, don't go to /loans page. Return to referrer page.

2023-03-13 18:51 UTC, cdrini commented on openlibrary/macros/FormatExpiry.html
> +            $datetimestr_utc(expiry_datetime)
```suggestion
	$datetimestr_utc(expiry_datetime)
```

2023-03-13 18:52 UTC, cdrini commented
@JaydenTeoh getting it in databarWork is a bit more difficult! I've put this up on testing.openlibrary.org and it is working well :)

2023-03-13 18:53 UTC, merged