Add Invisible reCaptcha on Registration Page
internetarchive/openlibrary pull request #7687
Opened 2023-03-19 08:36 UTC by imlakshay08

Closes #7674

This PR adds a Invisible Google reCaptcha on registration page of Open Library.

### Screenshot
![Screenshot_20230319_140409](https://user-images.githubusercontent.com/77228428/226163316-1be46ec7-6871-47f6-9f57-3517a4d7a3eb.png)

### Stakeholders

@mekarpeles @cdrini

2023-07-06 15:16 UTC, jimchamp requested changes
Thanks @imlakshay08, and sorry for the delay!
I've added a number of suggested changes that will be needed for this PR.  In addition to those changes, some changes to the reCAPTCHA configuration for the sign-up form are needed:

1. The Open Library staff will need to generate new keys in order to use the invisible reCAPTCHAs.  Can you create a new entry in our `openlibrary.yml` configuration file for these keys?  You can reference the existing keys [here](https://github.com/internetarchive/openlibrary/blob/bee11c445c5d2d37f6d91c56b89791bb138e80cd/conf/openlibrary.yml#L148-L150), and the new entry can be called `invisible_recaptcha`.
2. The keys for the sign up page are set [here](https://github.com/internetarchive/openlibrary/blob/bee11c445c5d2d37f6d91c56b89791bb138e80cd/openlibrary/plugins/upstream/account.py#L258-L259).  This will need to be updated to use the new config entry.

2023-07-08 05:43 UTC, imlakshay08 commented
> Thanks @imlakshay08, and sorry for the delay! I've added a number of suggested changes that will be needed for this PR. In addition to those changes, some changes to the reCAPTCHA configuration for the sign-up form are needed:
> 
> 1. The Open Library staff will need to generate new keys in order to use the invisible reCAPTCHAs.  Can you create a new entry in our `openlibrary.yml` configuration file for these keys?  You can reference the existing keys [here](https://github.com/internetarchive/openlibrary/blob/bee11c445c5d2d37f6d91c56b89791bb138e80cd/conf/openlibrary.yml#L148-L150), and the new entry can be called `plugin_invisible_recaptcha`.
> 2. The keys for the sign up page are set [here](https://github.com/internetarchive/openlibrary/blob/bee11c445c5d2d37f6d91c56b89791bb138e80cd/openlibrary/plugins/upstream/account.py#L258-L259).  This will need to be updated to use the new config entry.

Hey @jimchamp I have updated the pull requested according to the changes requested. Could you please review it?

2023-07-11 01:18 UTC, jimchamp requested changes
Thanks @imlakshay08!
Looks like some things are still needed:
1. Fix Python indentation errors.
2. Remove `<script>` tag in `create.html`.  What is that script even doing?
3. Update the button's click handler to execute reCAPTCHA test.

2023-07-11 01:18 UTC, jimchamp commented on openlibrary/plugins/upstream/account.py
> +
```suggestion
            public_key = config.plugin_invisible_recaptcha.public_key
            private_key = config.plugin_invisible_recaptcha.private_key
            return recaptcha.Recaptcha(public_key, private_key)
```
Indentation levels are meaningful in Python.  The `if` block code needs to be indented one level more than the `if` statement.
The comments can also be removed.  We can look at the code history in `git`, so these aren't really useful.

2023-07-11 01:18 UTC, jimchamp commented on openlibrary/templates/account/create.html
> +              </script>
What did you do to resolve this?  Do you have questions about what is being asked?

2023-07-11 01:18 UTC, jimchamp commented on openlibrary/templates/account/create.html
> +            <button type="submit" name="signup" id="signup" class="g-recaptcha" data-sitekey="reCAPTCHA_site_key" data-callback='onSubmit' data-action='submit'>$_("Sign Up")</button>
Change number 3 was not implemented.  Do you have questions about this?

2023-07-16 15:16 UTC, jimchamp commented
@imlakshay08, is this ready for review?

2023-07-18 10:58 UTC, imlakshay08 commented
> @imlakshay08, is this ready for review?

Yup, it is ready for the review.

2023-07-18 15:56 UTC, jimchamp reviewed
The following needed changes were not made:
- Submit button missing `larger` class
- `data-sitekey` not properly set
- ReCAPTCHA test never called in existing submit button click handler
- Unnecessary V3 data attributes still present

@imlakshay08, I encouraged you to ask questions if you didn't understand what I requested.  No questions were asked, nor were the questions that I asked you answered.

I'm not really sure how to move this PR forward.  Closing for now, but happy to work with you towards a working solution, if you desire.

2023-07-18 15:56 UTC, jimchamp commented on conf/openlibrary.yml
> +  private_key: ''
```suggestion
    public_key: ''
    private_key: ''
```
Use consistent indentation amount in this file.

2023-07-18 15:57 UTC, closed without merging