simple fix to remove duplicate lists in authors' list widget
internetarchive/openlibrary pull request #7688
Opened 2023-03-19 15:48 UTC by JaydenTeoh

Closes #7643 

Remove duplicate lists showing after adding an author to a list

### Stakeholders

@bicolino34 created issue
@jimchamp lead

2023-03-28 17:51 UTC, jimchamp requested changes

2023-04-01 14:47 UTC, JaydenTeoh commented on openlibrary/templates/type/author/view.html
> +                $:render_template("lists/widget", page, include_rating=False, include_showcase=False)
@jimchamp Thank you! I have made the change as requested.

2023-04-03 16:28 UTC, jimchamp requested changes

2023-04-03 17:38 UTC, JaydenTeoh commented on openlibrary/templates/type/author/view.html
> +                $:render_template("lists/widget", page, include_rating=False, include_showcase=False)
@jimchamp I apologise for my oversight. I have changed the widget back to including showcases but excluding own lists. I have also removed the commit where I merged the master branch in. Please do let me know if I have missed out anything!

2023-04-05 18:41 UTC, merged