Remove deprecated code usage from MARC HTML view
internetarchive/openlibrary pull request #7965
Opened 2023-06-13 04:03 UTC by hornc

relates to #7959

### Technical

### Testing

### Screenshot

### Stakeholders

2023-06-13 08:24 UTC, cclauss approved these changes
Looks good to me.

2023-06-13 08:24 UTC, cclauss commented on openlibrary/catalog/marc/tests/test_marc_html.py
> +import os
Would be cooler to see `from pathlib import Path` but that is a developer choice.  ;-)

2023-06-14 07:20 UTC, cclauss requested changes
https://docs.python.org/3/library/pathlib.html#pathlib.Path.read_bytes

2023-06-14 07:20 UTC, cclauss commented on openlibrary/catalog/marc/tests/test_get_subjects.py
> +TEST_DATA = f'{Path(__file__).parent}/test_data'
```suggestion
TEST_DATA = Path(__file__).parent / 'test_data'
```

2023-06-14 07:20 UTC, cclauss commented on openlibrary/catalog/marc/tests/test_get_subjects.py
> +            f'{TEST_DATA}/xml_input/{item}_marc.xml'
```suggestion
            str(TEST_DATA / 'xml_input' / f'{item}_marc.xml')
```

2023-06-14 07:20 UTC, cclauss commented on openlibrary/catalog/marc/tests/test_get_subjects.py
>              rec = MarcBinary(f.read())
```suggestion
        rec = MarcBinary((TEST_DATA / 'bin_input' / item).read_bytes())
```

2023-06-14 07:20 UTC, cclauss commented on openlibrary/catalog/marc/tests/test_marc_binary.py
> +TEST_DATA = f'{Path(__file__).parent}/test_data/bin_input/'
```suggestion
TEST_DATA = Path(__file__).parent / 'test_data' / 'bin_input'
```

2023-06-14 07:20 UTC, cclauss commented on openlibrary/catalog/marc/tests/test_marc_binary.py
>          ret = list(rec.read_fields(['520']))
```suggestion
    filepath = TEST_DATA / 'wrapped_lines.mrc'
    rec = MarcBinary(filepath.read_bytes())
    ret = list(rec.read_fields(['520']))
```

2023-06-14 07:20 UTC, cclauss commented on openlibrary/catalog/marc/tests/test_marc_binary.py
>              fields = list(rec.read_fields())
```suggestion
        filepath = TEST_DATA / 'onquietcomedyint00brid_meta.mrc'
        rec = MarcBinary(filepath.read_bytes())
        fields = list(rec.read_fields())
```

2023-06-14 07:20 UTC, cclauss commented on openlibrary/catalog/marc/tests/test_marc_binary.py
>              author_field = rec.get_fields('100')
```suggestion
        filepath = TEST_DATA / 'onquietcomedyint00brid_meta.mrc'
        rec = MarcBinary(filepath.read_bytes())
        author_field = rec.get_fields('100')
```

2023-06-14 07:20 UTC, cclauss commented on openlibrary/catalog/marc/tests/test_marc_html.py
> +TEST_DATA = f'{Path(__file__).parent}/test_data/bin_input/'
```suggestion
TEST_DATA = Path(__file__).parent / 'test_data' / 'bin_input'
```
Other modifications are required below...

2023-06-14 07:27 UTC, cclauss commented on openlibrary/catalog/marc/tests/test_parse.py
> +        expect_filename = f'{TEST_DATA}/bin_expect/{i}'.replace('.mrc', '.json')
https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.with_suffix

2023-06-19 04:40 UTC, hornc commented
@cclauss Thanks for the review and suggestions, I've given all the MARC tests another pass focusing on using `Path` correctly.

Hopefully it is better now!

2023-06-25 16:27 UTC, cclauss approved these changes

2023-06-26 01:18 UTC, merged