test: add initRoleValidation test
internetarchive/openlibrary pull request #7979
Opened 2023-06-19 22:39 UTC by GustavoHenriqueRS

test: InitRoleValidationError

### Testing
Run Automatizated Test, this test is for edit.js 

This PR covers the InitRoleValidation test that is present on the book edition page, it simulates several test cases, it is not complete, but it is the beginning, the html provided by the project was insufficient to test the InitRoleValidation

2023-07-01 11:53 UTC, cclauss commented
Please resolve git conflicts.

2023-07-07 15:18 UTC, cdrini requested changes
Thanks @GustavoHenriqueRS ! This looks pretty good, but some automatic formatting changes snuck in which should be removed. Let's please revert those!

2023-07-07 15:18 UTC, cdrini commented on tests/unit/js/editionsEditPage.test.js
> +import { initRoleValidation } from '../../../openlibrary/plugins/openlibrary/js/edit.js';
Move this to the top of the file.

2023-07-07 15:18 UTC, cdrini commented on tests/unit/js/editionsEditPage.test.js
> +});
Also undo these formatting changes.

2023-07-07 15:18 UTC, cdrini commented on tests/unit/js/html-test-data.js
> +      </span>`;
And these.

2023-07-20 15:22 UTC, cdrini commented
Hey @GustavoHenriqueRS ! I'd recommend recreating this PR ; trying to fix those automatic changes will be very difficult. I'd recommend (1) disable the auto-formatting thing you have enabled. Maybe you have prettier?, (2) create a new branch off the latest master, (3) copy your tests from this PR into that fresh branch, and fix any other little fixes. That should make things cleaner!

2023-07-20 15:22 UTC, closed without merging