Refactor cover archival
internetarchive/openlibrary pull request #8208
Opened 2023-08-19 19:53 UTC by mekarpeles

Addresses #7257

2023-08-19 19:57 UTC, mekarpeles commented on openlibrary/coverstore/archive.py
> +    filepath = os.path.join(config.data_root, "items" folder, filename)
```suggestion
    filepath = os.path.join(config.data_root, "items", folder, filename)
```

2023-08-19 21:38 UTC, mekarpeles commented on openlibrary/coverstore/archive.py
> +    return return os.path.join(folder, filename)
```suggestion
    return os.path.join(folder, filename)
```

2023-08-20 02:27 UTC, mekarpeles commented on openlibrary/coverstore/code.py
>                  path = f"{item_id}/{item_tar}/{item_file}.jpg"
Consider using DRY'ing and using `archive.get_filename(item_id, batch_id)`

2023-08-20 04:10 UTC, mekarpeles commented on openlibrary/coverstore/archive.py
>  def audit(group_id, chunk_ids=(0, 100), sizes=('', 's', 'm', 'l')) -> None:
XXX this is currently broken -- the is_uploaded check is not working correctly.

2023-08-24 16:51 UTC, mekarpeles commented on openlibrary/coverstore/tests/test_archive.py
> +    assert Cover.id_to_item_and_batch_id(987_654_321) == ('0987', '65')
```suggestion
    assert archive.Cover.id_to_item_and_batch_id(987_654_321) == ('0987', '65')
```

2023-08-31 23:19 UTC, cdrini requested changes
One blocking bug, and a number of improvements. Big question about Batch.process_pending!

Overall: Niiiice!!! This looks much tighter 😊 I reckon you probably don't have the energy to make any of the improvements so I made them in a separate PR: https://github.com/internetarchive/openlibrary/pull/8251 . Except for the blocker, I think just review the PR and we can merge it in after.

Nicely done!! 10/10 perseverance!! 😊

2023-08-31 23:19 UTC, cdrini commented on openlibrary/coverstore/tests/test_archive.py
These tests are all one-liners; they'd be best suited for doctests instead.

2023-08-31 23:29 UTC, cdrini commented on openlibrary/coverstore/archive.py
> +        zip_command = fr'ia list {item} | grep "{filename}" | wc -l'
Fixed in [`d552555` (#8251)](https://github.com/internetarchive/openlibrary/pull/8251/commits/d55255580326e2f1f435cd805777b945a2aa3082)

2023-08-31 23:29 UTC, cdrini commented on openlibrary/coverstore/code.py
> +    return f"{protocol}://archive.org/download/{itemid}/{zipfile}/{filename}"
Fixed in [`d552555` (#8251)](https://github.com/internetarchive/openlibrary/pull/8251/commits/d55255580326e2f1f435cd805777b945a2aa3082)

2023-08-31 23:30 UTC, cdrini commented on openlibrary/coverstore/archive.py
> +class Cover(web.Storage):
Fixed in [`dd71407` (#8251)](https://github.com/internetarchive/openlibrary/pull/8251/commits/dd714071601e449562027d27d0b8bf44c538c157)

2023-08-31 23:31 UTC, cdrini commented on openlibrary/coverstore/archive.py
> +        img_filename = item_file = f"{pcid}{'-' + size.upper() if size else ''}.jpg"
Fixed in [`d552555` (#8251)](https://github.com/internetarchive/openlibrary/pull/8251/commits/d55255580326e2f1f435cd805777b945a2aa3082)

2023-08-31 23:32 UTC, cdrini commented on openlibrary/coverstore/archive.py
> +            self.zipfiles[size.upper()] = (None, None)
Fixed in [`c83d330` (#8251)](https://github.com/internetarchive/openlibrary/pull/8251/commits/c83d330e1b229add904b9dd3eebc0dc55f785e5a)

2023-08-31 23:32 UTC, cdrini commented on openlibrary/coverstore/archive.py
> +        return int(result.stdout.strip())
Fixed in [`f40e50a` (#8251)](https://github.com/internetarchive/openlibrary/pull/8251/commits/f40e50a1f3476e5a386888a5db038f7c10490477)

2023-08-31 23:33 UTC, cdrini commented on openlibrary/coverstore/archive.py
> +    def add_file(self, name, filepath, **args):
Fixed in [`30b8203` (#8251)](https://github.com/internetarchive/openlibrary/pull/8251/commits/30b8203d6b5c696be0ebeccd67f4ee78db384eec)

2023-08-31 23:34 UTC, cdrini commented on openlibrary/coverstore/archive.py
> +                return max(file_list)
Fixed in [`23309f2` (#8251)](https://github.com/internetarchive/openlibrary/pull/8251/commits/23309f27bd975bd1256e993218b08c16066ff17a)

2023-08-31 23:34 UTC, cdrini commented on openlibrary/coverstore/archive.py
> +        return os.path.basename(zipper.filename)
Fixed in [`c83d330` (#8251)](https://github.com/internetarchive/openlibrary/pull/8251/commits/c83d330e1b229add904b9dd3eebc0dc55f785e5a)

2023-08-31 23:35 UTC, cdrini commented on openlibrary/coverstore/archive.py
> +                _zipfile.close()
Fixed in [`b71f784` (#8251)](https://github.com/internetarchive/openlibrary/pull/8251/commits/b71f784fcbd2e05a04b916c5f086fd2c970853bf)

2023-08-31 23:35 UTC, cdrini commented on openlibrary/coverstore/tests/test_archive.py
Fixed in [`9324a43` (#8251)](https://github.com/internetarchive/openlibrary/pull/8251/commits/9324a43dde8a246647dad371ad93310626548be9)

2023-09-01 18:43 UTC, merged