8253/refactor/merge queue
internetarchive/openlibrary pull request #8273
Opened 2023-09-07 19:53 UTC by Eds-Dbug

Closes #8253 

 Refactor merge request table such that there is more parity between the JS and HTML files.

### Technical

Mostly HTML, with a couple of lines of JS.

### Testing

Mostly visual

### Screenshot

![image](https://github.com/internetarchive/openlibrary/assets/83380248/507bf757-c2d8-46df-81e1-36084f71cfe0)
![image](https://github.com/internetarchive/openlibrary/assets/83380248/d666a8dd-4c0c-4d84-aef3-f1241e2aaeb8)

### Stakeholders

@jimchamp

2023-09-09 08:17 UTC, jimchamp requested changes
Thanks @Eds-Dbug!  Some changes will need to be made to this branch.

While you were working on this, a new filter and dot status color have been added. So, first and foremost, you'll have to pull the latest code and rebase this branch onto `master`.  The Git cheat sheet may come in handy for this task.

Once you've done that, begin working on the review notes.  In short, the following things should be updated:
- [ ] LibrarianQueue.js is renamed MergeRequestTable.js, and all references are updated
- [ ] Update the parameters that are passed to the new templates.

There are other, smaller requests as well.  Be sure to address all of the comments that I've left for you.

2023-09-09 08:17 UTC, jimchamp commented on openlibrary/templates/merge_request_table/table_header.html
> +$ order = header_context['order']
```suggestion
$def with (total, librarians, mode, username, submitter, reviewer)

$ order = query_param('order', 'desc')
```

2023-09-09 08:17 UTC, jimchamp commented on openlibrary/templates/merge_request_table/merge_request_table.html
> +        $:render_template('merge_request_table/table_row', row_context=row_context)
```suggestion
        $:render_template('merge_request_table/table_row', r, username, can_merge)
```

2023-09-09 08:17 UTC, jimchamp commented on openlibrary/templates/merge_request_table/merge_request_table.html
> +    $:render_template('merge_request_table/table_header', header_context=header_context)
```suggestion
    $:render_template('merge_request_table/table_header', total, librarians, mode, username, submitter, reviewer)
```

2023-09-09 08:17 UTC, jimchamp commented on openlibrary/templates/merge_request_table/merge_request_table.html
> +$ order = query_param('order', 'desc')
```suggestion
```
`order` isn't used in this template, so it can be removed.

2023-09-09 08:17 UTC, jimchamp commented on openlibrary/templates/merge_request_table/merge_request_table.html
> +$# row_context: all the arguments to be passed into the table_row template.
```suggestion
```
Neither `header_context` nor `row_context` are arguments for this template.

2023-09-09 20:54 UTC, Eds-Dbug commented
Hi Jim I'm just working over the weekend I'll work on the changes as soon
as I can!


On Sat, Sep 9, 2023, 04:18 jimchamp ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks @Eds-Dbug <https://github.com/Eds-Dbug>! Some changes will need to
> be made to this branch.
>
> While you were working on this, a new filter and dot status color have
> been added. So, first and foremost, you'll have to pull the latest code and
> rebase this branch onto master. The Git cheat sheet may come in handy for
> this task.
>
> Once you've done that, begin working on the review notes. In short, the
> following things should be updated:
>
>    - LibrarianQueue.js is renamed MergeRequestTable.js, and all
>    references are updated
>    - Update the parameters that are passed to the new templates.
>
> There are other, smaller requests as well. Be sure to address all of the
> comments that I've left for you.
> ------------------------------
>
> On
> openlibrary/plugins/openlibrary/js/merge-request-table/LibrarianQueue.js
> <https://github.com/internetarchive/openlibrary/pull/8273#discussion_r1320508285>
> :
>
> This file is supposed to be named MergeRequestTable.js. The name of this
> file's exported class will also need to be updated to MergeRequestTable.
> ------------------------------
>
> On package-lock.json
> <https://github.com/internetarchive/openlibrary/pull/8273#discussion_r1320508389>
> :
>
> This file should not have changed.
> ------------------------------
>
> In openlibrary/templates/merge_request_table/table_row.html
> <https://github.com/internetarchive/openlibrary/pull/8273#discussion_r1320508459>
> :
>
> > +        $else:
> +          $ icon_classes = 'mr-review-actions__checkmark'
> +          $ icon_content = '✓'
> +
> +        <span class="mr-review-actions__assignee-name">$request_reviewer</span>
> +        <span class="$icon_classes">$:icon_content</span>
> +      </div>
> +      <a href="$review_url" target="_blank" class="cta-btn mr-review-actions__review-btn $('' if show_review_button else 'hidden')">$_('Review')</a>
> +    </td>
> +    <td class="mr-comment-toggle">
> +      <a href="javascript:;" class="mr-comment-toggle__comment-expand cta-btn">
> +        <span class="mr-comment-toggle__comment-count">$len(comments)</span>
> +        <img class="mr-comment-review-cell__speech mr-comment-toggle__speech-bubble" src="/static/images/speech-bubble.svg" alt="">
> +      </a>
> +    </td>
> +  </tr>
>
> Add a newline to the end of this.
> ------------------------------
>
> In openlibrary/templates/merge_request_table/table_row.html
> <https://github.com/internetarchive/openlibrary/pull/8273#discussion_r1320509606>
> :
>
> > @@ -0,0 +1,79 @@
> +$def with(row_context)
> +  $ request_title = row_context['request_title']
> +  $ comments = row_context['comments']
> +  $ is_open = row_context['is_open']
> +  $ review_url = row_context['review_url']
> +  $ is_submitter = row_context['is_submitter']
> +  $ r = row_context['r']
> +  $ can_merge = row_context['can_merge']
> +
> +<tr id="mrid-$(r['id'])" class="mr-table-row" data-mrid="$(r['id'])">
>
> ⬇️ Suggested change
>
> -<tr id="mrid-$(r['id'])" class="mr-table-row" data-mrid="$(r['id'])">
> +<tr id="mrid-$(request['id'])" class="mr-table-row" data-mrid="$(request['id'])">
>
> ------------------------------
>
> In openlibrary/templates/merge_request_table/table_row.html
> <https://github.com/internetarchive/openlibrary/pull/8273#discussion_r1320509909>
> :
>
> > +          <div class="comment-panel__comment-display">
> +            $for c in comments:
> +              <div class="comment-panel__comment"><span class="commenter">@$c['username']</span> $c['message']</div>
> +          </div>
> +          $if is_submitter or can_merge:
> +            <div class="comment-panel__input">
> +              $# XXX: Ensure that this has a drag handle
> +              <textarea class="comment-panel__reply-input" rows="1" placeholder="$_('Add a comment...')"></textarea>
> +              <input class="comment-panel__reply-btn" type="button" value="$_('Reply')">
> +            </div>
> +        </div>
> +        $# End : Comment section
> +
> +        $# Start : Submitted by line
> +        <span class="mr-details__opened-by">
> +          $:_('MR #%(id)s opened %(date)s by <a href="/people/%(submitter)s" class="commenter">@%(submitter)s</a>', id=r['id'], date=datestr(r["created"]), submitter=r["submitter"])
>
> ⬇️ Suggested change
>
> -          $:_('MR #%(id)s opened %(date)s by <a href="/people/%(submitter)s" class="commenter">@%(submitter)s</a>', id=r['id'], date=datestr(r["created"]), submitter=r["submitter"])
> +          $:_('MR #%(id)s opened %(date)s by <a href="/people/%(submitter)s" class="commenter">@%(submitter)s</a>', id=request['id'], date=datestr(request["created"]), submitter=request["submitter"])
>
> ------------------------------
>
> In openlibrary/templates/merge_request_table/table_row.html
> <https://github.com/internetarchive/openlibrary/pull/8273#discussion_r1320510102>
> :
>
> > +              <input class="comment-panel__reply-btn" type="button" value="$_('Reply')">
> +            </div>
> +        </div>
> +        $# End : Comment section
> +
> +        $# Start : Submitted by line
> +        <span class="mr-details__opened-by">
> +          $:_('MR #%(id)s opened %(date)s by <a href="/people/%(submitter)s" class="commenter">@%(submitter)s</a>', id=r['id'], date=datestr(r["created"]), submitter=r["submitter"])
> +          $if is_open and is_submitter:
> +            <a class="mr-close-link" title="$_('Click to close this Merge Request')" href="javascript:;">&times;</a>
> +        </span>
> +        $# End : Submitted by line
> +      </div>
> +    </td>
> +    <td class="mr-review-actions">
> +      $ show_review_button = is_open and can_merge and not r.get('reviewer', '')
>
> ⬇️ Suggested change
>
> -      $ show_review_button = is_open and can_merge and not r.get('reviewer', '')
> +      $ show_review_button = is_open and can_merge and not request.get('reviewer', '')
>
> ------------------------------
>
> In openlibrary/templates/merge_request_table/table_row.html
> <https://github.com/internetarchive/openlibrary/pull/8273#discussion_r1320510213>
> :
>
> > +        </div>
> +        $# End : Comment section
> +
> +        $# Start : Submitted by line
> +        <span class="mr-details__opened-by">
> +          $:_('MR #%(id)s opened %(date)s by <a href="/people/%(submitter)s" class="commenter">@%(submitter)s</a>', id=r['id'], date=datestr(r["created"]), submitter=r["submitter"])
> +          $if is_open and is_submitter:
> +            <a class="mr-close-link" title="$_('Click to close this Merge Request')" href="javascript:;">&times;</a>
> +        </span>
> +        $# End : Submitted by line
> +      </div>
> +    </td>
> +    <td class="mr-review-actions">
> +      $ show_review_button = is_open and can_merge and not r.get('reviewer', '')
> +      <div class="mr-review-actions__assignee $('hidden' if show_review_button else '')">
> +        $ request_reviewer = r.get('reviewer', '')
>
> ⬇️ Suggested change
>
> -        $ request_reviewer = r.get('reviewer', '')
> +        $ request_reviewer = request.get('reviewer', '')
>
> ------------------------------
>
> In openlibrary/templates/merge_request_table/table_row.html
> <https://github.com/internetarchive/openlibrary/pull/8273#discussion_r1320510283>
> :
>
> > +$def with(row_context)
> +  $ request_title = row_context['request_title']
> +  $ comments = row_context['comments']
> +  $ is_open = row_context['is_open']
> +  $ review_url = row_context['review_url']
> +  $ is_submitter = row_context['is_submitter']
> +  $ r = row_context['r']
> +  $ can_merge = row_context['can_merge']
>
> ⬇️ Suggested change
>
> -$def with(row_context)
> -  $ request_title = row_context['request_title']
> -  $ comments = row_context['comments']
> -  $ is_open = row_context['is_open']
> -  $ review_url = row_context['revie [...]

2023-09-19 16:32 UTC, jimchamp commented
There are merge conflicts.  Did you rebase this branch, @Eds-Dbug?

2023-09-19 16:51 UTC, jimchamp commented on openlibrary/templates/merge_request_table/table_row.html
> +
```suggestion

```
The standard is that the last line of a file should contain **only** a newline character.  Remove the spaces from line 79, leaving only the newline character.

2023-09-19 16:53 UTC, jimchamp commented on openlibrary/templates/merge_request_table/table_row.html
> +	$ is_submitter = username == request['submitter']
```suggestion
	$ request_title = request.get('title', _('An untitled work') if request['mr_type'] != 2 else _('An unnamed author'))
$ comments = request.get('comments', {}).get('comments', [])
$ is_open = request['status'] == 1
$ review_url = "%s&mrid=%s" % (request['url'], request['id'])
$ is_submitter = username == request['submitter']
```
There's no reason for this to be indented.  Make the change outlined above, and also remove one level of indentation from lines 9 to the end of the file.

2023-09-19 16:54 UTC, jimchamp commented on openlibrary/templates/merge_request_table/table_header.html
> +  $ order = query_param('order', 'desc')
```suggestion
$ order = query_param('order', 'desc')
```
Remove indentation.

2023-09-20 16:36 UTC, closed without merging