Remove inline JS from readinglog_stats.html
internetarchive/openlibrary pull request #8389
Opened 2023-10-06 13:37 UTC by sbwhitt

Closes #8382 

Removes the inline JS from readinglog-stats.html. 

### Technical

Passes data through data-config in html instead.

### Testing

Go to reading log, verify that log stats display correctly.

### Screenshot

### Stakeholders

@RayBB

2023-10-06 14:16 UTC, RayBB approved these changes
I tested and it looks good to me.

<details>
  <summary>Review video</summary>
  
  

https://github.com/internetarchive/openlibrary/assets/921217/ab725697-1faf-4045-bebd-ff02e90eeaa0


  
</details>

@mekarpeles can you review/merge?

2023-10-17 20:14 UTC, jimchamp requested changes

2023-10-17 20:14 UTC, jimchamp commented on openlibrary/plugins/openlibrary/js/index.js
> +    if ($('div.readinglog-charts').length) {
```suggestion
    const readingLogCharts = document.querySelector('.readinglog-charts')
    if (readingLogCharts) {
        const readingLogConfig = JSON.parse(readingLogCharts.dataset.config)
```
Avoid adding new code that relies on jQuery.  Avoid multiple queries for the same element.

2023-10-17 20:14 UTC, jimchamp commented on openlibrary/plugins/openlibrary/js/index.js
> +            .then(module => module.init($('div.readinglog-charts').data('config')));
```suggestion
            .then(module => module.init(readingLogConfig))

2023-10-18 12:11 UTC, sbwhitt commented
@jimchamp Added your suggestions. Thanks for taking a look!

2023-10-19 20:41 UTC, jimchamp approved these changes
Lgtm.  Thanks @sbwhitt!

2023-10-19 20:41 UTC, merged