Team Page json
internetarchive/openlibrary pull request #8461
Opened 2023-10-26 23:14 UTC by mekarpeles

Closes #

### Technical

### Testing

### Screenshot

### Stakeholders

2026-04-14 17:10 UTC, RayBB requested changes
Copilots comments are also worth reviewing as they mostly seem correct.

2026-04-14 17:10 UTC, RayBB commented on openlibrary/templates/about/team.json
> +    "roles": ["fellow-2022", "staff-emeritus"],
Is @scottbarnes no longer staff? If that's the case why are we putting his title to be staff?

I guess it's a little confusing for me when someone was working on open library, but now there's stuff at the Internet Archive. How are we trying to portray that?

2026-04-14 17:10 UTC, RayBB commented on openlibrary/templates/about/team.json
> +    "title": "Front-end Lead",
I don't think I'm the frontend lead

2026-04-14 17:10 UTC, RayBB commented on openlibrary/templates/about/team.json
> +    "title": "Core Maintainer",
Is it intentional that Drini and Jim are "Core Maintainer" instead of staff?

2026-04-21 23:48 UTC, mekarpeles commented on openlibrary/templates/about/team.json
> +    "roles": ["fellow-2022", "staff-emeritus"],
@scottbarnes  is absolutely staff, just with the platform team so he remains staff and Open Library emeritus!

2026-04-21 23:49 UTC, mekarpeles commented on openlibrary/templates/about/team.json
> +    "title": "Core Maintainer",
They are both staff and listed under staff section

2026-04-22 00:07 UTC, mekarpeles commented on openlibrary/templates/about/team.json
> +    "photo_path": "http://blog.archive.org/wp-content/uploads/2023/04/NLW2023_Charles-1024x1024.png",
Fixed — changed to `https://`.

2026-04-22 00:08 UTC, mekarpeles commented on openlibrary/templates/about/team.json
This was addressed in a subsequent commit — the LinkedIn URL was replaced with a stable image URL.

2026-04-22 00:08 UTC, mekarpeles commented on openlibrary/templates/about/team.json
> +    "projects": [
Same as above — resolved in a subsequent commit with a stable image URL.

2026-04-22 00:08 UTC, mekarpeles commented on openlibrary/templates/about/team.json
> +    "title": "Front-end Lead",
Good catch — updated to "Engineering Fellow" to reflect your fellow role. Let me know if you'd prefer a different title!

2026-04-22 00:08 UTC, mekarpeles commented on openlibrary/templates/about/team.json
> +    "title": "Core Maintainer",
Updated both Drini and Jim to "Staff, Core Maintainer" to make their staff status explicit.

2026-04-29 19:56 UTC, RayBB approved these changes
Looks good

2026-04-29 19:56 UTC, merged