Add zero padding to last read date in client-side code
internetarchive/openlibrary pull request #8523
Opened 2023-11-14 06:54 UTC by KshitijThareja

Closes #8521 

This PR aims to add zero padding to last read date for a book in client-side code.

### Testing
#### Steps to verify: 
1. Mark a book as "Already Read". A prompt for a read date will appear below the dropper. Click the "Other" option to manually enter a date.
2. Set a read date of 1 January 2023, and submit the form.
3. You'll see that the day and month will be zero padded wherever expected.

### Proof

![Screenshot_20231114_122109](https://github.com/internetarchive/openlibrary/assets/116485536/07d332b3-7b18-432e-afcd-045b39c9910f)

https://github.com/internetarchive/openlibrary/assets/116485536/59d4d52c-e302-453c-a88e-7e9e87102c6f

### Stakeholders
@jimchamp

2023-11-15 17:48 UTC, jimchamp requested changes
Thanks @KshitijThareja!  Will merge this once the suggested changes have been made.

2023-11-15 17:48 UTC, jimchamp commented on openlibrary/plugins/openlibrary/js/check-ins/index.js
> +        }
```suggestion
        date += `-${month.padStart(2, '0')}`
```
Use `padStart` in a way that avoids extra conditionals.

2023-11-15 17:48 UTC, jimchamp commented on openlibrary/plugins/openlibrary/js/check-ins/index.js
> +            }
```suggestion
            date += `-${day.padStart(2, '0')}`
```

2023-11-16 04:42 UTC, KshitijThareja commented
@jimchamp I have made the necessary changes. I agree should have reviewed my submission before making the PR.
I guess this PR can be merged now.

2023-11-16 16:04 UTC, jimchamp approved these changes
Lgtm!

2023-11-16 16:04 UTC, merged