Adds follow (pubsub) feature
internetarchive/openlibrary pull request #8607
Opened 2023-12-09 20:54 UTC by mekarpeles

Followup to #8597, closes #1966

- database schema for follows
- adds core model for follows
- elementary mybooks /feed of followers
- ability to follow/unfollow
- json API to fetch patron's follows

### Technical

Schema already on production db

### Testing

### Screenshot

### Stakeholders

2023-12-09 20:55 UTC, mekarpeles commented
To leverage follows, on the Books page, start with the following code:

```
+++ b/openlibrary/templates/type/edition/view.html
@@ -338,6 +338,13 @@ $ worldcat_links = macros.WorldcatLink(isbn=isbn_13 or isbn_10, oclc_numbers=ocl
       </div>
     </div>
 
+    <div>
+      <ul>
+	$for p in page.get_patrons_who_also_read():
+	  <a href="/people/$(p.key.split('/')[2])/books/already-read">$p.key.split('/')[2]</a></li>
+      </ul>
+    </div>
```

2024-02-20 16:05 UTC, mekarpeles commented
BLOCKER: Bug,
http://ol-dev1.us.archive.org:1338/people/seabelis/followers seabelis following themself?

2024-02-20 16:17 UTC, mekarpeles commented on openlibrary/plugins/upstream/account.py
> +        template = render['account/follows'](mb.me, follows, manage=manage)
```suggestion
        template = render['account/follows'](mb.user, follows, manage=manage)
```

2024-02-28 22:04 UTC, jimchamp requested changes
Thanks, @mekarpeles!  A few things that I've noticed:

1. The "My Feeds" page doesn't render for patrons who are not following anybody.  The issue is with the `get_feed` function.  I've added some notes about this in the review, but couldn't come up with a solution that didn't cause other bugs...
2. I don't think that `PubSub` should extend `db.CommonExtras`, which seems to primarily be used to add methods for handling redirects.
3. You probably want some `statsd` counts for this feature somewhere.
4. What happens when a followed patron makes their reading log private?  Do they lose all of their followers?
5. When I was on the `/followers` and `/following` pages, it seemed odd that these options were not present in the sidebar.

Of these, I think that `#1` is a show-stopper until fixed, and `#4` seems very important and may have policy implications.

2024-04-16 22:37 UTC, jimchamp commented
Merging this should also close #1966.

2024-04-24 23:12 UTC, jimchamp approved these changes
Thanks @mekarpeles!  This largely looks good to me.

One thing: While, testing, I didn't realize that these were links until the cursor changed on hover.  Patrons using mobile devices may never make such a realization.  Also, the clickable region for each is large:
![image](https://github.com/jimchamp/ol-tasks/assets/28732543/dd99d8d4-69cd-4643-b3ea-8ec0d3eb679d)

Not a show-stopper, and maybe even a good first issue for the next iteration.

Anyway, I'm going to approve this PR, but it is blocked from merging until #9147 is merged.  Once that is done, feel free to merge this yourself, @mekarpeles.

2024-04-29 19:37 UTC, merged