Fixed #8585
internetarchive/openlibrary pull request #8638
Opened 2023-12-17 06:35 UTC by siddoinghisjob

Adds subtitles along with titles of books in stats

fix

### Technical

added subtitle attribute to work_json in mybooks.py and printed it in readinglog_stats.html

### Testing

Step 1 : Add a book that has subtitle to Already read
Step 2 : Go to mybook section and click on the My Reading Stats and click on any bar

### Screenshot

### Stakeholders

2023-12-20 10:47 UTC, siddoinghisjob commented
@cdrini Sorry to bother you but if there is any thing more to fix then kindly let me know I ll do that.. so that this PR can be merged ASAP🙏

2023-12-20 18:51 UTC, cdrini requested changes
Hey @siddoinghisjob ! Could you please attach a screenshot of this working? You should be able to fully test this in your local environment :)

2023-12-20 18:51 UTC, cdrini commented on openlibrary/templates/account/readinglog_stats.html
> +        <li><a href="$work.key" style="font-style:oblique">$work.title $work.subtitle</a>
There should be a `: ` between the title and sub title. Make sure not display the `:` if there is no subtitle!

2023-12-21 11:51 UTC, siddoinghisjob commented
> Hey @siddoinghisjob ! Could you please attach a screenshot of this working? You should be able to fully test this in your local environment :)

![open_lib_ss](https://github.com/internetarchive/openlibrary/assets/96379749/1795e0b0-0607-4520-8f21-ef30978c6abe)

2023-12-21 12:02 UTC, siddoinghisjob commented
Hi @cdrini! I have made a PR. Please let me know if you need anything else to be fixed.

2023-12-31 17:14 UTC, siddoinghisjob commented
Hey @cdrini , it's been a while since I made the changes. Anything more to fix :)

2024-01-02 21:00 UTC, cdrini commented on openlibrary/templates/account/readinglog_stats.html
> +            <a href="$work.key" style="font-style: oblique">$work.title $divider $work.subtitle</a>
```suggestion
        $ full_title = work.title
        $if work.subtitle:
            $ full_title = work.title + ': ' + work.subtitle
        <li>
            <a href="$work.key" style="font-style: oblique">$full_title</a>
```

2024-01-02 21:12 UTC, cdrini approved these changes
Lgtm! Appears correctly on testing.openlibrary.org . Thank you @siddoinghisjob !

2024-01-02 21:12 UTC, merged