Fix: Disable 'Submit" button after submission is made .
internetarchive/openlibrary pull request #8660
Opened 2023-12-21 15:34 UTC by xonx4l

issue-:#8651

Closes #8651 

Fix:  Disable 'Submit" button after submission with a loading spinner .

### Technical

  // Adds state
        this.isSubmitting = true;

        // Disable button
        this.submitButton.disabled = true;

        // Show loading spinner
        this.submitButton.textContent = "Submitting...";
  
### Testing

A loading spinner can be seen after submission is made 

### Stakeholders

2023-12-22 00:47 UTC, jimchamp requested changes
@xonx4l, thanks!   I've added a few suggested changes.  Aside from those, disregard my comment in the issue thread about the spinner animation --- changing the button's text to "Submitting..." is simpler.

2023-12-22 00:47 UTC, jimchamp commented on openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger.js
> +        this.isSubmitting = true;
```suggestion
```
This isn't being used in any meaningful way, so remove it.

2023-12-22 00:47 UTC, jimchamp commented on openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger.js
> +        // Show loading spinner
```suggestion
```
This is not a spinner.  Remove misleading comment.

2023-12-22 00:47 UTC, jimchamp commented on openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger.js
> +                    this.isSubmitting = false;
```suggestion
```
`!response.ok` implies that an error occurred.
`this.isSubmitting` doesn't do anything.

2023-12-22 00:47 UTC, jimchamp commented on openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger.js
> +                    new FadingToast('Error submitting batch').show();
```suggestion
                    new FadingToast('Batch subject update failed. Please try again in a few minutes.').show();
```
Why was this changed?  There was no mention of changing the toast message in #8651.

2023-12-22 00:47 UTC, jimchamp commented on openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger.js
> +                    this.isSubmitting = false;
```suggestion
```

2023-12-22 00:47 UTC, jimchamp commented on openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger.js
> +                    this.resetTaggingMenu();
```suggestion
                    this.hideTaggingMenu();
                    new FadingToast('Subjects successfully updated.').show()
                    this.submitButton.textContent = 'Submit';
                    this.updateFetchedSubjects();
                    this.resetTaggingMenu();
```
- No need to change the order of operations here
- No need to change the toast message here
- Submit button's text should be reset to its original state.  Several submissions can occur without reloading the page.

2023-12-23 03:44 UTC, xonx4l commented
again @jimchamp thanks man for showing the right direction and pointing out the mistakes and helping in my learning .Thanks you very much .Means a lot .

2023-12-27 22:52 UTC, jimchamp approved these changes
Thanks @xonx4l!  This is working as expected.

You can use GitHub's UI to add several review suggestions to a single commit.  See [this documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request#applying-suggested-changes) for more information.

2023-12-27 22:52 UTC, merged

2023-12-28 13:18 UTC, xonx4l commented
Thanks @jimchamp will surely go through the documentation . Thanks for your time .