Added: Highlighted staged changes in BulkTagger
internetarchive/openlibrary pull request #8676
Opened 2023-12-30 14:30 UTC by QuantuM410

Closes #8658 

This PR addresses the issue outlined in #8658 by enhancing the Bulk Tagger tool to provide visual indications of subjects staged for addition or removal. The proposed solution adds highlighting to the corresponding menu options when a subject is staged.

### Technical

The PR integrates the highlighting logic to the staged changes for addition or removal. The highlighting classes are applied based on the updated menu option state. I still have some queries regarding the staged changes as mentioned [**here**](https://github.com/internetarchive/openlibrary/issues/8658#issuecomment-1872234457)

### Testing

1. Open Manage Subjects Menu
![image](https://github.com/internetarchive/openlibrary/assets/85943021/c49564fd-470a-42e7-b46d-1f36884fda15)

2. Add / Remove subject to view highlighted staged changes
![image](https://github.com/internetarchive/openlibrary/assets/85943021/85733241-a867-4a1b-9b45-41b40ca8811e)

### Screenshot

Before Staging changes
![image](https://github.com/internetarchive/openlibrary/assets/85943021/a5493df3-e63b-4166-be02-d166a4d31199)

After Staging changes
![image](https://github.com/internetarchive/openlibrary/assets/85943021/4b85e3d4-c001-4284-98a2-c3663638e5a2)

### Stakeholders

@jimchamp

2024-01-03 21:11 UTC, QuantuM410 commented
@jimchamp Can you please review this PR :)

2024-01-03 22:50 UTC, jimchamp commented
If this is ready for review, press the "Ready for review" button.
Is it ready for review?  I said that there should only be yellow highlighting in [this comment](https://github.com/internetarchive/openlibrary/issues/8658#issuecomment-1872552273), but I see both yellow and grey highlighting in your screenshots...

2024-01-04 02:54 UTC, QuantuM410 commented
> If this is ready for review, press the "Ready for review" button. Is it ready for review? I said that there should only be yellow highlighting in [this comment](https://github.com/internetarchive/openlibrary/issues/8658#issuecomment-1872552273), but I see both yellow and grey highlighting in your screenshots...

Yeh I added grey highlighting to highlight the removed changes and yellow for the addition. I can revert the highlight color for removed to yellow :) @jimchamp

2024-01-04 19:10 UTC, QuantuM410 commented
@jimchamp I have made this PR ready for review. If you want me to revert the color of "removed" changes to yellow instead, Ill make a commit :+1:

2024-01-19 15:22 UTC, QuantuM410 commented
@jimchamp Please review it this PR

2024-02-20 19:30 UTC, jimchamp requested changes
Thanks @QuantuM410, and apologies for the massive delay.  There's not a need for the level of state management that these changes add --- we need only add a single class if an option is staged.  If a staged option is highlighted, people need only look for the status icon to know if the tag is being added or removed.

I've added some suggested changes that should simplify things a bit.

2024-02-20 19:30 UTC, jimchamp commented on static/css/components/tagging-menu.less
> +  }
```suggestion
  &--staged {
    background-color: @light-yellow;
  }
```
These menu options will either be staged or not.  Let's use `.selected-tag--staged` to add the yellow background to menu options.

2024-02-20 19:30 UTC, jimchamp commented on openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger.js
> +    }
```suggestion
```
This much state management is not needed.  Whenever an option is clicked, add the `selected-tag--staged` class.

2024-02-20 19:30 UTC, jimchamp commented on openlibrary/plugins/openlibrary/js/bulk-tagger/BulkTagger.js
> +        this.highlightMenuOption(menuOption);
```suggestion
        menuOption.stage()
```
Could you add a `stage` method to `MenuOption`?  This should add the `selected-tag--staged` class to the menu option.

2024-02-22 16:48 UTC, QuantuM410 commented
@jimchamp I have implemented the required changes

Before:
![Screenshot from 2024-02-22 21-49-30](https://github.com/internetarchive/openlibrary/assets/85943021/8aa161a6-58a0-4f4f-9c66-913b295e608d)

After:
![Screenshot from 2024-02-22 21-49-43](https://github.com/internetarchive/openlibrary/assets/85943021/e062158d-d761-4f51-9ad0-0a36fc6e4fe7)

2024-02-26 18:50 UTC, merged