Re-enabled autofill on add new book form
internetarchive/openlibrary pull request #8688
Opened 2024-01-04 19:57 UTC by shivam200446

Closes #8598 

### Technical

updated `book_title` as the new `name` 
 Added `book_title=""` as object to post handler and set the value of `i.title` to `i.book_title`
### Testing

### Screenshot

### Stakeholders

2024-01-05 18:02 UTC, jimchamp requested changes
Thanks, @shivam200446.
Instead of changing `i.title` to `i.book_title` throughout the code, please set `i.title = i.book_title` like I asked.  You can do this on line 229, right after `i` is defined.

2024-01-06 05:53 UTC, shivam200446 commented
> Thanks, @shivam200446. Instead of changing `i.title` to `i.book_title` throughout the code, please set `i.title = i.book_title` like I asked. You can do this on line 229, right after `i` is defined.

Sorry for inconvenience!

2024-01-08 19:31 UTC, jimchamp approved these changes

2024-01-08 19:32 UTC, merged

2024-01-08 19:32 UTC, jimchamp commented
No worries!  Thanks for making those changes.