Make MergeUI edition covers link to enlarged covers
internetarchive/openlibrary pull request #8845
Opened 2024-02-26 22:16 UTC by cdrini

Closes #

### Technical

### Testing

### Screenshot

### Stakeholders

2025-06-04 00:47 UTC, RayBB requested changes
I tested it and it works well but left a few questions for you.

2025-06-04 00:47 UTC, RayBB commented on openlibrary/components/MergeUI/EditionSnippet.vue
> +            window.open(url, undefined, 'width=600,height=600');
Why set the height and width? I'd assume if they're clicking to make it big they'd want it to be as big as possible?

2025-06-04 00:47 UTC, RayBB commented on openlibrary/components/MergeUI/EditionSnippet.vue
> +      cursor: zoom-in;
Nice effect!

2025-06-04 00:47 UTC, RayBB commented on openlibrary/components/MergeUI/EditionSnippet.vue
> +            }
Agree with this one!

2025-06-04 00:47 UTC, RayBB commented on openlibrary/components/MergeUI/EditionSnippet.vue
> +      @click="openEnlargedCover"
Also seems fine.

2025-06-04 00:47 UTC, RayBB commented on openlibrary/components/MergeUI/EditionSnippet.vue
> +            return '';
Good!! This finally stops showing broken images when there is none!

2025-06-09 13:49 UTC, cdrini commented on openlibrary/components/MergeUI/EditionSnippet.vue
> +                url = `https://archive.org/download/${ocaid}/page/cover_w600_h600.jpg`;
```suggestion
            } else if (this.edition.ocaid) {
                const ocaid = this.edition.ocaid;
                url = `https://archive.org/download/${ocaid}/page/cover_w600_h600.jpg`;
```

2025-06-09 13:50 UTC, cdrini commented on openlibrary/components/MergeUI/EditionSnippet.vue
> +            window.open(url, undefined, 'width=600,height=600');
In my testing I found 600px I've found enough to read any useful into. Making it smaller than full screen avoids it taking over the user action so-to-speak. They can enlarge/zoom in if necessary, but it's usually just to read a small piece of info or something to double check a word/etc.

2025-06-09 14:09 UTC, merged