Persist Yearly Reading Goals banner preferences
internetarchive/openlibrary pull request #8892
Opened 2024-03-11 15:35 UTC by QuantuM410

Closes #8814 

### Technical

This PR addresses the issue where the Yearly Reading Goal banner reappears upon each login. The solution involves persisting the banner preference on the User, preventing the banner from displaying every time a user logs in.

### Testing

- Dismiss the "Your Reading Goal" banner 
- You can monitor browser storage for the respective cookie starting with "yrg" stored locally
- Remove the cookies or open another browser
- Log in and check the "yrg" cookies being stored as per the user preference leading to no display of the YRG banner

### Screenshot

### Stakeholders

@jimchamp

2024-03-14 17:58 UTC, jimchamp requested changes
Thanks, @QuantuM410!

Just a few small changes and this will be ready to merge.

2024-03-14 17:58 UTC, jimchamp commented on openlibrary/plugins/upstream/account.py
> +                        expires=(3600 * 24 * 30),
```suggestion
                        expires=(3600 * 24 * 365),
```
This shouldn't expire for one year.

2024-03-14 17:58 UTC, jimchamp commented on openlibrary/plugins/upstream/account.py
> +                expires=(3600 * 24 * 30),
```suggestion
                expires=(3600 * 24 * 365),
```

2024-03-15 15:19 UTC, QuantuM410 commented
@jimchamp I have updated the code with the required changes, Thanks :)

2024-03-20 18:27 UTC, jimchamp approved these changes
Lgtm! Thanks, @QuantuM410

2024-03-20 18:27 UTC, merged