Add messages.pot update script to pre-commit.
internetarchive/openlibrary pull request #8900
Opened 2024-03-12 19:26 UTC by rebecca-shoptaw

Closes #8818.

Feature. Automates generation of new `messages.pot` file for translation whenever Python or HTML files are changed.

### Technical

Shockingly simple! Just involved adding a new hook and corresponding dependencies to `pre-commit.config.yaml`

### Testing

1. Make a change to a Python or HTML file (ideally one that adds new text or adjusts line numbers)
2. Install pre-commit if not installed
3. Commit the change; pre-commit should automatically generate a new `messages.pot` file

### Stakeholders

@cdrini

2024-03-12 21:18 UTC, scottbarnes commented on .pre-commit-config.yaml
> +        - "git+https://github.com/webpy/webpy.git@ed3e92cceb6ed870b224107ea653f48fa7fc2d0a#egg=web-py"
```suggestion
        - "git+https://github.com/webpy/webpy.git@d3649322b85777b291ac2b7b3699fb6fc839e382#egg=web-py"
```

2024-03-13 17:40 UTC, scottbarnes commented on .pre-commit-config.yaml
> +      files: '\.(html|py)$'
```suggestion
pass_filenames: false
```
This should stop `pre-commit` from running the command multiple times.

2024-03-13 17:44 UTC, scottbarnes reviewed
I think the `SyntaxWarning: invalid escape sequence '\ '` is coming from something that `i18n-messages extract` is calling, rather than from `pre-commit`.

I don't think this is the solution, but with the change to use `pass_filenames: false` instead of `files`, and the following, `pre-commit` shows `Passed` for `Generate POT`:

```diff
diff --git a/scripts/i18n-messages b/scripts/i18n-messages
index 98f28e5d6..4085c927c 100755
--- a/scripts/i18n-messages
+++ b/scripts/i18n-messages
@@ -4,6 +4,10 @@ macros and write to openlibrary/i18n/messages.pot file.
 """
 import _init_path  # noqa: F401  Imported for its side effect of setting PYTHONPATH
 
+import warnings
+
+warnings.simplefilter('ignore')
+
 import sys
 from openlibrary import i18n
 ```

Perhaps somewhere inside is a regex that needs `r` in front of the string. Not sure.

2024-03-14 13:15 UTC, rebecca-shoptaw commented
pre-commit.ci autofix

2024-04-09 04:14 UTC, cdrini requested changes
Awesome, thank you @rebecca-shoptaw !! I tested this in gitpod/locally, and:

- ✅ When no html/python files staged it doesn't run
- ✅ When HTML file staged with no i18n lines changed, it runs but doesn't save
- ✅ When HTML file staged with i18n lines moved but not modified, it runs but doesn't save
- ✅ When HTML file staged with i18n lines modified, it runs and saves

There's one case I realized would cause some issues; on my machine I have a bunch of untracked files, some of which are html/python! These are getting added to the messages.pot file when I do a commit, which is not what we want. I reckon we should try to exclude untracked/unstaged files when running from pre-commit. Maybe a `--pre-commit` option that adds these exclusions?

```py
    # Exclude untracked git files.
    # git ls-files --others --exclude-standard
    untracked_files = {
        Path(line)
        for dir in dirs
        for line in subprocess.run(
            ['git', 'ls-files', '--others', '--exclude-standard', dir],
            stdout=subprocess.PIPE,
            text=True,
        ).stdout.split('\n')
        if line.endswith(('.py', '.html'))
    }

    # Also exclude unstaged git files.
    # git diff --name-only
    unstaged_files = {
        Path(line)
        for line in subprocess.run(
            ['git', 'diff', '--name-only'],
            stdout=subprocess.PIPE,
            text=True,
        ).stdout.split('\n')
        if line.endswith(('.py', '.html'))
    }

    excluded_files = untracked_files | unstaged_files
```

And then when it builds the catalog makes sure to toss these out?

Otherwise a few small code cleanups/fixes!

2024-04-09 05:27 UTC, cdrini commented on .pre-commit-config.yaml
> +        - Babel==2.12.1
Actually nevermind this is an issue with all the dependencies in this file, sigh!

2024-04-30 04:11 UTC, cdrini approved these changes
Lgtm! One small change

2024-05-01 19:28 UTC, cdrini commented
We talked Creation-Date potentially causing a few headaches via merge conflicts ; we decided to create a separate issue to fix the Creation-Date to the first day of the current year; this should hopefully not interfere with any translator flows, whilst reducing conflict headaches for us!

2024-05-01 19:29 UTC, merged