Modified alt text from Template to Page
internetarchive/openlibrary pull request #9020
Opened 2024-04-03 09:21 UTC by Spedi

Closes #9012

Modifies the Alt text for the History button from Template to Page.

### Stakeholders
@RayBB

2024-04-03 10:23 UTC, RayBB requested changes
Good start!

Please change the title on both pages "Edit this template"

I think the title for databarHistory and compact_title.html should probably also be changed.
Edit: Also check for other usages of "template" strings in the wrong spot if you can.

2024-04-03 10:50 UTC, Spedi commented
Found a title "Edit this template" on `profile.html`, should I change it to "Edit this page" too?

2024-04-03 10:54 UTC, RayBB commented
@Spedi yes that makes sense to me.

2024-04-04 21:11 UTC, RayBB approved these changes
Just tested and it's working great. Good job!

I think that `openlibrary/templates/admin/profile.html` might be able to be deleted but lets not let that block this issue.

Now we just need staff to give it a final check.

2024-04-08 20:00 UTC, merged