remove inlinejs for waitlist
internetarchive/openlibrary pull request #9038
Opened 2024-04-05 20:57 UTC by RayBB

Closes #

### Technical

### Testing

### Screenshot

### Stakeholders

2024-04-12 19:02 UTC, jimchamp requested changes
Thanks @RayBB!

While testing with production data, the dialog would open when I clicked a `a.leave` link.  However, confirming would not remove me from the waitlist.

I mocked a waiting list on my local environment, and discovered that the context of `this` has changed from `a.leave` to the `initLeaveWaitlist` function.  I've provided some code that should fix that.

I also noticed that the "Leave waitlist" dialog has an existing bug.  There should be a "Are you sure you want to leave the waiting list of {title}?" CTA displayed in the dialog, but it is hidden by the `hidden` class.  I think that removing `hidden` from the `#leave-waitinglist-dialog` element on `a.leave` clicks would fix this, but I didn't test it out.

2024-04-15 09:53 UTC, RayBB commented
@jimchamp I addressed your comments. Good catch on the context changing. I've updated the code as you mentioned and put it on testing and it seems to be working right (easier to tell now that the title isn't hidden in the dialog).

Did you figure out how to add books to your waitlist in prod?
Or can you share how you were mocking the responses? Is there an easy way to do that?

In any case, I'm hoping this PR is done now! 👍

2024-04-15 23:38 UTC, jimchamp reviewed
Lgtm!  Tested removing some myself from some books' wait lists on testing.openlibrary.org.

> Did you figure out how to add books to your waitlist in prod?

I had to join wait lists on archive.org details pages, from the borrow button's drop down options:
![Screenshot from 2024-04-15 15-49-37](https://github.com/internetarchive/openlibrary/assets/28732543/5589236b-3430-4e87-b78d-b347eec8cffc)

> Or can you share how you were mocking the responses? Is there an easy way to do that?

I hacked together [this code](https://github.com/internetarchive/openlibrary/compare/master...jimchamp:openlibrary:poc/mock-waitlist) to test your changes locally.  I mocked the response based on how the wait list is represented in the store, as per [this docstring](https://github.com/internetarchive/openlibrary/blob/3d1b5ae890f1c4a93d9d431addd442a1f16e9960/openlibrary/core/waitinglist.py#L5-L13), and mocked the methods that are called in `/account/loans.html` (the commented-out attributes weren't needed for that page).

This was definitely a quick and dirty way to mock this.  It would be more broadly useful if `User.get_waitinglist()` returned some configurable waiting list in dev enviroments, and that the mocked methods returned expected values (without the need for additional parameters, like the `get_book` call in the linked branch).  I'm not sure if this is a worthwhile pursuit, though, as we rarely need a working waitlist in dev...

2024-04-15 23:39 UTC, jimchamp approved these changes

2024-04-15 23:39 UTC, merged