Fixed overlap between button text and icon
internetarchive/openlibrary pull request #9066
Opened 2024-04-10 20:55 UTC by Realmbird

Closes #8899

Fixes overlap between button text and icon

### Technical

- Issue: Audio book read buttons had button text & icon "external link" overlap on smaller screen sizes
- Cause: Responsive booksPerBreakpoints were not accurate with when less pages should be shown on the page

- Fix: Changing responsive booksPerBreakpoints was not css like issue had stated

### Testing

1. docker compose up
// For running site
2. docker compose exec -e PYTHONPATH=. web bash -c "./scripts/copydocs.py --search 'author_key:OL9411725A' --search-limit 100"
// Adding data
3. http://localhost:8080/works/OL36891831W/
4. Start changing screen width

### Screenshot

[Screencast from 04-10-2024 01:54:07 PM.webm](https://github.com/internetarchive/openlibrary/assets/56459277/823fe90a-010f-47ff-9da5-183c9692d1b4)
Will be screencast to demonstrate that text never overlaps with icon

### Stakeholders

@cdrini @RayBB

2024-04-12 13:34 UTC, RayBB commented
@Realmbird it is on [testing](https://testing.openlibrary.org/works/OL36891831W/Short_Mystery_Suspense_Collection_013) now and it is working as expected. I think it fixes the initial concern. However, I want to run it by the design team in the call today. 👍

2024-04-12 14:56 UTC, Realmbird commented
Thanks

2024-04-15 12:11 UTC, RayBB commented
The design call didn't have time for me to bring this up.

Maybe @cdrini can comment directly.

2024-04-17 09:37 UTC, RayBB commented
@Realmbird we have to wait for @cdrini to comment on this one. He's off Thursday and Friday so it will probably have to wait until next week.

Here are my thoughts though:
- Your PR does fix the issue
- However, I'm not sure if those numbers you changed in the JS were set for a specific reason so I'm hesitant to change them.
- In my opinion, I think it is a better long-term fix to move the image out of the background and have it be right next to the text. But that's just my opinion and changes the design of the button. I assume the original goal was that the external icon stays to the far right while the text stays centered. I'm not sure how attached we are to that design.

2024-04-19 17:08 UTC, RayBB commented
@Realmbird 
I asked in the design call today. 
The feedback I got from @mekarpeles was that maybe we should see if we can make the text/icon scale smaller with the size of the button. We are still not sure if that is feasible and probably want to get feedback from @cdrini before spending too much time on that path.

2024-04-19 17:20 UTC, RayBB commented
@Realmbird feel free to play around with moving the icon out but ultimately we should wait for Drini's input here. We can try to get his input on the Tuesday call.

2024-04-19 17:24 UTC, Realmbird commented
Ok in the mean time gonna work on other issue

2024-05-22 15:30 UTC, cdrini commented
Howdy folks! I think what we can try is; apologies it will be a little involved!

1) Decrease the font size of all `cta-btn` from 16px to 14px. Make only the primary button, the one inside the `#read-options` element, be 16px.
2) Make all `.cta-btn` `white-space: nowrap; overflow: hidden; text-overflow: ellipsis;` and make `.cta-btn--external` have a padding-right of 25px ; this should make sure there's enough space for the external icon, and crop the text with an ellipsis if there isn't
3) Make all buttons have `padding: 8px 0` instead of the current `padding: 8px` ; the button label already has padding, so we're just doubling up on it.
4) Make all buttons have `text-align: center`; this is getting lost somewhere for carousels.

That should do it, and give us something like this

![image](https://github.com/internetarchive/openlibrary/assets/6251786/77b5f623-8d48-4e89-951d-cb20c11153d0)

Here's the css I experimented with ; although yours will likely look different / be in a different spot

![image](https://github.com/internetarchive/openlibrary/assets/6251786/8d410162-4a21-4bd5-9830-dec0feffe617)

2024-05-22 17:55 UTC, Realmbird commented
Ok will make changes to css

2024-05-22 18:36 UTC, Realmbird commented
@cdrini Added your changes

2024-05-22 18:39 UTC, Realmbird commented
[Screencast from 05-22-2024 11:22:57 AM.webm](https://github.com/internetarchive/openlibrary/assets/56459277/d9ffd12f-0544-4b23-8d56-e3f0abce4df0)
After changes

2024-05-22 19:17 UTC, RayBB requested changes

2024-05-22 19:17 UTC, RayBB commented on openlibrary/plugins/openlibrary/js/carousel/Carousel.js
> +            responsive: [1200, 1024, 740, 580, 360]
```suggestion
            responsive: [1200, 1024, 600, 480, 360]
```
Lets restore these (I think that's what Drini wanted) then I'll put it on testing so we can see how things look!

2024-05-31 19:58 UTC, Realmbird commented
@RayBB @cdrini  Tried rays changes caused overlap bug to reappear

2024-05-31 19:59 UTC, Realmbird commented
![Uploading Screenshot from 2024-05-31 12-59-20.png…]()

2024-11-27 00:25 UTC, RayBB commented
Closing this to offer up someone else to work on this one.

2024-11-27 00:25 UTC, closed without merging