Cache collections with new `CacheablePathsProcessor`
internetarchive/openlibrary pull request #9069
Opened 2024-04-10 23:39 UTC by jimchamp

Closes #9058

Creates new `CacheablePathsProcessor` that can be used to cache Infogami pages without overriding the default Infogami handler for such pages.

This processor attempts to fetch pages from cache when the following are true:
1. The request is a `GET`
2. The request is not specially encoded data (`json`, `yml`, etc.)
3. The request's path matches one of the patterns in the `paths_and_expiries` dictionary
4. `debug` is not in the request's query string
5. The requested page's mode is `view`

The processor has been set up to cache`/collections` and `/collections/{collection_identifier}` pages.

### Technical

Cache keys will take the form:
`{web.ctx.path}.{web.ctx.lang}{query_string}`

...where `query_string` is either an empty string or an ordered query string (e.g. `?a=1&b=1&c=1`)

Adding a new path pattern and expiry time to `paths_and_expiries` will enable caching for pages matching to path pattern.

### Testing

1. Deploy this branch to a testing environment
2. Navigate to the `/collections` page
3. On page load, refresh the page

The load time on refresh should be noticeably faster than the initial page load.

### Screenshot

### Stakeholders

@mekarpeles

2024-04-10 23:45 UTC, jimchamp commented on openlibrary/plugins/openlibrary/processors.py
> +from openlibrary.plugins.openlibrary.home import caching_prethread
**Reviewer:** Is it okay to use this `caching_prethread`?

I more or less re-implemented the homepage caching in this new processor, which uses `caching_prethread`.

2024-04-10 23:59 UTC, jimchamp commented on openlibrary/plugins/openlibrary/processors.py
> +
**Reviewer:** Please check the order of the conditionals that return `handler()`.

My goal is to order these such that we exit this method as quickly as possible if the page isn't being cached by this processor.

2024-04-11 00:00 UTC, jimchamp commented on openlibrary/plugins/openlibrary/processors.py
> +        cache_key = f'{web.ctx.path}.{web.ctx.lang}'
Will be something like `/collections.en` or `/collections.it`.

2024-04-11 00:01 UTC, jimchamp commented on openlibrary/plugins/openlibrary/processors.py
> +            del i['m']
**Reviewer:** This may be totally unnecessary...

2024-04-22 19:52 UTC, mekarpeles requested changes
At minimum, cache should take into consideration `lang` and `printdisabled` (in he future `sfw`

2024-04-25 23:33 UTC, jimchamp commented
Caching localized pages was already in place (we both missed that during our quick review).  Have added additional caching for print-disabled page requests, and have included commented-out code for `sfw`.

2024-05-06 21:50 UTC, jimchamp commented
Blocking temporarily for PM script testing purposes.

2024-05-10 15:47 UTC, merged