allows librarians to view edition search
internetarchive/openlibrary pull request #9093
Opened 2024-04-16 14:32 UTC by quackers2

Closes @9054

Feature

### Technical

Added another check for librarians when displaying the edition search checkbox

### Testing

Logged in as AccountBot and searching something, the "solr edition" checkbox should not be visible. After adding AccountBot as a librarian, the checkbox should be visible.

### Screenshot

Before Adding AccountBot as librarian:
<img width="1096" alt="image" src="https://github.com/internetarchive/openlibrary/assets/91789460/2e551673-013e-4a89-92c1-35651a9da78a">

After Adding AccountBot as librarian:
<img width="1096" alt="image" src="https://github.com/internetarchive/openlibrary/assets/91789460/1ca2556a-f2e6-4fe5-b45a-1e969c78c0f5">

### Stakeholders

@RayBB 
@seabelis

2024-04-16 14:53 UTC, RayBB requested changes
@quackers2 can you change it to use `is_librarian()` and `is_super_librarian()`?

Thanks!

2024-04-16 15:10 UTC, quackers2 commented
@RayBB Done!

2024-04-16 15:59 UTC, RayBB approved these changes
Great job! Now we just need staff to merge it.

2024-04-18 15:41 UTC, mekarpeles commented
lgtm, ty!

2024-04-18 15:41 UTC, merged