Add Arrow to dropdown list
internetarchive/openlibrary pull request #9135
Opened 2024-04-23 10:50 UTC by Spedi

Closes #9065 

This PR makes sure to correctly show the arrow on the _Add to List_ dropdown button on the Author page.

### Testing
1) Check an Author page and see if the arrow is shown correctly in the _Add to List_ button.

### Screenshot
![Screenshot from 2024-04-22 21-55-00](https://github.com/internetarchive/openlibrary/assets/64098698/407c03d0-c510-4c22-8af8-0de6228c4aef)

### Stakeholders
@RayBB

2024-04-23 11:59 UTC, RayBB commented
@Spedi your changes seem to have some unintended effects on the dropdown. Making a big indent and showing new text.
Can you fix this?
| Before | After |
|:-------:|:-----:|
| ![image](https://github.com/internetarchive/openlibrary/assets/921217/f1d51373-fb8d-4644-838c-b44538b7910f) | ![image](https://github.com/internetarchive/openlibrary/assets/921217/84590665-aa2d-48d5-8e4c-0573a001dc50) |

2024-04-23 21:01 UTC, Spedi commented
That's weird, I'll have a look at the codebase to find some answers. Do you have any idea about what this can be related to?

2024-04-23 21:14 UTC, Spedi commented
I suppose the error I made is that the changes "copy" the dropdown list that's on the _Want to Read_ button, so they inherit the indentation and the unwanted text. Do you think that's a possible explanation of the bug?

2024-04-23 21:51 UTC, Spedi commented
The problem seems to go away if I add `old-style-lists` to `<div class="generic-dropper__dropdown old-style-lists">
      $:dropdown_content
    </div>`.
The thing is that the same type of template goes to the _Want to Read_ dropdown too, which is something that we don't want. Should we manage the two dropdowns differently? If yes, how can I try to do that, do you have any suggestions?

2024-04-23 22:13 UTC, Spedi commented
![Screenshot from 2024-04-24 00-11-34](https://github.com/internetarchive/openlibrary/assets/64098698/68e3cdf0-82b6-48a5-b5fe-10dddf7c7e07)

Changing everything as it was before the PR, and changing the visibility of arrow to visible in the `old-style-lists` css styling should work, since I tried to do it manually with the Inspect function of the browser.
However if I test the code I don't see the changes, since the visibility is set to _hidden_. 
How is it possible if I set it to _visible_ in the code?

2024-04-26 14:14 UTC, RayBB commented
@Spedi in reviewing your PR, I also noticed that it is weird that the visibility is set to hidden in some cases. I don't have the time to dig into it now but perhaps if you can uncover that (it could be in the JS?) then you might be able to find a nice solution.

2024-04-30 16:53 UTC, Spedi commented
I'm still trying to work on it.
I've tried disabling JS on the Dev Tools but it had no effect on the result, so maybe the problem isn't there.
Could it be a problem of CSS specificity?

2024-05-01 22:32 UTC, RayBB commented
It can be the CSS specifically. It likely has to do with nested css which can make it a bit tricky to untangle.
I imagine this is why the code was left a little messy like this with the old styles class.
Have tried looking at other dropdowns on the site to compare the html/css?

2024-05-09 00:37 UTC, jimchamp requested changes
Thanks @Spedi, and sorry for the very late review!

I think that we should avoid changes to `openlibrary/templates/lib/dropper.html`, which is meant to be a generic base component for all droppers.

I think if you remove this [CSS rule](https://github.com/internetarchive/openlibrary/blob/ca46cbfe87af6e81dabc966baa5b75c827097879/static/css/components/mybooks-dropper.less#L30-L32), the arrow will be rendered.

2024-05-09 00:44 UTC, jimchamp commented
> However if I test the code I don't see the changes, since the visibility is set to hidden.
How is it possible if I set it to visible in the code?

@Spedi, when a `.less` file is changed, it has to be compiled into CSS.  Try running the following after you make a change, and see if it helps:
`docker compose exec web make css`

If you're doing a lot of CSS work, it may be better to run the following:
`docker compose exec web npm run watch-css`

`watch-css` will build the CSS assets every time a `.less` file is saved.

2024-05-09 11:20 UTC, Spedi commented
@jimchamp Should I run `docker compose exec web npm run watch-css` while running `docker compose up`?

2024-05-09 12:37 UTC, jimchamp commented
Yes.  Your web container needs to be running, so run `docker compose up` first.  Alternatively, you can run `docker compose run --rm home make css` without first running `docker compose up`.

2024-05-09 13:42 UTC, Spedi commented
@jimchamp It worked! 
Made the correct changes, gonna do a PR soon, thank you and @RayBB for the patience!

2024-05-09 13:47 UTC, Spedi reviewed
This should close the issue, linking some pictures of the new dropdown list:
![Screenshot from 2024-05-09 15-41-34](https://github.com/internetarchive/openlibrary/assets/64098698/e4454800-0548-4264-8296-3962e82c1253)
![Screenshot from 2024-05-09 15-41-42](https://github.com/internetarchive/openlibrary/assets/64098698/b83c389d-9fa9-46de-b266-c13426524da3)

2024-05-09 16:41 UTC, jimchamp approved these changes
This looks good to me.  Will revert the `my_books/dropper`, then merge when the tests pass.

2024-05-09 16:41 UTC, jimchamp commented on openlibrary/templates/my_books/dropper.html
> +  $ additional_classes += '  old-style-lists'
```suggestion
  $ additional_classes += ' old-style-lists'
```

2024-05-09 16:46 UTC, merged