remove unused utils
internetarchive/openlibrary pull request #9180
Opened 2024-04-29 01:03 UTC by RayBB

Closes #

### Technical

### Testing

### Screenshot

### Stakeholders

2024-05-09 18:00 UTC, jimchamp requested changes
Thanks @RayBB!  The changes to the `excerpts` template are causing errors on the book edit page.  Switching from string interpolation to string concatenation should fix things.

2024-05-10 11:05 UTC, RayBB commented on openlibrary/templates/books/edit/excerpts.html
> +                        {{pages ? `From page ${pages}.` : "";}}
@jimchamp good catch... it is fixed as you suggested!

2024-05-13 14:59 UTC, cdrini commented
Howdy folks, I've been thinking about this one and I think it might be best for us to close this. Even if we remove the places where our jsdef code uses e.g. `cond`, it's _expected_ that jsdef codeblocks should have access to these python globals. Removing the JS implementations here will make our code brittle, especially since we don't really have strong tests to verify that our python/jsdef templates are valid.

2024-05-13 15:02 UTC, cdrini commented
To clarify, here is what I mean by jsdef using these files:

https://github.com/internetarchive/openlibrary/blob/1860c2562819330bf4657f8ed13d2c3d0ea336e2/openlibrary/templates/subjects.html#L84-L91

The `cond` call here uses the window.cond definition when this template is converted to/called from the JS.

2024-05-13 15:04 UTC, RayBB commented
@cdrini thanks for replying.

Should we also keep `focusNextInputField` ?

Do we need to keep the `window.cond = cond;` for jsdef to work?
Or would it be feasible to move these to a window.jsdef.cond so they're not taking up so much at the top of index.js?

2024-05-13 15:06 UTC, cdrini commented
`focusNextInputField` looks entirely unused; that looks like we can drop :+1: We do need the `window.cond` exposure in order for jsdef to work atm; if we wanted to change that, we would need to modify the way that the jsdef converts the templates to JS to check a certain global eg a JSDEF global. That would be nice in some future! But a little complicated to achieve. We'd need to change the parser to basically alter all globals to pull them from somewhere else. Here: https://github.com/internetarchive/openlibrary/blob/b46ff5135473c003f191d804bdd3b07cfa2c37cb/openlibrary/plugins/upstream/jsdef.py

2024-05-13 15:12 UTC, RayBB commented
@cdrini sounds good to me. I've pushed code with a comment about this and removing `focusNextInputField`

2024-05-20 16:02 UTC, cdrini approved these changes
Lgtm! Tested on testing (the only place I can think where this might apply is the "add one?" link for description, which focusses on the description box; still works!) + can't find any references to that method.

2024-05-20 16:03 UTC, merged