Fix some i18n errors
internetarchive/openlibrary pull request #9214
Opened 2024-05-03 14:21 UTC by cdrini

Closes #9213

### Technical

### Testing

### Screenshot

### Stakeholders

2024-05-03 16:06 UTC, merwhite11 requested changes

2024-05-03 20:24 UTC, cdrini commented on openlibrary/templates/account/readinglog_stats.html
Ah nope! That should be there, otherwise the text will be display without a space between "following" and "these instructions 👍

2024-05-04 00:39 UTC, merwhite11 commented on openlibrary/templates/account/readinglog_stats.html
Is 'these instructions' going to appear as a blue hyperlink text? In that case, isn't the space already accounted for after 'follow'? And then there would be a hyperlinked space before [' these instructions'](https://openlibrary.org/help/faq/editing.en#author-identifiers-purpose)

2024-05-04 02:11 UTC, cdrini commented on openlibrary/templates/account/readinglog_stats.html
Ohhhh I'm sorry, I thought the code snippet you included was what was in the document not what you were proposing at change it to! Haha you're completely correct, good catch! Will take a look when I'm back next week 👍

2024-05-10 19:55 UTC, merged