added function to add/update multiple query parameters
internetarchive/openlibrary pull request #9306
Opened 2024-05-20 20:25 UTC by IlyaMckay

Closes #9303 

fix

### Technical

Everything done as proposed by the team

### Testing

n/a

### Screenshot

n/a

### Stakeholders

@scottbarnes

2024-05-20 21:50 UTC, IlyaMckay commented
Sorry for inconviniece but once again I commited out of branch #[0d8f217](https://github.com/internetarchive/openlibrary/pull/9306/commits/0d8f217870148d9a6f7176c7a3843664a34e1272) (it happens everytime when I have to re-new existing commit and I don't understang what I'm doing wrong).

2024-05-21 15:18 UTC, scottbarnes requested changes
Thanks for this, @IlyaMckay. It's a really good start. Please see my feedback for some suggestions, and please remember to always test each PR to make sure it does what is requested in the issue.

2024-05-21 15:18 UTC, scottbarnes commented on openlibrary/plugins/openlibrary/js/team.js
What about something like the following, starting around line 67:
```javascript
roleFilter.addEventListener('change', (e) => {
    filterTeam(e.target.value, departmentFilter.value);
    updateURLParameters({
        role: e.target.value,
        department: departmentFilter.value
    });
});
departmentFilter.addEventListener('change', (e) => {
    filterTeam(roleFilter.value, e.target.value);
    updateURLParameters({
      role: rolefilter.value,
      department: e.target.value
    });
});
```
I think this should make it so that whenever either the `role` or `department` is changed via the drop down menus, the URL should update to reflect the change.

But this won't be enough I think, because it just updates the URL -- but we have nothing to read the initial URL to set the sort from that. So you'll want to add something similar to the following in `initTeamFilter()`:
```javascript
    const initialSearchParams = new URL(window.location.href).searchParams;
    const initialRole = initialSearchParams.get('role');
    const initialDepartment = initialSearchParams.get('department');
```
Then you'll want to call `filterTeam()` near the bottom in the `// on page load` section, with something like `filterTeam(initialRole, initialDepartment);`

That should get it to a point where if you visit http://localhost:8080/about/team?role=fellow&department=communication you see what you expect in terms of the avatars.

But if that works, it still won't be enough, because if you experiment with this, you'll probably find that the drop down menu when you visit http://localhost:8080/about/team?role=fellow&department=communication doesn't display what you'd expect, so you'll need to update that as well.

2024-05-22 17:41 UTC, scottbarnes commented
@IlyaMckay, I was just thinking about this, and I think--when it comes to reading patron input for a URL with query parameters (i.e. `role` and `department`)--we should probably be reading the values for `role` and `department` from the Python endpoint, so that it's more clear to people looking at the entrypoint what the API does.

I want to look to see how we handle this sort of thing more generally first, and I don't have time just now, but I wanted to alert you right away to reduce the likelihood you'd need to rewrite anything.

As a quick summary of what I mean, you can see how `/about/team` is defined, along with `/addbook`, and how URL parameters are extracted and passed along here: https://github.com/internetarchive/openlibrary/blob/cd46a0ae7c08740ba3d2608d1848058e090f9a72/openlibrary/plugins/openlibrary/code.py#L228-L247.

I think we probably want to do something similar for `/about/team` as we do for `/addbook`.

More on this syntax with `web.input` can be found [here](https://webpy.org/cookbook/input).

I will try to get back to today.

2024-05-22 19:38 UTC, mekarpeles commented
@IlyaMckay, a screenshot is applicable for this PR, if you would like this re-reviewed, please update the initial comment to include one! Otherwise it may be closed. 

<img width="180" alt="Screenshot 2024-05-22 at 12 37 44 PM" src="https://github.com/internetarchive/openlibrary/assets/978325/e1fe61d9-1cba-4c0c-99d4-dab2838108c5">

2024-05-22 23:09 UTC, scottbarnes commented
@IlyaMckay, Please ignore what I said about the Python stuff--let's do it all in JavaScript. I will edit that Python comment so it is not confusing. Instead just stick to what was mentioned in the code review: https://github.com/internetarchive/openlibrary/pull/9306#discussion_r1608515671.

2024-05-23 00:27 UTC, IlyaMckay commented
> @IlyaMckay, Please ignore what I said about the Python stuff--let's do it all in JavaScript. I will edit that Python comment so it is not confusing. Instead just stick to what was mentioned in the code review: [#9306 (comment)](https://github.com/internetarchive/openlibrary/pull/9306#discussion_r1608515671).

Today I tried a little but didn't understand where this route leads (`/type/edition`) and recieved an error message from template engine that __some_dunder()__ expects 1 argument but were provided 3 😄 
``` 
def GET(self):
        d = {'type': web.ctx.site.get('/type/edition')}

        i = web.input()
        role = i.get('role') and web.ctx.site.get(i.role)
        department = i.get('department') and web.ctx.site.get(i.department)

        if role:
            d['role'] = [role]

        if department:
            d['department'] = [department]

        page = web.ctx.site.new("", d)
        return render.edit(page, self.path, 'About Team')
```
So, if you say it's not valid anymore - that's ok, thank you!

2024-05-23 00:34 UTC, IlyaMckay commented
> @IlyaMckay, a screenshot is applicable for this PR, if you would like this re-reviewed, please update the initial comment to include one! Otherwise it may be closed.
> <img alt="Screenshot 2024-05-22 at 12 37 44 PM" width="180" src="https://private-user-images.githubusercontent.com/978325/332936087-e1fe61d9-1cba-4c0c-99d4-dab2838108c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MjM3NjgsIm5iZiI6MTcxNjQyMzQ2OCwicGF0aCI6Ii85NzgzMjUvMzMyOTM2MDg3LWUxZmU2MWQ5LTFjYmEtNGMwYy05OWQ0LWRhYjI4MzgxMDhjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwMDE3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZjgzOTU5ZGNmMTkyOWVhMGZjOTgxN2UwZmNkNDJiNjg3MGM3MzA3OTQ5ZWNhYjI4ZDA2YWQxOTEzZGRhZDA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uPQSvBuUrsrGUMt8lpYeH3ICTDdYBNAbFEDGU1ZAfg8">

I'm sorry for that - I'll add a screenshot when will be able to start a docker and test new changes (have some problems with docker desktop).

2024-05-23 00:42 UTC, rebecca-shoptaw commented
@IlyaMckay Dropping by to say that if you're having a few more git issues, we just did a big overhaul of the [Git Cheat Sheet](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#forking-and-cloning-the-open-library-repository) including a new [troubleshooting section](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#troubleshooting-your-pull-request) which may help you work through whatever's going on. 🙂 

Also if your Docker issues persist and you'd like to try testing on GitPod, you can see what the changes in this pull request currently look like here: [https://gitpod.io/#https://github.com/internetarchive/openlibrary/pull/9306](https://gitpod.io/#https://github.com/internetarchive/openlibrary/pull/9306).

2024-05-23 00:45 UTC, scottbarnes commented
> Today I tried a little but didn't understand where this route leads (`/type/edition`) and recieved an error message from template engine that **some_dunder()** expects 1 argument but were provided 3 😄

I am sorry -- I tried to prevent inadvertently creating more work for you, but that's exactly what I did.

Rather than handle the URL parameters via the Python endpoint in `openlibrary/plugins/openlibrary/code.py`, you should be able to handle them by adding some `const`s to `initTeamFilter`, as mentioned here: https://github.com/internetarchive/openlibrary/pull/9306#discussion_r1608515671.

2024-05-23 01:25 UTC, IlyaMckay commented
> > Today I tried a little but didn't understand where this route leads (`/type/edition`) and recieved an error message from template engine that **some_dunder()** expects 1 argument but were provided 3 😄
> 
> I am sorry -- I tried to prevent inadvertently creating more work for you, but that's exactly what I did.
> 
> Rather than handle the URL parameters via the Python endpoint in `openlibrary/plugins/openlibrary/code.py`, you should be able to handle this by adding some `const`s to `initTeamFilter` and using them as mentioned here: [#9306 (comment)](https://github.com/internetarchive/openlibrary/pull/9306#discussion_r1608515671).

This morning I added those 'consts' and changed everything as you described at #9306 (comment)](https://github.com/internetarchive/openlibrary/pull/9306#discussion_r1608515671) but all day today I have the same problem with docker. When I docker compose 'build' and than 'up' the OL's "Development version" it's builds without those lines that I added and I don't understand why.
![5-22-2024 (22-12-17)](https://github.com/internetarchive/openlibrary/assets/104564914/26badb99-2c94-4b81-a018-40fcc8db5d02)
![5-22-2024 (22-18-55)](https://github.com/internetarchive/openlibrary/assets/104564914/945e0390-b6ed-4df6-ac0c-e7593d022d55)

2024-05-23 01:33 UTC, rebecca-shoptaw commented
> This morning I added those `consts` and changed everything as you described at #9306 [(comment)](https://github.com/internetarchive/openlibrary/pull/9306#discussion_r1608515671) but all day today I have the same problem with docker. When I docker compose `build` and than `up` the OL's "Development version" it builds without those lines that I added and I don't understand why.

@IlyaMckay Just popping in quickly again because I got the notification and have had my share of Docker issues -- seems you just need to get Docker to [build your JavaScript changes](https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide#building-css-and-js). 

If you run `docker compose run --rm home npm run-script watch` the dev version should auto-update every time you make a JavaScript change!

2024-05-23 01:39 UTC, IlyaMckay commented
> > This morning I added those `consts` and changed everything as you described at #9306 [(comment)](https://github.com/internetarchive/openlibrary/pull/9306#discussion_r1608515671) but all day today I have the same problem with docker. When I docker compose `build` and than `up` the OL's "Development version" it builds without those lines that I added and I don't understand why.
> 
> @IlyaMckay Just popping in quickly again because I got the notification and have had my share of Docker issues -- seems you just need to get Docker to [build your JavaScript changes](https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide#building-css-and-js).
> 
> If you run `docker compose run --rm home npm run-script watch` the dev version should auto-update every time you make a JavaScript change!

OMG, I saw this part in docs but just didn't link it in my head. Seems like I was over focused on my docker desktop... Thank you!

2024-05-23 21:18 UTC, IlyaMckay commented
@scottbarnes 
While testing how those chunks you proposed work, I noticed that when I open the endpoint in a different tab/browser, I get to the endpoint but the filters on the page are shown as All/All. Additionally, if I go to the endpoint `about/team`, the template doesn't show the "profile cards"/photos. 
So, I took the liberty to slightly refine your chunks to ensure everything works as users expect and nothing deviates from the expected behavior.
I added default values:
```
const initialRole = initialSearchParams.get('role') || 'All';
const initialDepartment = initialSearchParams.get('department') || 'All';
```
and passed the values to the filter:
```
roleFilter.value = initialRole;
departmentFilter.value = initialDepartment;
```
So, now everything works as expected. I think this PR is ready to be reviewed.

2024-05-23 22:07 UTC, scottbarnes approved these changes
Thanks, @IlyaMckay. Looks good to me!

Tested:
- loading http://localhost:8080/about/team displays what I expect to see and facets by `All` for `role` and `department;
- faceting by role and department displays what I'd expect to see on the page as the settings change;
- when faceting using the drop down menus, the updates to the display and URL bar do not require a page reload;
- faceting by role and department updates the URL bar, e.g. http://localhost:8080/about/team?role=fellow&department=communication;
- page reloads preserve the selected facets;
- opening a new tab and visiting a URL with the facets set via URL parameters works as expected, e.g. with http://localhost:8080/about/team?role=fellow&department=communication; and
- when first loading the page while using URL parameters (e.g. at http://localhost:8080/about/team?role=fellow&department=communication), the correct facets are selected in the drop down menu.

Great job adapting the code snippets to make everything work together. :)

2024-05-23 22:10 UTC, merged