Fetch `/collections` pages from DB, not cache
internetarchive/openlibrary pull request #9382
Opened 2024-06-03 20:59 UTC by jimchamp

Closes #9364

Removes `CacheablePathsProcessor` from the application's processor chain.  Collections pages will now be fetched from the DB.

### Technical

### Testing

### Screenshot

### Stakeholders

2024-06-04 16:57 UTC, cdrini requested changes
Ok I patch deployed this one! Dropping to P1 since it's no longer affecting production.

Can you revert the rest of the code in https://github.com/internetarchive/openlibrary/pull/9069 ? We can have a separate issue for fixing it up/bringing it back, but I'd rather not all this code which is now dead in the codebase, since we're not sure if/how we can fix it!

2024-06-05 18:56 UTC, jimchamp commented
I'm working on fixing the processor, so removing it doesn't make sense to me.

2024-06-05 18:56 UTC, cdrini commented
Sounds good to me!

2024-06-05 18:56 UTC, cdrini approved these changes

2024-06-05 18:57 UTC, merged