Fixed Read More Button Display Logic to Avoid Unnecessary Display
internetarchive/openlibrary pull request #9627
Opened 2024-07-25 13:15 UTC by CodeMaverick2

# Issue ->  https://github.com/internetarchive/openlibrary/issues/9329
## Description

This PR addresses an issue where the "Read more" button was displayed even when it made the section longer than the fully expanded content. This led to a confusing user experience, as the "Read more" button was not serving its intended purpose. The following changes have been made to resolve this issue:

## Changes

1. **Capture "Read More" Button Height**:
    - The height of the "Read more" button is now captured during initialization to ensure accurate calculations.

2. **Update Condition in `reset` Method**:
    - The logic that determines whether the "Read more" button should be displayed has been updated to include the height of the button. This ensures the button is only shown when it makes sense.

## Impact

- **Improved User Experience**: The "Read more" button is now only displayed when necessary, preventing unnecessary clutter and confusion.
- **Correct Layout Behavior**: Ensures the layout behaves as expected, with the "Read more" button enhancing usability rather than detracting from it.

## Screenshots
![Screenshot from 2024-07-25 18-43-42](https://github.com/user-attachments/assets/fd72ad9e-2e81-4208-9622-44f93840f087)

2024-07-31 09:53 UTC, RayBB commented
@CodeMaverick2 it looks like there is a test that broke because of this change. You'll need to investigate if the test should be changed or if something is actually broken.


@cdrini I am not so familiar with this part of the code and can't really dig into this issue anytime soon. Could we get someone else to review this?

2024-08-30 20:37 UTC, cdrini requested changes
Thanks @CodeMaverick2 . Please revert the unnecessary changes. And please add testing instruction on how you tested to confirm this change worked. If you cannot test this PR, we will be unable to review your changes.

2024-08-30 20:37 UTC, cdrini commented on openlibrary/plugins/openlibrary/js/readmore.js
> +        if (this.$content.scrollHeight <= (this.collapsedHeight + this.$readMoreButton.offsetHeight + 1)) {
This should be the only change that is necessary here. Please revert the other changes since they are unnecessary.

2024-09-11 20:03 UTC, CodeMaverick2 commented
@RayBB Sure i will do that

2024-09-11 20:17 UTC, closed without merging