Add [alt] attributes to images
internetarchive/openlibrary pull request #9644
Opened 2024-07-28 19:25 UTC by Souvik-Cyclic

Closes #9629 

Adds [alt] attributes to images for Improving Accessibility Score of Book Pages

### Stakeholders
@cdrini

2024-07-29 19:33 UTC, cdrini commented on openlibrary/macros/EditionNavBar.html
>      </span>
Heads up: This was meant to replace the span with the button, and you'll have to update some the CSS as well

2024-08-14 22:45 UTC, jimchamp requested changes
Thanks for your patience, @Souvik-Cyclic!

This is mostly good.  The styling of the `Go to next section` button will need to be updated before this can be merged in.

2024-08-14 22:45 UTC, jimchamp commented on openlibrary/macros/EditionNavBar.html
> +  </button>
```suggestion
    <button class="nav-arrow" title="$_('Go to next section')">
      <img src="/static/images/nav-arrow.svg" alt="">
    </button>
```
Indentation level of this code block should remain the same.

2024-08-14 22:45 UTC, jimchamp commented on openlibrary/macros/EditionNavBar.html
> +  </button>
Fix styling of button:
![image](https://github.com/user-attachments/assets/3d09a19d-f0fb-434e-9b52-bcb6820769b4)

2024-08-16 21:32 UTC, Souvik-Cyclic commented
I fixed the indentation, but I had trouble adjusting the button's styling. I tried changing the CSS, but the changes didn't take effect. @jimchamp, could you help me with this?

2024-08-16 22:40 UTC, jimchamp commented
Sure!  Every time a change is made to a `.less` file, the change needs to be compiled into CSS before it can take effect.  You can do this by running the following:
```bash
docker compose exec web make css
```

More information about developing Open Library's front-end can be found [here](https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide).

2024-08-17 09:50 UTC, Souvik-Cyclic commented
I am closing this PR due to an error on my part. I will submit a new one shortly.

2024-08-17 09:50 UTC, closed without merging

2024-08-17 10:14 UTC, Souvik-Cyclic commented
@jimchamp What exactly happened that so many commits started showing in this one ?