Move author identifiers to version-controlled YAML file
internetarchive/openlibrary pull request #9769
Opened 2024-08-18 07:10 UTC by fakegithub01

Closes [#9666](https://github.com/your-repo/issues/9666)

Refactor

### Technical

- Created a new YAML file: `openlibrary/plugins/openlibrary/config/author/author.yml`.
- Updated `_get_author_config()` function to load author identifiers from the new `author.yml` file.

### Testing

- Verify that the application correctly loads author configurations from `author.yml`.
- Test relevant parts of the application to ensure no disruption of existing functionality.

### Stakeholders
@jimchamp @mekarpeles

2024-08-21 00:12 UTC, jimchamp requested changes
Thanks @fakegithub01!  Will QA this branch after the requested changes have been made.

2024-08-21 00:12 UTC, jimchamp commented on openlibrary/plugins/openlibrary/config/author/author.yml
> +    value: '2021-05-06T22:11:18.795025'
```suggestion
```
We only want the `identifiers` in this file, as per the requirements.

2024-08-21 00:12 UTC, jimchamp commented on openlibrary/plugins/openlibrary/config/author/author.yml
> +    key: /type/object
```suggestion

```
Remove unnecessary fields.  Ensure that the file ends with a newline character.

2024-08-21 00:12 UTC, jimchamp commented on openlibrary/plugins/upstream/utils.py
> +    with open('openlibrary/plugins/openlibrary/config/author/author.yml') as in_file:
```suggestion
    with open('openlibrary/plugins/openlibrary/config/author/identifiers.yml') as in_file:
```
Update name of author identifier configuration file to follow same pattern as the edition identifier config file.

2024-08-25 19:05 UTC, Freso requested changes
You didn’t actually rename the `author.yml` file as you changed the `open()` call.

2024-08-26 14:41 UTC, fakegithub01 commented
@Freso @jimchamp I have renamed the `author.yml` file to `identifiers.yml` as reviewed for changes. Can you please review the PR?

2024-08-26 15:30 UTC, Freso reviewed
Seems fine to me. I have left a couple of comments about related documentation that is _slightly_ off now, but I don’t know if Jim will want that changed or not. I just wanted to note the filename so once Jim is available to review this, he wouldn’t have to point that out, so you could get this PR done with sooner. :)

2024-08-26 15:30 UTC, Freso commented on openlibrary/plugins/upstream/utils.py
> +    # Load the author config from the author.yml file in the author directory
We’re only loading `identifiers` of the author config here… but that’s also currently the entirety of the config. I don’t know if that’s something that needs changing or not.

2024-08-26 15:30 UTC, Freso commented on openlibrary/plugins/upstream/utils.py
>      Any changes to /config/author page require restarting the app.
The `/config/author` page isn’t getting loaded anymore, so restarting won’t do much… :)

2024-08-27 00:45 UTC, jimchamp approved these changes
Thanks, @fakegithub01!
I've tested this locally by adding a new author identifier entry.  Verified that the new ID is present in the identifiers drop-down in the author edit screen.  Newly added IDs were also present on the author view page.

Will open a follow-up PR that updates the documentation for these functions, and the equivalent edition identifier configuration functions, which, I suspect, were not updated.

2024-08-27 00:47 UTC, merged