Fix URL redirect for go back link
internetarchive/openlibrary pull request #9795
Opened 2024-08-23 23:44 UTC by schu96

Closes #9688

Fix

### Testing
I deleted an entry until the "This page has been deleted" page was shown. I checked that the previous expected behavior worked, then copied and pasted the entry's URL into a new browser window to check if the 'go back' link would redirect to the OpenLibrary homepage.

### Stakeholders
@jimchamp

2024-08-26 16:49 UTC, mekarpeles commented
We may have (a) a few style tweaks and (b) numerical formatting to make to our search results + star ratings PR, though overall looking good. And the half star and whole stars should be the same gold color

![image](https://github.com/user-attachments/assets/d4c6b2d0-f727-43e7-9919-a11e368d51b4)

perhaps we're missing a style rule for reader-stats__star. --half currently has the style font-size: 1.5em; which should probably be  removed (the size should be on whatever the base class is that --half overwrites, and this base class also needs the right @gold ffd400 color

2024-08-26 22:45 UTC, schu96 commented
@mekarpeles Is your comment for intended for this [PR](https://github.com/internetarchive/openlibrary/pull/9790)?

2024-08-27 01:23 UTC, jimchamp requested changes
Thanks, @schu96!
This is a great start.  Please check out my review notes, and apply your new click handler to all "Go Back" links.

2024-08-27 01:23 UTC, jimchamp commented on openlibrary/templates/type/delete/view.html
> +      <li><a href="javascript:;" id="go-back">$_("Go back where I came from")</a></li>
```suggestion
      <li><a href="javascript:;" class="go-back-link">$_("Go back where I came from")</a></li>
```
There are a number of these links throughout the codebase.  I think that it's best to identify them with a common class, then add the click listener to all elements having this class.

Doing a quick search for `history.go` with my IDE yielded 14 matches.  I'd expect all of these to be updated to use your click listener in this branch.

2024-08-27 01:23 UTC, jimchamp commented on openlibrary/plugins/openlibrary/js/index.js
> +            .then(module => module.initGoBackRedirect(goback))
```suggestion
    const backLinks = document.querySelectorAll('.go-back-link')
    if (backLinks.length) {
        import (/* webpackChunkName: "go-back-links" */ './go-back-links')
            .then(module => module.initGoBackLinks(backLinks))
```
A couple of changes here:
1. Select all elements on the page that have the `go-back-link` class, then pass them to the `init` method (which should be updated to handle a [`NodeList`](https://developer.mozilla.org/en-US/docs/Web/API/NodeList) of elements).
2. Update the name of the `init` function, and the `delete-redirect.js` file name.  When I see the name `delete-redirect.js`, it's not clear that the code is related to the "Go Back" links.  I expect that naming this something more obvious will make the code easier to maintain (especially as my memory of this PR fades over time).

2024-09-05 20:25 UTC, jimchamp approved these changes
Seems to be working as expected.  Thanks, @schu96!

2024-09-05 20:26 UTC, merged