Added link tracks to all download options
internetarchive/openlibrary pull request #9837
Opened 2024-09-02 18:29 UTC by merwhite11

Closes #9782 

Adds link tracks to all download options in sidebar so that we can have a baseline reading of patron activity. This reading will then be used to compare the effectiveness of the work-in-progress [Read dropdown redesign
](https://github.com/internetarchive/openlibrary/issues/5831). 
### Technical

### Testing

Click a download option and ensure that data for SideBar|Download is being recorded in stats. 
### Screenshot

### Stakeholders

@cdrini @mekarpeles 
@SivanC -- just letting you know about this one for when you want to compare SideBar|Download with your eventual ReadDropper|Download feature.

2024-09-05 17:29 UTC, mekarpeles requested changes
We probably want different actions for the different download types. Instead of Sidebar, you might want to call *that* `Download` and then after the `|` the type

e.g. `Download|HTML`

2024-09-05 17:47 UTC, merwhite11 commented
@mekarpeles I see what you're saying. How then would we distinguish the `Download | HTML` from a click in Sivan's `Download | HTML` in the Read dropdown?

2024-09-15 17:22 UTC, mekarpeles commented
One option is to have something like `Download|SidebarHTML` or `DownloadSidebar|HTML`. It depends how we want to split / roll-up the analytics.

Is it most useful to see the total number of downloads? The total number of downloads per type? Either way, so long as we segment/bucket the types we should be able to see what we need -- it just may take 2 queries + manual maths to get the totals we want.

I haven't spent much time thinking about the best solution. If we did `Download|<Location><Format>` then we'd get a total number of downloads and we'd be able to be able to easily add up the `Format` counts per `Location`. So that might be my strategy.

2024-09-17 00:00 UTC, merwhite11 commented
@mekarpeles I agree with the `Download|<Format>_<Location> ` strategy. I will run by Drini before I make the changes.

2025-01-31 19:52 UTC, cdrini approved these changes
Lgtm! Apologies for the delay @merwhite11 , I forgot to respond to your question on this!

2025-02-01 15:27 UTC, merged