Unescape HTML entities in search result page titles.
internetarchive/openlibrary pull request #9882
Opened 2024-09-17 02:27 UTC by SeraphimRP

Closes #9787.

### Technical

This parses the title with [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) to unescape any HTML entities that might get mistakenly created in the search process. This implementation avoids XSS attempts as it takes advantage of the browser's HTML parser directly as opposed to fiddling with the document's DOM to make a workaround.

I attempted to seek out why this might be the case to begin with but admittedly I didn't get very far. It's unclear to me whether the fetched partials are always escaped HTML (even to the extent of the title), but I'm not sure if that's due to my unfamiliarity with the codebase or if this is intended behavior to avoid XSS.

Also, just to note, in my local testing I had to coerce the search box to display the query in the title. Most of the time it just displayed "search" until I managed to get it to show up by adding a subject.

### Screenshot

| Before | After |
| ------ | ----- |
| <img width="852" alt="image" src="https://github.com/user-attachments/assets/19038225-5090-4774-8135-e06e31175112"> | <img width="850" alt="image" src="https://github.com/user-attachments/assets/c5b34f67-1b3c-4d6c-9ef2-e0e2581172dd"> |

### Stakeholders

@jimchamp

2024-09-17 21:43 UTC, jimchamp requested changes
Thanks @SeraphimRP!

I'm not sure if it makes sense to use `DOMParser` for this.  It's probably best if this is set server-side, like it was up until recently.  Doing so would also ensure that the title is set when there are no search results.

Today, the title string is constructed [here](https://github.com/internetarchive/openlibrary/blob/2640c4e9c78c806f8720a53439c538bddaa38640/openlibrary/templates/search/work_search_selected_facets.html#L13-L19), and the value used inside of the `<title>` element is set [here](https://github.com/internetarchive/openlibrary/blob/2640c4e9c78c806f8720a53439c538bddaa38640/openlibrary/templates/search/work_search_selected_facets.html#L57).  If you cut these lines from the `work_search_selected_facets.html` template and insert them below the `$def with` line in [`work_search.html`](https://github.com/internetarchive/openlibrary/blob/2640c4e9c78c806f8720a53439c538bddaa38640/openlibrary/templates/work_search.html), things will be back to the way they used to be.

Can you make those changes, remove `title` from the `/partials` response [here](https://github.com/internetarchive/openlibrary/blob/2640c4e9c78c806f8720a53439c538bddaa38640/openlibrary/plugins/openlibrary/code.py#L1160), and remove the JS code that sets the title?

2024-09-24 04:05 UTC, SeraphimRP commented
Hello. Just noting that this is still on my radar, weekend got pretty busy! I'll get these changes submitted soon. Thank you for the direction!

2024-10-04 15:47 UTC, jimchamp commented
@SeraphimRP, are you still working on this?

2024-10-07 13:55 UTC, jimchamp commented
Closing as abandoned.

2024-10-07 13:55 UTC, closed without merging