Expand author roles
internetarchive/openlibrary pull request #9901
Opened 2024-09-23 02:55 UTC by hornc

Closes #9844

### Technical

Builds on PR #9797 , which should be merged first and this PR rebased for ease of review. #9797 changes very many test files, this PR modifies fewer and should be more contained to address just #9844.

### Testing

### Screenshot

### Stakeholders

2025-02-10 20:24 UTC, hornc commented
@cdrini are you able to give this a review?

2025-02-19 22:06 UTC, tfmorris requested changes
@hornc feel free to use Github "request review" to tag me.

This looks great. I added a couple of roles, but I don't have a good feel for what others might be missing because the test data doesn't have a very big variety. Do you have an easy way of surveying your available MARC data?

2025-02-19 22:06 UTC, tfmorris commented on openlibrary/catalog/marc/parse.py
> +    'comp.': 'Compiler',
```suggestion
    'comp.': 'Compiler',
    'ed.': 'Editor',
```
Alphabetized for a combination of pedantry and ease of scanning ;)

2025-02-24 00:52 UTC, hornc commented on openlibrary/catalog/marc/tests/test_data/bin_expect/ithaca_college_75002321.json
> +      "role": "Editor",
That is correct, they will be treated as co-authors, on both the work and the edition.

I ran the import locally to confirm.
This is the resulting work .yml:
```
authors:
-   author:
        key: /authors/OL5A
    type:
        key: /type/author_role
-   author:
        key: /authors/OL10A
    type:
        key: /type/author_role
-   author:
        key: /authors/OL11A
    type:
        key: /type/author_role
created:
    type: /type/datetime
    value: '2025-02-24T00:41:39.838663'
key: /works/OL1W
last_modified:
    type: /type/datetime
    value: '2025-02-24T00:41:39.838663'
latest_revision: 1
revision: 1
subject_places:
- New Jersey
subjects:
- Congresses
- Negative income tax
- Guaranteed annual income
- Labor supply
title: Work incentives and income guarantees
type:
    key: /type/work
```

and the edition .yml:
```
authors:
-   key: /authors/OL5A
-   key: /authors/OL10A
-   key: /authors/OL11A
by_statement: editors, Joseph A. Pechman, P. Michael Timpane
created:
    type: /type/datetime
    value: '2025-02-24T00:41:39.838663'
dewey_decimal_class:
- 361.6/2/09749
isbn_10:
- 0815769768
- 081576975X
key: /books/OL5M
languages:
-   key: /languages/eng
last_modified:
    type: /type/datetime
    value: '2025-02-24T00:41:39.838663'
latest_revision: 1
lc_classifications:
- HC107.N53 I58
lccn:
- '75002321'
notes:
    type: /type/text
    value: 'Papers and comments presented at the conference at Brookings Institution,
        Apr. 29-30, 1974, sponsored by the Brookings Panel on Social Experimentation.


        Includes bibliographical references and index.'
number_of_pages: 232
pagination: xiii, 232 p.
publish_country: dcu
publish_date: '1975'
publish_places:
- Washington
publishers:
- Brookings Institution
revision: 1
series:
- Brookings studies in social experimentation
source_records:
- ia:test-blah
subject_places:
- New Jersey
subjects:
- Congresses
- Negative income tax
- Guaranteed annual income
- Labor supply
subtitle: the New Jersey negative income tax experiment
title: Work incentives and income guarantees
type:
    key: /type/edition
works:
-   key: /works/OL1W
```

The "Editor" role is not even represented in the work, which is what #3084 is requesting.

2025-02-24 00:59 UTC, hornc commented on openlibrary/catalog/marc/tests/test_data/bin_expect/ithaca_college_75002321.json
> +      "role": "Editor",
... this now has me worried that there is a piece missing to make this a complete feature. 

It looks like `role` is only picked up by OL for what ends up in the `contributors` field on editions, and is lost for `authors`.

Also, only work level `authors` have a `role` in the model, but it seems that some of these additional roles are really more appropriate at the edition level...

For example, where should you place the 'illustrator' or 'translator' of Homer's _Odessy_? On the work, or on a specific edition?

2025-02-25 04:55 UTC, hornc commented on openlibrary/catalog/marc/tests/test_data/bin_expect/ithaca_college_75002321.json
> +      "role": "Editor",
With the last commit c0c0fba94c90e3a6e71b93627fd68980c7062cad  the role is now written to the work:

```
authors:
-   author:
        key: /authors/OL5A
    role: Editor
    type:
        key: /type/author_role
-   author:
        key: /authors/OL10A
    role: Editor
    type:
        key: /type/author_role
-   author:
        key: /authors/OL11A
    type:
        key: /type/author_role
created:
    type: /type/datetime
    value: '2025-02-25T04:50:42.454726'
key: /works/OL2W
last_modified:
    type: /type/datetime
    value: '2025-02-25T04:50:42.454726'
latest_revision: 1
revision: 1
subject_places:
- New Jersey
subjects:
- Congresses
- Negative income tax
- Guaranteed annual income
- Labor supply
title: Work incentives and income guarantees
type:
    key: /type/work
```

2025-03-20 02:43 UTC, tfmorris reviewed
Thanks for incorporating the additional roles. 

As for adding the role to the `authors` field of the work, I guess I'm not familiar enough with this area of the system to know whether it'll have the desired effect. My naÏve belief was that the only thing supported here was a list of author keys. I'm pretty sure there's no way in the UI to set a role for a work contributor.

They way I was thinking that this would have to work in the short term is to just add any 7xx's with a role of "author" to the `authors` list (but without any role). 

Sorry I'm not more help here, but I don't have time right now to dig in deep to see how this actually works.

2025-04-15 21:12 UTC, mekarpeles commented
As is, I don't think this will hurt anything, it may just be challenging to fully take advantage of?

2025-04-29 21:24 UTC, merged