Show toolbar and follow button for list visitor
internetarchive/openlibrary pull request #9908
Opened 2024-09-25 20:45 UTC by schu96

Closes #9337 

Fix

### Technical

Remove ```if/else``` condition, uses the ```lst['key']``` to determine if the user is the owner of the list and show relevant components within the ```account/view.html``` template.

### Testing

- [Create two user accounts](https://github.com/internetarchive/openlibrary/wiki/Creating-and-Logging-in-as-a-new-user-on-your-local-client) and use one account to create a list of books
- Navigate to the list page and check that the follow button does not appear within the list of lists and single list webpages.
- Sign out of the list creator account and sign into the other newly created account.
- Navigate to the created book list, verify that the follow button appears on the list page and that pressing follow will add the creator's account to the visitor's ```Following``` tab.

### Screenshot

![image](https://github.com/user-attachments/assets/d078aa37-9fb5-4790-8ad6-0cc49c532522)
![image](https://github.com/user-attachments/assets/af22bc64-67bc-4e43-99f2-6b73ad2c6e91)
![image](https://github.com/user-attachments/assets/7d3bb076-4a45-4ef4-b6e9-f5fc496e170d)
![image](https://github.com/user-attachments/assets/4c39180d-e4e4-4478-9d94-f9185d6442ea)

### Stakeholders

@jimchamp

2024-10-01 18:14 UTC, jimchamp requested changes
Thanks @schu96!  This is working well, but there are two things that are bothering me:

![Screenshot 2024-10-01 105524](https://github.com/user-attachments/assets/de3a8ce2-ca7e-423a-87db-8894308b0876)

1. There are two sets of navigation breadcrumbs.
2. The `databarView` macro doesn't appear in the top-right corner of the view.

I've left some suggested code changes that will partially address number 2.  In addition to those changes, you'll have to remove the breadcrumbs and the duplicate `databarView`, [here](https://github.com/internetarchive/openlibrary/blob/9eb111cc9514c27ff6aaa18b75b80f108e129c74/openlibrary/templates/type/list/view_body.html#L41-L47).

2024-10-01 18:14 UTC, jimchamp commented on openlibrary/templates/account/view.html
> +      $if page and mb.is_my_page:
```suggestion
      $if page:
```
Ensure that `databarView` always appears in the top-right corner of the view.

2024-10-01 18:14 UTC, jimchamp commented on openlibrary/templates/account/view.html
>          $:macros.databarView(page)
```suggestion
        $:macros.databarView(page, edit=mb.is_my_page)
```
Only show the edit button to the list's owner.

2024-10-01 18:14 UTC, jimchamp commented on openlibrary/templates/type/list/view.html
> +$:template
```suggestion
$:template

```
Add trailing newline to this file.

2024-10-08 15:18 UTC, jimchamp requested changes
So far, so good.  The duplicate breadcrumbs and `databarView` are [here](https://github.com/internetarchive/openlibrary/blob/9eb111cc9514c27ff6aaa18b75b80f108e129c74/openlibrary/templates/type/list/view_body.html#L41-L47), and should be removed.

2024-10-08 19:25 UTC, schu96 commented
Whoops, thanks for the reminder I had a complete airhead moment there

2024-11-14 00:59 UTC, jimchamp approved these changes
Thanks @schu96, and sorry for the massive delay...
This is great!  I'm going to switch things back such that the `databarView` isn't displayed for visitors, as there's not enough room for it and people can check the history table if they want to see the last edit date.
Will merge after I make the change and the tests pass.

2024-11-14 00:59 UTC, jimchamp commented on openlibrary/templates/account/view.html
> +      $if page and mb.is_my_page:
I was totally wrong about this!  The header is too crammed when `databarView` is present for visitors.

2024-11-14 01:04 UTC, merged