adding super librarians and 2024 fellows
internetarchive/openlibrary pull request #9933
Opened 2024-10-03 16:34 UTC by mekarpeles

Updates json for team page re: #9352 

### Technical

### Testing

### Screenshot

### Stakeholders

2024-10-03 17:01 UTC, mekarpeles commented on openlibrary/templates/about/team.json
> +    "ol_key": ""
```suggestion
    "name": "Stef Kischak",
    "title": "Engineering Fellow",
    "roles": ["fellow-2024"],
    "departments": ["engineering"],
    "projects": ["Wikisource Imports"],
    "photo_path": "https://github.com/user-attachments/assets/4d8dd2c9-7750-41f6-91e9-2ab5b27258cb",
    "personal_url": "https://pidgezero.one",
    "github_id": "pidgezero-one",
    "ol_key": ""
```

2024-10-08 18:50 UTC, Freso requested changes
Hope this is okay! :bow:

2024-10-08 18:50 UTC, Freso commented on openlibrary/templates/about/team.json
> +    "ol_key": ""
```suggestion
    "name": "Frederik “Freso” S. Olesen",
    "title": "Super Librarian",
    "roles": ["volunteer"],
    "departments": ["librarians"],
    "projects": [],
    "photo_path": "https://avatars.githubusercontent.com/u/177659",
    "personal_url": "https://freso.dk/",
    "favorite_book_url": "https://openlibrary.org/people/freso/lists/OL272257L",
    "github_id": "Freso",
    "ol_key": "Freso"
```

2024-10-08 19:43 UTC, mekarpeles commented on openlibrary/templates/about/team.json
> +    "ol_key": ""
```suggestion
  {
    "name": "Daniel Capilla",
    "title": "Super Librarian",
    "roles": ["volunteer"],
    "departments": ["librarians"],
    "projects": [],
    "photo_path": "https://avatars.githubusercontent.com/u/7125952",
    "github_id": "dcapillae",
    "personal_website": "https://dcapillae.wordpress.com",
    "ol_key": "dcapillae"
```

2024-10-09 19:20 UTC, mekarpeles commented on openlibrary/templates/about/team.json
> +    "photo_path": "",
```suggestion
    "photo_path": "https://github.com/user-attachments/assets/91b60336-05bf-48d7-9307-7654465e7434",
```

2024-10-28 18:01 UTC, merged