fail calls to openlibrary.php gracefully
internetarchive/openlibrary pull request #9977
Opened 2024-11-01 22:09 UTC by mekarpeles

Categorically fixes `IA_Lending_API` issue where Open Library breaks when `archive.org/services/openlibrary.php` not reachable

Was discovered when trying to hit https://openlibrary.org/account/loans. Because `archive.org/services/openlibrary.php` is currently blocked by mod_security WAF, the API was hitting non-json 403 response and dying.

Thie code path here was: `get_waitinglist_for_user` in `/openlibrary/openlibrary/core/waitinglist.py` which died while trying to call `waitlist.extend(WaitingLoan.query(userid=account.itemname))`. The `WaitingLoan.query` uses `core.lending.IA_Lending_API` which has a `_post` method https://github.com/internetarchive/openlibrary/compare/master...php-graceful-failure?quick_pull=1#diff-896c18b3ccfadfa425c7e24a86226343314fce7957d14a8023d3e159156b224bL1092 which has been patched to return `{}` instead of `raise` when a failure occurs.

2024-11-01 22:22 UTC, mekarpeles commented on openlibrary/core/lending.py
> +        except (JSONDecodeError, Exception):  # TODO: Narrow exception scope
We should split this into **just** `JSONDecodeError` and/or 403... And any other `Exception` and continue to raise

2024-11-01 22:25 UTC, cdrini requested changes
I think it might be more performant if we just return `{}` without making the request at all until it's back up.

Otherwise +1 to the longer term fix of properly handling JSONDecodeError + 403s without having this raise and break everything!

2024-11-01 22:37 UTC, mekarpeles commented on openlibrary/core/lending.py
> +        except (JSONDecodeError, Exception):  # TODO: Narrow exception scope
We might also consider using `timeout=1` or something to reduce the wait time for calls we know should be fast.

2024-11-02 00:03 UTC, cdrini commented
Mek tested, looks ok for now.

2024-11-02 00:03 UTC, cdrini approved these changes

2024-11-02 00:03 UTC, merged